### ISSUE TITLE
BioSimSpace tutorial - interactive MD - proposal for Protocol API changes

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#10]
# Initialise a short equlibration protocol.
protocol = BSS.Protocol.Equilibration(runtime=0.05, temperature_start=0, temperature_end=300, restrain_backbone=True)

--> We should modify the API to have users specify parameters with units e.g. runtime=0.05 ps  

To address questions from the audience this morning we could also add a __str__ method to a Protocol class so that users can easily print out all the parameters actually set by the Protocol (rather than having to explicitly use getTimeStep() etc...

**Comment by jmichel80** [comment]
Following up on #10 we should consistently report physical quantities with their units
process.runTime()
0.5227433131833095
-->
should be
0.5227433131833095 min 
(or probably better formatted as 0.52 min)

process.getTotalEnergy()
-6359.6161
-->
should be 
-6359.6161 kcal/mol . (or kj/mol etc...)

**Comment by lohedges** [comment]
Good suggestions, this is what we plan to do. Eventually there will be more input requirement types, e.g. `BSS.Gateway.Temperature`, `BSS.Gateway.Time`, etc. These will handle units and conversions and will be the thing that you pass to the `Protocol` constructors (rather than raw python floats and ints).

With regards to `runTime`, I agree that it that it might be nice to return the units (again perhaps an object of type `BSS.Gateway.Time`.
