### ISSUE TITLE
Jupyter notebook support on OSX

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#113]
Currently when trying to use jupyter on OSX using the conda BioSimSpace will result in a Segmentation fault. Registering the sire_python kernel with jupyter will let you run BioSimSpace using a jupyter notebook also on OSX. 
This can be done in the following way:

```
/path/to/conda/miniconda3/envs/BSS/bin/sire_python -m ipykernel install --prefix=/path/to/conda/miniconda3/envs/BSS/ --name 'sire_python'
```

Then simply select the sire_python in the option for kernels in the jupyter notebook.

**Comment by lohedges** [comment]
Thanks for the workaround, I'll add this to the documentation. I'll also open another Sire issue([this](https://github.com/michellab/Sire/issues/251) one was closed) so that we can try to get this fixed. The macOS segmentation fault was introduced by one of the pull requests prior to the release of 2019.1.0. Unfortunately this wasn't triggered by our unit tests, since they are run with `sire_test` which invokes `sire_python`, for which the segmentation fault doesn't occur.

**Comment by lohedges** [comment]
@ppxasjsm FYI: I've fixed the segmentation fault issue with the macOS Python interpreter so you now no longer need to use `sire_python` as a workaround. An updated development Sire Conda package is already out.
