### ISSUE TITLE
BioSimSpace and OpenForcefieldTK interoperability

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#117]
Hi, 

I am starting a thread to discuss efficient solutions to reliably exchange information back and forth between the [OpenFFtoolkit](https://github.com/openforcefield/openforcefield) and [BioSimSpace](https://github.com/michellab/BioSimSpace) libraries. 

The purpose would be to facilitate development of code that makes use of functionality available in both toolkits. 

We ran an exploratory coding session in August 2019 at the ACS San Diego meeting, the results of which can be found [here](https://github.com/michellab/bssopenffhack)

What came out of this was that it could be desirable to add functionality in BioSimSpace to enable conversion of a BioSimSpace system into an OpenMM system, and to add functionality in OpenFFto enable conversion of an OpenMM system into a BioSimSpace system. This may well be easier and extensible than a solution that relies on writing/reading with high reliability to fileformats supported by both toolkits.  Particularly as we may want to move towards supporting functionality that is not covered by all legacy file formats (e.g. virtual sites, new functional forms for potential energy functions).

Before any significant work is undertaken it would be good to collect opinions about the best way forward. 

One immediate question I have is whether the conversion should operate at the level of a ‘system’, a ‘molecule’ or a collection of molecules. Both toolkits seem to have slightly different definition of what this means so I would be good if @lohedges , @j-wags, @ppxasjsm and @chryswoods could comment on this.

**Comment by lohedges** [comment]
Hi @jmichel80, thanks for putting this together. With regards to your question:

> One immediate question I have is whether the conversion should operate at the level of a ‘system’, a ‘molecule’ or a collection of molecules.

In BioSimSpace you can directly _upconvert_ any Sire wrapped object. This means that you can go from a `Molecule` or `Molecules` container to a `System` directly using, e.g., `molecule.toSystem()`. In this sense, it doesn't really matter what we use since we can always convert as necessary. For example, we could create a collection of BioSimSpace molecules from OpenMM ones, then add them together to create a system. However, it might make sense to convert at the smallest scale, i.e. molecule, since this would provide the greatest flexibility, i.e. you might only want to operate on a single molecule, so it seems silly to create a one molecule system then extract the molecule.

In BioSimSpace/Sire, the only additional property (at least the one we use) of a `System` is the box information in `space`. However, this could probably be inferred, e.g. computing the axis aligned bounding box, or by passing information through in other ways.

**Comment by j-wags** [comment]
_pinging @davidlmobley and @jchodera to keep them in the loop_

Sorry for the delay -- OFF is somewhat shorthanded right now and I had to help with some science work this month.

I've been thinking about this for a while, and it is probably best to talk about which information we hold in which objects. 

### OFF object overview

In terms of major classes, the OpenFF Toolkit uses OFF `ForceField`s, OFF `Molecule`s, OFF `Topology`s, and **OpenMM** `System`s. 

OFF `Molecule` and OFF `Topology` classes are defined entirely in our toolkit. 

OFF `System`s don't exist yet (but will eventually!), so for now we just use OpenMM's `System` class to hold the parameters we assign.

OFF `ForceField`s are specialized enough towards our internal use cases that it doesn't make much sense to talk about converting them. 

### OFF Molecules

An OFF `Molecule` object is a description of a molecule that contains enough information to parameterize it.

OFF `Molecule`s must include at least {`element`, `formal charge`, `is_aromatic`, and `stereochemistry` (R/S/None)} for all atoms and {`order`, `is_aromatic`, and `stereochemistry` (E/Z/None)} for bonds. They _can_ include more information, but the above is the minimum needed for parameterization. Our current `Molecule` "spec" can be found [here](https://github.com/openforcefield/openforcefield/issues/135). These are the fields we check in round-trip tests in our other existing toolkit integrations (RDKit and OpenEye).

So, one big potential difference between BSS and OFF `Molecule`s is that OFF `Molecule`s _do not_ have parameters (bond lengths, dihedral terms, vdW radii, etc) assigned. OFF `Molecule`s are a description of a molecule that _can be_ parameterized. Based on my reading of BSS docs, it seems like BSS `Molecule`s may have parameters attached earlier on. In OFFTK, the parameters don't get defined until we make an OpenMM `System`. 

It would be good to get more clarification on whether BSS `Molecule`s require parameters to be attached. If so, round-tripping may still be possible, we'd just need to figure out a scheme to stash the parameters in data dictionaries when making the OFF `Molecule`, and then unpack them on the way back to a BSS `Molecule`. 

Also, OFF `Molecule`s are a bit unusual in that they really can't exist without bond orders and formal charges (since the primary reason for them to exist is to be parameterized, we need to know bond orders and such to assign parameters). A BSS Molecule <--> OFF Molecule converter will probably need to include logic on this front, which might take some tinkering. 

### OFF Topologies

An OFF `Topology` is basically just a bunch of OFF `Molecule`s, with an additional layer that allows the `Topology`s atom indexing to be different than the original `Molecule`'s, and also optional box vectors. This seems to be analogous to BSS's `System`. 

### Figuring out which converters to make

Using the functionality in the OFFTK, it's a one-way road from OFF `Molecule` --> OFF `Topology` --> OpenMM `System`. So, the most functionality is available if the user starts with a `Molecule`. 

Given my current understanding, I'd advocate making the following converters:

1) BSS `Molecule` --> OFF `Molecule` (and maybe the other direction too)
2) OpenMM `System` -->  BSS Molecule

My logic is that most of the functionality in the OFFTK is centered around assigning parameters. So, someone making a workflow in BSS and looking to integrate OFFTK is probably looking to take a BSS `Molecule`, parameterize it using OFFTK, and bring it back to a BSS `Molecule`. Until we make a dedicated OFF `System` object, this conversion will need to use an OpenMM `System` to hold the parameters that OFFTK assigns. 

I could use your input on whether OFFMol --> BSSMol conversion would be a popular use case, knowing that OFFMols don't have parameters assigned. 

Alternatively, we could wait until the OFF `System` class is built, since that may be better exchange point between OFFTK and BSS. But with current manpower that's at least several months away, so we may not want to delay making useful converters now waiting for it.

**Comment by jmichel80** [comment]
Hi @j-wags 
Sorry for the very slow reply. Thanks for the clear and detailed post. We are now shorter on manpower than I anticipated earlier this year  and had to push back plans for OFFTK and BSS integration to get the time to complete a few other tasks.  I'm hoping to revisit this in a few months, at which stage it may make sense to exchange data directly between an OFF System class depending on how OFFTK has evolved. 

For your question on whether parameters have to be attached to molecules in BSS that's not a strict requirement because BSS Molecules wraps around Sire Molecule objects which can be very flexible in terms of what they contain (could lack coordinates etc...). This just stops you from doing certain things like computing a potential energy etc...Maybe @lohedges can chime in on possible restrictions I may have overlooked.

**Comment by lohedges** [comment]
Closing since discussion has moved to [this](https://github.com/michellab/BioSimSpace/issues/175) thread.
