### ISSUE TITLE
BioSimSpace installation error 

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/BioSimSpace#122]
Hello! I am trying to installing BSS from source using the python from Sire ~/sire.app/bin/python setup.py install. However I keep getting the warning of installation issues. The setup.err is the following: 
```
Warning: 'conda-forge' already in 'channels' list, moving to the top
Enabling notebook extension fileupload/extension...
      - Validating: ^[[32mOK^[[0m
Enabling notebook extension nglview-js-widgets/extension...
      - Validating: ^[[32mOK^[[0m
```
When I am trying to import BSS, the error that I get is this:
` ImportError: libboost_python37.so.1.68.0: cannot open shared object file: No such file or directory `
When I `locate libboost_python37.so.1.68.0`, the system cannot find it, but it can find libboost_python37.so.1.70:
```
/home/sofia/sire-vs.app/lib/libboost_python37.a
/home/sofia/sire-vs.app/lib/libboost_python37.so
/home/sofia/sire-vs.app/lib/libboost_python37.so.1
/home/sofia/sire-vs.app/lib/libboost_python37.so.1.70
/home/sofia/sire-vs.app/lib/libboost_python37.so.1.70.0
/home/sofia/sire-vs.app/pkgs/boost-1.70.0-py37h9de70de_1/lib/libboost_python37.a
/home/sofia/sire-vs.app/pkgs/boost-1.70.0-py37h9de70de_1/lib/libboost_python37.so
/home/sofia/sire-vs.app/pkgs/boost-1.70.0-py37h9de70de_1/lib/libboost_python37.so.1
/home/sofia/sire-vs.app/pkgs/boost-1.70.0-py37h9de70de_1/lib/libboost_python37.so.1.70
/home/sofia/sire-vs.app/pkgs/boost-1.70.0-py37h9de70de_1/lib/libboost_python37.so.1.70.0
```
I tried to create a symbolic link as seen [here](https://github.com/michellab/Sire/issues/253#issuecomment-470901781) and also include the path to the $LD_LIBRARY_PATH env variable, but the error remains.

**Comment by lohedges** [comment]
Hi Sofia,

You'll need to install BioSimSpace into a fresh Sire install, since the
version of liboostpython that Sire has been built again has been updated in
the last few months.

This is one of the annoying issues with a source install of BioSimSpace,
since you can't guarantee that dependencies will be compatible (even though
they should be since we're using a Miniconda). Could you try deleting your
Sire app directory and the build directory in the Site source folder, then
recompile. This problem doesn't occur with the Conda package since all
dependencies are explicitly pinned to the correct versions.

As for the warning of installation issues, you can safely ignore that
message. Annoyingly, many packages also use stderr for non error messages,
hence why I say "possible" error and leave it to the user to check.

Cheers.

**Comment by lohedges** [comment]
Hi @SofiaBariami, any progress on this? Wondering if a fresh installed fixed the problem for you? The Azure Pipeline for BioSimSpace is currently succeeding so it should work with an up-to-date Sire.

Cheers.

**Comment by lohedges** [comment]
No problem. I'm just trying to close as many dangling issues before I go on leave.
