### ISSUE TITLE
.getSystem()/trjconv issue

### ISSUE THREAD

**Issue by dlukauskis** [michellab/BioSimSpace#126]
I'm trying to use BSS to equilibrate a simple guest-host system, using own .mdp files. However, .getSystem() fails to return the last frame, giving me the following:
`''/home/dom/anaconda3/lib/python3.7/site-packages/BioSimSpace/Process/_gromacs.py:807: UserWarning: Failed to extract trajectory frame with trjconv. Try running 'getSystem' again.
  _warnings.warn("Failed to extract trajectory frame with trjconv. " `

Attaching [the folder](https://github.com/michellab/BioSimSpace/files/3733532/BSS_funnel_test.zip) with inputs and a notebook with the full error trace.

`BSS.__version__ = '2019.1.0+232.g8ce392e'`
Conda installation on Ubuntu 18.04. Gromacs-2019

**Comment by lohedges** [comment]
Thanks for reporting. It looks like your custom `mdp file for the equilibration protocol doesn't save coordinates to the `trr` file, but instead uses an `xtc` file:

```
nstxout                = 0         ; do not save coordinates to .trr
nstxout-compressed     = 50000     ; xtc compressed trajectory output every 100 ps
```

BioSimSpace uses the `trr` file by default, so fails to get the latest frame from the trajectory using `trjconv`. I'll update the code so that it searches the working directory for a `xtc` file if a `trr` doesn't exist. This will hopefully allow `getSystem` to work when there is a custom configuration file. (I believe `trjconv` should work with an `xtc` file too.)

**Comment by lohedges** [comment]
This should now be fixed. However, an updated Conda package might be a while. See [this](https://github.com/michellab/BioSimSpace/issues/127) issue for details.
