### ISSUE TITLE
[JOSS Review] Author list

### ISSUE THREAD

**Issue by amritagos** [michellab/BioSimSpace#129]
This is part of https://github.com/openjournals/joss-reviews/issues/1831.

 I notice that there are [five direct contributors](https://github.com/michellab/BioSimSpace/graphs/contributors) to the repository and four authors for the paper. [It appears that](https://github.com/michellab/BioSimSpace/commits?author=ptosco) @ptosco added some tests back in August. The question is regarding the author list then. Is there a reason to not include the fifth contributor (can't be contacted, left the project before the paper was begun, etc)?

**Comment by lohedges** [comment]
Hi @amritagos. @ptosco is not a direct member of the core BioSimSpace team (who are the authors of the paper) but works for an external industrial project partner (Cressett). You are correct that he added some tests and bug fixes over the summer. Since BioSimSpace is built on top of [Sire](https://github.com/michellab/Sire) he has also made some important indirect contributions (such as adding windows support).

I'm not sure of the JOSS policy, but should every contribution to the code (regardless of number of commits) result in authorship? I would be happy to have @ptosco as an author if needed. Pinging @jmichel80 and @chryswoods for comments/suggestions.

**Comment by amritagos** [comment]
No JOSS policy just requires that the reviewers are satisfied with the author list. Thank you for the clarifications. Since he is not a direct member and is not actively working with the project your reasoning makes sense.

**Comment by chryswoods** [comment]
Thanks - I agree with @lohedges (and we’ve discussed IRL).
