### ISSUE TITLE
[joss] example notebooks

### ISSUE THREAD

**Issue by richardjgowers** [michellab/BioSimSpace#130]
re: openjournals/joss-reviews#1831

The examples in the paper are pretty long, they could be squashed down a little by getting rid of the redundant comments, ie lines like addAuthor are self documenting.  Other lines could be grouped together with a common comment and less whitespace between

**Comment by lohedges** [comment]
I've done some squashing and made the comments a little less verbose. The first example is still a little longer, since it introduces some functionality and concepts that aren't explained elsewhere. The second example is shorter since there is no need to re-comment functionality that has been explained previously.

**Comment by lohedges** [comment]
I'll also squash the examples in the figures when I get a chance.
