### ISSUE TITLE
[JOSS Review] Minor paper changes

### ISSUE THREAD

**Issue by amritagos** [michellab/BioSimSpace#133]
Part of https://github.com/openjournals/joss-reviews/issues/1831. I do think the paper is well written, however, certain parts might be reconsidered.

- Use of the word "fantastic" (abstract)

I was also surprised to not see any mention of or discussion of relative merits of other codes which work in a sort of similar manner, in terms of unifying different tools (though BioSimSpace has many novel features). In particular, mention of [ASE](https://wiki.fysik.dtu.dk/ase/) and [MD Traj](http://mdtraj.org/development/) or [Cubby](https://onlinelibrary.wiley.com/doi/10.1002/jcc.24312/abstract) might be useful in this context.

I would expect the above revisions before further considerations and look forward to your comments on the same.

**Comment by lohedges** [comment]
Hi @amritagos, thanks for your comments and suggestions. I'll make some edits over the next few days and let you know when revisions are ready for approval.

**Comment by amritagos** [comment]
The changes are very good, however on my final read I noticed something which might be clarified a little further.

![image](https://user-images.githubusercontent.com/32496815/68948681-516da480-07b0-11ea-9f37-163dbc5dea44.png)

What guesses are made in general when it comes to reading the file formats? Perhaps this section could be expanded a little bit or it might link to further documentation?

**Comment by lohedges** [comment]
I'll have a think how it might be best to clarify this. The guesses are very specific to individual parsers and we only use them when they are reliable. For example, we can reliably infer missing element records from the atom names in a PDB file, but don't attempt to account for missing atoms, or incorrect residue names.

**Comment by chryswoods** [comment]
We don’t guess. Only information that is in the file is packed into the molecule, and thus only this information can be unpacked and written back out. This is part of what we mean by the parsers being symmetrical (same in, same out). The **only** inferred information is when reading a PDB when we follow the conventions of the field and assign chemical element information based on atom name. This is something I didn’t like adding, but is a necessary convention because of the way the field uses PDBs and overloads meaning into the atom name. Tools would simply break if we discarded this overloaded implied information.

**Comment by lohedges** [comment]
When writing I was thinking about the PDB case and also certain situations when we need to make a best guess when information in an input file is poorly formatted. For example, if atom names (or ordering) aren't consistent between a GROMACS top and crd file. This isn't really inferring missing information, so I'll remove that from the text to avoid confusion.

**Comment by amritagos** [comment]
Thanks. I am pleased with the changes and am happy to close this now.
