### ISSUE TITLE
[JOSS REVIEW] references

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#134]
I noticed that you use a very recent OpenMM reference, but quite an old GROMACS reference. Should be not be using the latest GROMACS publication, if we are using an OpenMM latest one?

**Comment by lohedges** [comment]
Hi @ppxasjsm, I don't think the date matters. For OpenMM, I have explicitly used the _primary_ publication as the citation, as requested by the developers [here](http://openmm.org/about.html). (Earlier papers don't really talk about the overall software framework, but rather discuss the use of GPU accelerated MD to do interesting things.) For GROMACS, I have also used used the main _primary_ publication, which appears to be the canonical reference.

If anyone has opinions, or better ideas, then let me know. I'm also happy to cite more than one paper in each case if it would be useful.

**Comment by lohedges** [comment]
[This](https://www.sciencedirect.com/science/article/pii/S2352711015000059?via%3Dihub) is also listed as a principal GROMACS publication and is more recent. Perhaps we could use in as well / instead.

**Comment by lohedges** [comment]
I like how the above paper contains a recursive citation, i.e. it cites itself in its own introduction! GROMACS all the way down...

**Comment by lohedges** [comment]
I've updated the reference since I agree that it is more appropriate to cite GROMACS 5, since that's what BioSimSpace has been tested against. The paper is also quite general too.

**Comment by ppxasjsm** [comment]
Yay! You came to the same conclusion as me!

**Comment by lohedges** [comment]
Ha, yes... although I needed to show all of my working and a complete solution to figure out your thought process ;-)

I think software citations are hard, since it's a living thing where developers come and go and new features are added. I wish we could just cite one thing, e.g. a Git repository, where all authors and contributions and changes are logged. Additionally, you could just refer to a specific release version (or tag or whatever) if that is what was used.

**Comment by ppxasjsm** [comment]
Yeah I agree with this. I guess that's why living journals are a nice thing too! And if from a tag or release everything was attributed correctly automatically that would just be wonderful :)
