### ISSUE TITLE
amberequilibration error

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/BioSimSpace#138]
Hello, 
I want to equilibrte a solvated small ligand, with amberequilibration.py but I am getting this TypeError: ` 'system' must be of type 'BioSimSpace._SireWrappers.System'` . I have followed the same process with other ligands as well, but didn't have any issues. I cannot understand where is the problem with this one. Any ideas? 
The files are [here](https://github.com/SofiaBariami/sharing_files/tree/master/neopentane).

**Comment by lohedges** [comment]
The problem is that the `amberequlibration.py` script has no error checks for failing processes. It looks like the minimisation fails, so the `process.getSystem()` call returns a `NoneType` object.  This is then passed as the system argument to the equilibration process, hence the error. The code should really check that `process.isError() == False` at each stage to make sure that it completes correctly. (We can't just throw an error if `process.getSystem()` returns nothing since the user might be running things interactively, in which case the log file might not yet have been written.)

Also, the `amberequlibration` script and notebook need to be updated to remove the outdated `ensemble` keyword argument from the equilibration protocol. Simulations are run in the NVT ensemble by default. If you pass a `pressure` option then NPT is used instead.

**Comment by SofiaBariami** [comment]
Thanks Lester! 
Yes, I also noticed that about the ensemble keyword and I deleted it. 
The issue was solved after running a short minimisation/ equilibration with SOMD.
