### ISSUE TITLE
running FreeEnergy.Solvation() without simulating vacuum leg

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#145]
Hi all,

I have a use case where I need to compute a large (> 10.000) number of solvation free energy calculations using SOMD/BSS. For my workflow I do not need the vacuum leg to be computed but in the current BSS API I can not disable this. Would it be possible to implement a way for disabling the vacuum simulations? An example of this would be by passing a parameter vacuum_leg=False to FreeEnergy.Solvation().

I have considered bruteforce deletion of the vacuum folder like this:
```
freenrg_somd = BSS.FreeEnergy.Solvation(..)
shutil.rmtree(work_dir+"/vacuum/)
freenrg_somd.run()
```
Which seems to work but this might create problems downstream.

**Comment by lohedges** [comment]
Hi @JenkeScheen. Your suggested modification would be very easy for me to add. Is this a general workflow that many other users would benefit from too? At present this would break the analysis stage since this assumes reference to a vacuum PMF. In your case would this just be zero, or do you have a known value that you are computing the free energy in respect to?

The `FreeEnergy.run` method is just a dumb wrapper around BioSImSpace's rather basic `ProcessRunner` class for handing multi-stage simulations, such as an alchemical free-energy calculation. This just runs each process sequentially. For a `FreeEnergy.Solvation` object, the `ProcessRunner` is first populated with processes for each lambda window of the free leg, followed by the processes for the vacuum leg. This means you could manually run only the first half of the processes in the runner to get the same effect.

Something like the following _should_ work (untested):

```python
# Get the process runner from the FreeEnergy object. This is private since the user
# normally doesn't need to access it.
runner = freenrg_somd._runner

# Work out half the total number of processes. Since there are the same number
# of lambda values in each leg we can just divide by two and get a whole number.
num_proc = len(runner.processes()) / 2

# Run the first half of the processes.
for process in runner.processes()[0:num_proc]:
    # Start the process in the background and wait for it to finish.
    process.start()
    process.wait()

**Comment by JenkeScheen** [comment]
> Is this a general workflow that many other users would benefit from too? 

I think it would be very helpful for users to have the ability to run any vertical leg of the thermodynamic cycle. Running a single leg can help in understanding whether the setup protocol is suitable and potentially be a simplified topic in tutorials.

> In your case would this just be zero, or do you have a known value that you are computing the free energy in respect to?

We are computing a large number of hydration free energies to analyse their (standard) error, so no vacuum energy or an energy of 0 would be perfect. 


I'll take a shot at it with your snippet, thanks!

**Comment by lohedges** [comment]
I've implemented the change that you suggested. You can now pass `vacuum_leg=False` to the `FreeEnergy.Solvation` constructor. Similarly, you can pass `free_leg=False` to the `FreeEnergy.Binding` constructor.

When running any analysis through BioSimSpace you can catch the redundant PMF in a dummy variable. This is to avoid breaking the existing API. For example:

```python
# Here _ represents a dummy return variable that we don't care about.
pmf_free, _, delta_delta_g = freenrg.analyse()
```

Let me know if you run into any issues.
