### ISSUE TITLE
BSS fails to read charmm files

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/BioSimSpace#150]
Hello, I'm trying to read a psf and a pdb file with `BSS.IO.readMolecules()` but it fails with this error: 
```
OSError: Failed to read molecules from: ['file.psf', 'file.pdb']
```
The files contain more than one molecules. Can this be an issue? Or should I set `property_map`? If so, will the path point to a topology folder like the one for GROMACS? Thanks a lot!

**Comment by ppxasjsm** [comment]
Can you share the files and how you read them in?

**Comment by lohedges** [comment]
Hi @SofiaBariami. This could be because you failed to pass in a CHARMM parameter file, e.g.

```python
import BioSimSpace as BSS
system = BSS.IO.readMolecules(["namd/alanin/alanin.pdb", "namd/alanin/alanin.psf", "namd/alanin/alanin.params"])
```

(This assumes you are in the `demo` directory of the BioSimSpace repository.)

However, the PDB and PSF should be enough to construct the molecular system.

Remember you can see the full Sire error trace by doing:

```python
import BioSimSpace as BSS
BSS.setVerbose(True)
system = BSS.IO.readMolecules(["file.psf", "file.pdb"])
```

Although BioSimSpace/Sire can read CHARMM files we current don't support all of the terms (e.g. CMAP) or potential formats.

As @ppxasjsm says, files would be useful for debugging.

**Comment by lohedges** [comment]
Closing as no update.
