### ISSUE TITLE
Compatibility with newer dependencies

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#159]
Hi @lohedges 

Have you tested recently BioSimSpace with AmberTools 20 or Gromacs 2020.* releases ? I wonder if the documentation here can be updated

https://biosimspace.org/compatibility.html#ref-compatibility

**Comment by lohedges** [comment]
Hi Julien. I actually can't build AmberTools 20 since they haven't updated the fortran code to work with more recent versions of GCC. (Things that were previously warnings are now errors and there are various linker errors too.) I've also not managed to compile the most recent GROMACS either. I'll certainly update the compatibility list when I'm actually able to test.

**Comment by lohedges** [comment]
The website has now been updated. I'll close for now but it would be good to come up for a strategy for periodically running tests against new versions of our dependencies.
