### ISSUE TITLE
atom-mapping mismatch between LOMAP/rdkit and BSS.Align.rmsdAlign()

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#162]
Hi,

I have a use-case where I'm building a SOMD freenrg environment in the standard BSS way, except that I need to use LOMAP to come up with the atom mapping. Although this is fairly straightforward, the output mapping dict doesn't correspond to the atom mapping by BSS:
```
BSS:
{28: 33, 16: 21, 17: 22, 18: 23, 19: 24, 20: 25, 21: 26, 22: 27, 23: 28, 8: 13, 9: 14, 10: 15, 11: 16, 12: 17, 13: 18, 14: 19, 15: 20, 0: 4, 1: 5, 2: 6, 3: 8, 4: 9, 5: 10, 6: 11, 7: 12, 56: 60, 57: 61, 58: 62, 59: 63, 48: 52, 49: 53, 50: 54, 51: 55, 52: 56, 53: 57, 54: 58, 55: 59, 41: 45, 42: 46, 43: 47, 44: 48, 45: 49, 46: 50, 47: 51, 35: 42, 36: 43, 24: 29, 25: 30, 26: 31, 27: 32}
LOMAP:
{0: 4, 1: 5, 2: 6, 3: 8, 4: 9, 5: 10, 6: 11, 7: 12, 8: 13, 27: 32, 28: 33, 26: 31, 17: 22, 16: 21, 9: 14, 10: 15, 15: 16, 14: 17, 13: 18, 12: 19, 11: 20, 18: 23, 19: 24, 20: 25, 25: 30, 21: 26, 22: 27, 23: 28, 24: 29}
```
which presumably is caused by some differences between the way the rdkit and BSS molecule objects are built. As far as I can see there would be two solutions:
- correct the LOMAP mapping to match up with how BSS has built the molecule
- convert the rdkit molecule object into a BSS molecule object while preserving the atom numbering

would either of these be possible with the currently exposed code? 
As a sanity check, here is the BSS mapping:
![image](https://user-images.githubusercontent.com/43140137/98121896-d06b5980-1ea7-11eb-9977-b1837dcfe3a6.png)

and here is the LOMAP mapping:
![image](https://user-images.githubusercontent.com/43140137/98121939-dc571b80-1ea7-11eb-9b50-434264382978.png)
of which the latter (as far as I understand) the used atom indices (i.e. suggested by LOMAP) will be wrong because ligA and ligB are BSS mol objects, instead of rdkit mol objects that the mapping is based on.

input ligands:
[mapping_ligs.tar.gz](https://github.com/michellab/BioSimSpace/files/5488274/mapping_ligs.tar.gz)

**Comment by lohedges** [comment]
We actually use RDKit to generate our MCS mappings and only use Sire as a fallback. (RDKit's MCS algorithm is, in general, faster and more reliable.) We transfer molecular information into RDKit via a PDB representation of the molecule, using [Chem.MolFromPDBFile](http://rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.MolFromPDBFile). (See [here](https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/Align/_align.py#L228) for the BioSimSpace code.) To date I haven't experienced any issues with atom re-ordering, so the MCS returned by RDKit matches the topology (and atom indexing) of the original BioSimSpace system. (If this isn't always the case, then I'll need to figure out a fix.)

One thing to note is that the BioSimSpace mapping matches 50 atoms, whereas the one from LOMAP only contains 29. In this case should the 29 atom match be a substructure of the 50 atom one, i.e. is it obvious that the mapping should contain the same atom pairs?

Do you know how LOMAP generates the mapping? Is there code I could look at to see how the indices are mapped?

**Comment by JenkeScheen** [comment]
Hi Lester, you can find the version of LOMAP mcs I'm currently using [here](https://github.com/JenkeScheen/cresset_work/blob/master/eg5_doa/lomap_mcs.py). The code is a bit elaborate but it seems the main mapping happens in MCS.map_mcs_mol().. do you recognise anything? if it isn't very clear to you either I can have a chat with Mark. 

> One thing to note is that the BioSimSpace mapping matches 50 atoms, whereas..

Here are the actual structures:
![image](https://user-images.githubusercontent.com/43140137/98129606-390b0400-1eb1-11eb-975f-59b5a0044207.png)
I would assume the 29 vs 50 is due to LOMAP matching only the MCS atoms (or only non-MCS? again, perhaps it's more efficient if I ask Mark)

**Comment by lohedges** [comment]
Hi again,

I've run the script you posted, modifying the example input files in the `if "__main__" == __name__:` section, i.e. using:

```python
if "__main__" == __name__:
    ...
    mola = Chem.MolFromMol2File('ligA.mol2', sanitize=False, removeHs=False)
    molb = Chem.MolFromMol2File('ligB.mol2', sanitize=False, removeHs=False)
```

Note that two mappings are generated: one that only includes heavy atoms, and one that includes all atoms. In BioSimSpace we only map all atoms, i.e. including hydrogens. (We used to support both options, but this is tricky when using Sire as a fallback.)

Next I loaded the LOMAP mapping into a Python dictionary and compared with the mapping from BioSimSpace:

```python
import BioSimSpace as BSS

# Load the ligands.
ligA = BSS.IO.readMolecules("ligA.mol2")[0]
ligB = BSS.IO.readMolecules("ligB.mol2")[0]

# Generate the MCS mapping with BioSimSpace.
bss_mapping = BSS.Align.matchAtoms(ligA, ligB)

# Assign the MCS mapping from LOMAP.
lomap_mapping = {0:4,1:5,2:6,3:8,4:9,5:10,6:11,7:12,8:13,9:14,
                 10:15,11:20,12:19,13:18,14:17,15:16,16:21,17:22,18:23,
                 19:24,20:25,21:26,22:27,23:28,24:29,25:30,26:31,27:32,
                 28:33,29:44,35:3,36:43,39:7,41:45,42:46,43:47,44:48,45:49,
                 46:50,47:51,48:52,49:53,50:58,51:57,52:56,53:55,
                 54:54,55:59,56:60,57:61,58:62,59:63,65:42
}

# Print the lengths of the mappings.
print(f"BSS = {len(bss_mapping)}, LOMAP = {len(lomap_mapping)}")
BSS = 50, LOMAP = 53

# Print the BSS mappings that don't match those from LOMAP.
for key, value in bss_mapping.items():
    if value != lomap_dict[key]:
        print(f"key = {key}, BSS = {value}, LOMAP = {lomap_mapping[key]}")

key = 35, BSS = 42, LOMAP = 3
key = 53, BSS = 57, LOMAP = 55
key = 54, BSS = 58, LOMAP = 54
key = 50, BSS = 54, LOMAP = 58
key = 51, BSS = 55, LOMAP = 57
key = 12, BSS = 17, LOMAP = 19
key = 14, BSS = 19, LOMAP = 17
key = 15, BSS = 20, LOMAP = 16
key = 11, BSS = 16, LOMAP = 20

# Print the extra matches that only exist in the LOMAP mapping.
for key in lomap_mapping.keys():
    if key not in bss_mapping:
        print(f"{key} <===> {lomap_mapping[key]}")

29 <===> 44
39 <===> 7
65 <===> 42
```

It looks like the indices the same for both approaches, only LOMAP is generating a larger mapping with a substructure that contains a few (9) different matches. I've not visualised the mappings, so let me know if you think anything is wrong.

**Comment by lohedges** [comment]
Note that the default BioSimSpace scoring function is also slightly different in that in does rigid translation / rotation alignment before performing the RMSD score. It looks like the LOMAP one only translates, so you might get slightly different _best_ mappings because of differences in the scoring.

**Comment by JenkeScheen** [comment]
great, thanks for digging into this! Would you suggest going forward with simply calling MCS.map_mcs_mol() and work with the heavy-atom mapping, or to use the all-atom LOMAP mapping? (I'm not sure how you got to that one)

**Comment by lohedges** [comment]
I just ran the script directly, e.g. `python lomap_mcs.py` (after doing the edits) rather than loading it as a module and using the functions. In the `__main__` section at the bottom you can see how they call the MCS routine once, then extract only the heavy atom matches from the mapping. Typically the user will want to use the all atom mapping, but it can generate spurious results. (@jmichel80 will probably be able to be able to comment on this more accurately.)

Interestingly, `MCS.map_mcs_mol` isn't called anywhere in the `__main__` section, so I'm not sure if it's necessary.

Given that this LOMAP script is pure Python and uses RDKit for all of the MCS grunt work, there should be no reason that we could match it exactly with BioSimSpace. I simply followed the approach used by FESetup.

**Comment by lohedges** [comment]
Looking at the options passed to `rdkit.Chem.rdFMCS`, it appears that LOMAP uses exactly the same as settings as us (and in turn, FESetup). As such, I'm surprised that we are getting different mappings in this case. Specifically, I'm not sure why LOMAP returns a mapping with a larger number of atoms. I could understand differences in the actual mapping, or a mapping with a lower number of atoms, since LOMAP imposes a sequence of rules which could trim the resulting MCS.

I'll investigate further since it would be good to understand the origin of the discrepancy.

**Comment by lohedges** [comment]
Ah, I believe that it's related to [this](https://github.com/michellab/BioSimSpace/issues/124) issue, i.e. LOMAP is sanitizing the molecular input, resulting in slightly different mappings. (It also mentions a change to the `completeRingsOnly` option, but this looks the same in the version of LOMAP that you linked to.)

It would be good to find a way to support sanitization, but it's not obvious if we still rely on Sire as a fallback. I guess we could warn the user that options are being ignored if we do fall through to Sire. In most cases it would be okay to get some kind of match, rather than nothing, and it's always up to the user to validate it anyway.

**Comment by lohedges** [comment]
I've now added support for molecular sanitzation, so you can get _almost_ the same mapping with BioSimSpace using:

```python
bss_mapping = BSS.Align.matchAtoms(ligA, ligB, sanitize=True)
```

This gives a mapping of 52 matches, rather than the 50 we were getting before. Using the same code as above we can work out the additional match from LOMAP.

```python
# Print the extra matches that only exist in the LOMAP mapping.
for key in lomap_mapping.keys():
    if key not in bss_mapping:
        print(f"{key} <===> {lomap_mapping[key]}")

29 <===> 44
```

I think the reason for this difference is that LOMAP uses the heavy atom MCS to perform its additonal scoring functions and trims, then reconstructs the full MCS by adding various atoms that are bonded to the heavy atom part. I think that something must be going wrong in their algorithm, or that they are choosing to include additional atoms for some reason.

In any case, other than the additional scoring metrics, we can now support a near identical MCS routine as LOMAP within BioSimSpace.

**Comment by lohedges** [comment]
Closing for now since I think we understand the differences between the BioSImSpace and LOMAP mappings, and have provided means for matching the LOMAP options within BioSimSpace. Feel free to re-open (or open a new issue) if you come across further examples where there are discrepancies between the mappings.

Cheers.
