### ISSUE TITLE
BSS compile from source fails on jupyter

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#166]
It seems the newest devel installation of sire does not include `sire.app/bin/jupyter-nbextension` which breaks the current BSS compile. 

Tail of compilation prints:
```
copying BioSimSpace.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying BioSimSpace.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/BioSimSpace-2020.1.0+88.ga209eb1-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing BioSimSpace-2020.1.0+88.ga209eb1-py3.7.egg
Removing /home/jscheen/sire.app/lib/python3.7/site-packages/BioSimSpace-2020.1.0+88.ga209eb1-py3.7.egg
Copying BioSimSpace-2020.1.0+88.ga209eb1-py3.7.egg to /home/jscheen/sire.app/lib/python3.7/site-packages
Removing BioSimSpace 2020.1.0+88.ga209eb1.dirty from easy-install.pth file
Adding BioSimSpace 2020.1.0+88.ga209eb1 to easy-install.pth file

Installed /home/jscheen/sire.app/lib/python3.7/site-packages/BioSimSpace-2020.1.0+88.ga209eb1-py3.7.egg
Processing dependencies for BioSimSpace==2020.1.0+88.ga209eb1
Finished processing dependencies for BioSimSpace==2020.1.0+88.ga209eb1

Setting up python environment...
Adding conda-forge channel
Disabling conda auto update
Installing conda dependencies: configargparse, mdanalysis, mdtraj, nglview, pygtail, pymbar, pypdb, pytest, pyyaml, rdkit, watchdog
Activating notebook extension: nglview
Cleaning conda environment

Possible installation issues. Please check output in 'setup.out' and 'setup.err'
```
setup.err:
```
Warning: 'conda-forge' already in 'channels' list, moving to the top
/bin/sh: 1: /home/jscheen/sire.app/bin/jupyter-nbextension: not found
/bin/sh: 1: /home/jscheen/sire.app/bin/jupyter-nbextension: not found
```
could there be a mismatch with the current versions or did I miss something in the installation documentations? Compiling sire looked OK - let me know if you think I should post this as a sire issue instead though.

**Comment by JenkeScheen** [comment]
simply patch installing nbextensions into sire by running `..sire.app/bin/conda install -c conda-forge jupyter_contrib_nbextensions` resolved this issue.

**Comment by lohedges** [comment]
Thanks for reporting. Jupyter is dependency of BioSimSpace dependency, not Sire. It's implicitly installed via `nglview` since all Jupyter widgets pull in Jupyter as a dependency. We're not seeing any issues in our [build pipeline](https://dev.azure.com/michellab/BioSimSpace/_build) for Linux or macOS, which runs the same install that you are doing, as well as building the BioSimSpace conda package and testing that it installs properly. (The latest build was yesterday.)

I imagine that there was a network issue during your installation meaning that the Jupyter package wasn't installed correctly. Sometimes this can result in a corrupted package on disk, which means that it won't be installed even if you try to re-run, i.e. it will try to use the broken cached package. Conda isn't very good at reporting errors, so the failure might have also been silent. It also outputs what I would consider to be error information to a mixture of stdout and stderr, hence me redirecting to both files. It's possible that there was some helpful info in `setup.out` that you missed.

As a sanity check I'll test things locally and will let you know if I run into the same issue.

**Comment by JenkeScheen** [comment]
ah! Yes that's a possibility. I remember conda momentarily complaining about a 404 when trying to reach omnia too so those could be related in that case.
