### ISSUE TITLE
Parameterizing protein throws error even when tleap doesn't. 

### ISSUE THREAD

**Issue by OleinikovasV** [michellab/BioSimSpace#169]
I am using IO.readPDB with a PDB that has been through pdb4amber with options '--nohyd -a -p' to strip away all but protein (Ideally, I would do that with 'pdb4amber=True' directly inside BSS, but I cannot pass the choices).

```
import BioSimSpace as BSS
# Parameterize the protein.
receptor_pdb = BSS.IO.readPDB(f'{pdb1.stem}_p4a.pdb')[0]
receptor = BSS.Parameters.ff99SBildn(receptor_pdb, work_dir='./tmp').getMolecule()
```
I get this traceback:
```
---------------------------------------------------------------------------
ParameterisationError                     Traceback (most recent call last)
<ipython-input-54-17880d7c1d87> in <module>
      3 print(BSS.__version__)
      4 receptor_pdb = BSS.IO.readPDB(f'{pdb1.stem}_p4a.pdb')[0]
----> 5 receptor = BSS.Parameters.ff99SBildn(receptor_pdb, work_dir='./tmp').getMolecule()

~/miniconda3/envs/bss/lib/python3.7/site-packages/BioSimSpace/Parameters/_process.py in getMolecule(self)
    212         # If there was an problem, return the last error.
    213         if self._is_error:
--> 214             raise _ParameterisationError("Parameterisation failed! Last error: '%s'" % str(self._last_error)) from None
    215 
    216         return self._new_molecule

ParameterisationError: Parameterisation failed! Last error: 'Failed to read molecule from: './tmp/leap.top', './tmp/leap.crd''
```
For some reason _is_error is set True even if tleap.err is empty. I looked at tleap.out and looks rather normal:
> ...
> /home/model/MD-SOFTWARE/amber18-gnu-cu10/bin/teLeap: Warning!
> The unperturbed charge of the unit (7.000000) is not zero.
> 
> /home/model/MD-SOFTWARE/amber18-gnu-cu10/bin/teLeap: Note.
> Ignoring the warning from Unit Checking.
> 
> Building topology.
> Building atom parameters.
> Building bond parameters.
> Building angle parameters.
> Building proper torsion parameters.
> Building improper torsion parameters.
>  total 1549 improper torsions applied
> Building H-Bond parameters.
> Incorporating Non-Bonded adjustments.
> Not Marking per-residue atom chain types.
> Marking per-residue atom chain types.
>   (Residues lacking connect0/connect1 - 
>    these don't have chain types marked:
> 
> 	res	total affected
> 
> 	CGLU	1
> 	CLEU	1
> 	NGLY	1
> 	NSER	1
>   )
>  (no restraints)
> 	Quit
> 
> Exiting LEaP: Errors = 0; Warnings = 1; Notes = 1.

I checked, it produces clean PDB, and the produced leap.top and leap.crd can be loaded by parmed without any issues.
But could not be loaded by BSS for some reason.

Attaching the zipped work_dir.
[tmp.zip](https://github.com/michellab/BioSimSpace/files/5644312/tmp.zip)

BSS version 2020.1.0+58.g817f66f

**Comment by lohedges** [comment]
Hi there,

Thanks for posting! As you say, there is no `tLEaP` error in the output, just that BioSimSpace is unable to load the topology file that it produced. To dig deeper we can load the file directly with the underlying `AmberPrm` parser from Sire (which is what BioSimSpace is using behind the scenes).

```python
from Sire.IO import AmberPrm

amber_prm = AmberPrm("leap.top")
```

This throws the following exception:

```
Exception 'SireIO::parse_error' thrown by the thread 'master'.
Disagreement over the number of atoms in molecule 1. Looking at bonding implies the number of atoms is 7874, while the file itself claims the number is 3929.
Thrown from FILE: /home/lester/Code/Sire/corelib/src/libs/SireIO/amberprm.cpp, LINE: 679, FUNCTION: void SireIO::AmberPrm::rebuildMolNumToAtomNums()
```

It looks like the `ATOMS_PER_MOLECULE` flag in the top file is inconsistent with the topology of the PDB, i.e.:

```
%FLAG ATOMS_PER_MOLECULE
%FORMAT(10I8)
    3929
```

For some reason this flag is referring to the number of atoms in the _original_ PDB (the one without hydrogens), rather than the number after `tLEaP` has _fixed_ things, which should be 7874. If you change the number, then Sire/BioSimSpace can read it just fine. (Seems like a `tLEaP` bug to me...)


However, even having fixed this you would still run into issues when using BioSimSpace, since we are assuming that the original PDB is the reference system and what is returned from other tools must be "made compatible" with this. (In our meeting we discussed how BioSimSpace expects sane input and we've generally taken the approach that it's the responsibility of the user to prepare things before using BioSimSpace, since we can't guess their intentions with 100% accuracy all of the time.)

Since there is an atom number mismatch, the `makeCompatibleWith` step, which is performed when the parameterised molecule is returned, would fail. If we need to handle parameterisation of incomplete systems then we will need to update the logic in `makeCompatibleWith`, which might be tricky to do in general. For example, we could try to keep the common substructure compatible, then copy over new atoms. However, I'm not sure of all the possible things that `tLEaP` might do. If it's not possible, and we have not use `makeCompatibleWith` in instances where the PDB has been stripped, then you will lose the ability to reference, atoms etc. by the original PDB chain identifiers throughout a workflow.

> Ideally, I would do that with 'pdb4amber=True' directly inside BSS, but I cannot pass the choices.

Yes, I agree that it would be good to support some additional options. I just went with what Antonija said, which was that the defaults work fine in most cases. I don't want to support all options, since many are experimental, so let me know a subset that would be helpful.

I'll update next week when I've had a chance to think about things further.

(Is there a reason why you're not using the latest development build? The latest is 2020.1.0+92.)

Cheers.

**Comment by OleinikovasV** [comment]
> Yes, I agree that it would be good to support some additional options. I just went with what Antonija said, which was that the defaults work fine in most cases. I don't want to support all options, since many are experimental, so let me know a subset that would be helpful.

We could add an "advanced-user" kwarg to pass a string of pdb4amber choices. This could be a separate variable, **pdb4amber_flags**, or could allow **pdb4amber** variable to accept non-Boolean input, which would be passed to append the command whenever it is of a string type.

**Comment by lohedges** [comment]
Yes, something like that would work. Although we are then entering into the realm of supporting experimental behaviour and issues with downstream BioSimSpace functionality, as we are seeing here. I would personally prefer that we only support a limited set of common options then work out a way of extending `makeCompatibleWith`. If that's not possible, then I'd rather return to the idea that the user prepares the system outside of BioSimSpace so that we start from a valid initial system.

**Comment by lohedges** [comment]
Closing as this issue has now been fixed.
