### ISSUE TITLE
Incorrect PDB format in the output using BSS.IO.saveMolecules

### ISSUE THREAD

**Issue by mieczyslaw** [michellab/BioSimSpace#170]
# Expected Behavior
Outputs follow PDB format when residue name is two letters long.

# Current Behavior
With residue name like "ZN", all further columns are moved to the left, so coordinates etc. are messed up. See the attached screenshot.

![BSS_ZN_incorrect_columns](https://user-images.githubusercontent.com/3063282/102078276-907e8700-3e02-11eb-868b-aef676bc6bd3.png)

## Steps to Reproduce
Run the minimization with Amber and output the minimized file:
```
process = BSS.Process.Amber(complex_BSS, protocol, work_dir="work_dir")
process.start()
process.wait()
BSS.IO.saveMolecules("minimised.pdb",  process.getSystem(), "PDB")
```

## Context
prmtop/rst7 files are prepared outside BSS because it currently doesn't support ZN ion when parametrized inside BSS. They are read in inside BSS and the system is minimized. @lohedges knows more about the context.

* Operating System: Linux.
* Installation method: conda, sire (sire                      2020.1.0        py37hf484d3e_71    michellab/label/dev), bss (biosimspace               2020.1.0        py37h14c3975_92    michellab/label/dev)
* If you're running on a cluster: No, local run.
* What molecular system are you simulating? protein-protein complex with PROTAC

**Comment by lohedges** [comment]
I've update the Sire PDB parser so that residue names are fixed width, which avoids issues when they are less than three characters in length. You'll need to wait for the Sire CI to finish, then updated Sire in your conda environment. We have recently paused our cloud server, so it's possible that a new build won't be available until the New Year, in which case you'd need to build Sire from source.

Cheers.
