### ISSUE TITLE
Adding an option to source additional parameters from local files when parameterising

### ISSUE THREAD

**Issue by AdeleLip** [michellab/BioSimSpace#182]
The system I'm currently working with has some non-standard residues, with published parameters. When using leap directly I have been simply adding the file path and sourcing the additional parameters, but that is not option in BSS as far as I can see.

My (rather inelegant) solution that has worked so far was to add an argument to `Parameters._parameters.ff14SB()` that carries over down to `Parameters.Protocol._protocol._run_tleap()` where if it is not None, addPath and source lines are added to the input leap file.

I think it would be a good idea to allow the user to source already existing additional libraries in these scenarios.

**Comment by lohedges** [comment]
Yes, this is a good idea and should be easy to add. Your approach works fine, although it might be more flexible to allow the user to pass an optional list of configuration strings that are written to the `tLEaP` input file, although this would also need to be passed down to the protocol. (This might allow us to support other things too.)

If you can share some example inputs then I can play around to see what works best.

Cheers.

**Comment by AdeleLip** [comment]
[here](https://github.com/michellab/BioSimSpace/files/5893589/leap_example.zip) is the peptide and the parameters it needs, as well as an example leap input I used for it (will need adjusting). I agree that pasing a list of configuration strings would allow to do even more! (maybe something like the very visible config for processes - I have adjusted the Amber process config list to integrate plumed and it worked great)

**Comment by lohedges** [comment]
Thanks, that's great. I should be able to take a look this afternoon.

I agree that it would be good to support more configuration options. The problem comes with making things simple for most users, while still supporting more advanced use cases. It's always a case of striking a balance. Parameterisation is also a little tricky since, for certain force fields, we can parameterise using multiple tools. For example, for most AMBER force fields we use `tLEaP` as the default, but fall back on `pdb2gmx` if it's not installed. Here we should be able to support additional `tLEaP` options if the user calls an appropriate force field function directly, e.g. `BSS.Paramters.ff14SB`. If these options are set, then we would no longer support `pdb2gmx` as a fallback.

It's good to know that it was easy to get PLUMED working with AMBER. There is no reason why we can't support PLUMED/AMBER integration natively and it's on my to do list. As a first pass we got our metadynamics implementation working with GROMACS but haven't yet extended it to other MD engines.

**Comment by lohedges** [comment]
Hi again,

I added functionality so that the user can pass a list of optional `LEaP` commands to any AMBER force field function that will support them. (This then disables using `pdb2gmx`.) In your example, you could do something like:

```python
import BioSimSpace as BSS

# Load the peptide molecule.
peptide = BSS.IO.readMolecules("peptide.pdb")[0]

# Create a list of optional LEaP commands.
leap_commands = ["addPath /path/to//phosphate-params",
                 "source leaprc.phosaa10"]

# Parameterise the molecule.
peptide = BSS.Parameters.ff14SB(peptide, leap_commands=leap_commands).getMolecule()
```

Note that we don't currently support `ff19SB`, since the `Sire.IO.AmberPrm` parser doesn't yet have support for `CMAP` records. Also, if I switch to using `ff14SB`, although the parameterisation works BioSimSpace fails when making the loaded system compatible with the original PDB topology, i.e. the original molecule has 95 atoms, whereas the one following parameterisation has 170. I tried pre-processing the PDB with `pdb4amber`, e.g.:

```
peptide = BSS.IO.readPDB("peptide.pdb", pdb4amber=True)[0]
```

but the resulting molecule still has 95 atoms.

The Azure CI build pipeline is currently running and a new conda package will be available in an hour or so. Let me know how you get on, or if you have any more questions / suggestions.

**Comment by lohedges** [comment]
Having thought about this a little more I've moved the addition of any user commands to _after_ all off the base commands used to set up the parameterisation, i.e. everything other than the `saveAmberParm ...` step. I assume that and custom files loaded by the user could be intended to override certain parameters from the force field files, so it would be necessary to load them second.

**Comment by lohedges** [comment]
Closing as feature is implemented. Can re-open if further additions / discussion is needed.
