### ISSUE TITLE
string passing issues on import

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#186]
Seen this kind of error before?

```
Traceback (most recent call last):
  File "/home/floeuser/miniconda/envs/user_env/lib/python3.7/site-packages/floe/detect.py", line 177, in detect_py_source
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/package/bss-test-0.1.0/bss_test/mycube.py", line 21, in <module>
    import BioSimSpace as BSS
  File "/home/floeuser/miniconda/envs/user_env/lib/python3.7/site-packages/BioSimSpace/__init__.py", line 183, in <module>
    from . import Gateway
  File "/home/floeuser/miniconda/envs/user_env/lib/python3.7/site-packages/BioSimSpace/Gateway/__init__.py", line 60, in <module>
    ResourceManager = ResourceManager()
  File "/home/floeuser/miniconda/envs/user_env/lib/python3.7/site-packages/BioSimSpace/Gateway/_resources.py", line 46, in __init__
    add_help=False, allow_abbrev=False)
  File "/home/floeuser/miniconda/envs/user_env/lib/python3.7/argparse.py", line 1641, in __init__
    prog = _os.path.basename(_sys.argv[0])
  File "/home/floeuser/miniconda/envs/user_env/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list

```

**Comment by lohedges** [comment]
No, I've not seen this before. Since the latest development binary and conda package don't have this problem I can only assume that you are running an outdated version of BioSimSpace, or your conda environment is borked?

Do you have any more context, otherwise I'm not sure how I can help? What is the OS, installation method, BioSimSpace version?

I'm _guessing_ that this could be a result of your attempts to get BioSimSpace to install alongside orion and the resulting mismatch in the `attrs` package. If so, does this issue occur before/after upgrading/downgrading `attrs` to attempt to match versions between the packages? (It might be possible that both packages _do_ require the versions that they state, and if so you're out of luck.)

Could you possibly create an env file for your conda environment, then upload it as a text file? (Pasting would be too large.) That way I could compare to a vanilla conda install to see what the difference is, or try to reproduce the issue locally.

```sh
conda env export -n ENV_NAME > biosimspace-env.txt
```

(Here `ENV_NAME` is the actual name of your conda environment, which looks like `user_env`.)

The fact that it's being triggered by `BioSimSpace.Gateway.ResourceManager` suggests it's an issue with `argparse`. This isn't currently used, but gives the user the ability to pass information such as the number of nodes, cpus, and gpus to a script (node), regardless of the other options that have been set, e.g.:

```python
import BioSimSpace as BSS

print(BSS.Gateway.ResourceManager.getCPUs())
```

```sh
python test.py --cpus 10
10
```

Another test could be to edit `/home/floeuser/miniconda/envs/user_env/lib/python3.7/site-packages/BioSimSpace/Gateway/_resources.py` and replace:

```python
import argparse as _argparse
```

with

```python
import configargparse as _argparse
```

(`configargparse` is a full replacement for `argparse` that also supports config files and environment variables. I use this for the command-line parsing in `BioSimSpace.Gateway._node.py`)

I'm on toddler duty this morning but could take a look this afternoon.

**Comment by ppxasjsm** [comment]
This is what happens when I install attrs==18.2.0 with this set requirement after installing biosimpsace via conda. I'll see if I can get the state of the environment out. It should be pulling the latest release from conda in theory, unless there is some kind of versioning/pinning.

**Comment by ppxasjsm** [comment]
I see. I just checked I think I end up with BSS 19.03....probably due to some dependencies pinning.

**Comment by lohedges** [comment]
Add --all to your conda install command to make sure you get the latest
versions of all packages that are compatible.
