### ISSUE TITLE
atom mapping mismatch on pyridine

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#197]
We've been running a large series of FEPs between FreeSolv molecules (so quite small), and looking at the data I've found some edge-cases that have high variance. An example is this perturbation:
![image](https://user-images.githubusercontent.com/43140137/112505164-6daa2a00-8d84-11eb-9d30-aa33d2d1b6fb.png)

where ligands are read by `BSS.IO.readPDB()[0]`, then atoms are matched with `BSS.Align.matchAtoms(mol1, mol2)`. The mapping is used to direct the align/merge further downstream, but the FE predictions of this pert in solvation have a standard error of ~40 kcal/mol.. The mapping looks like this:
![image](https://user-images.githubusercontent.com/43140137/112505530-c679c280-8d84-11eb-8ee9-d9e23adab87e.png)
with indices:
![image](https://user-images.githubusercontent.com/43140137/112505545-cc6fa380-8d84-11eb-833c-7b3433e07183.png)
where clearly something is off (idx 0 atoms have no label, so 0 is the methyl carbon for mol1, e.g.):
![image](https://user-images.githubusercontent.com/43140137/112505590-d396b180-8d84-11eb-981e-d8b72a9ede9a.png)
(note, e.g. 13:7)

Forcing 0:1 mapping by `BSS.Align.matchAtoms(mol1, mol2, prematch={0 : 1})` gives a more realistic mapping:
![image](https://user-images.githubusercontent.com/43140137/112505975-37b97580-8d85-11eb-9178-3e131e4eb537.png)
![image](https://user-images.githubusercontent.com/43140137/112505999-3be59300-8d85-11eb-9ecc-27803ce26c29.png)

We suspect there might be a (hopefully not too) large set of these discrepancies in our dataset. Could there be a way to catch these? I suppose finding a way to compute the correct mapping and then cross referencing would be the simplest. 

Bonus question: we are starting to suspect mappings are more prone to fail on small molecules (i.e. <10 ha). Is there a simple explanation for why that could be?

**Comment by JenkeScheen** [comment]
see [this notebook for code and input files](https://github.com/JenkeScheen/hydra_quintup_analyses/blob/main/domain_checks/check_mapping.ipynb).

**Comment by lohedges** [comment]
Out of interest, do you see the same poor mappings with these molecules when using FESetup? BioSimSpace uses the same approach, so the mappings _should_ be the same.

When passing in the prematch it might be that the code is falling back on the Sire MCS routine, since the RDKit mapping might not include the prematch. I'll check this.

**Comment by lohedges** [comment]
By default, we don't perform molecular sanitization with RDKit on load. (This is for consistency with FESetup does.) If you include this option, then you get a more desirable mapping without needing to pass in a prematch, i.e.:

```python
mapping = BSS.Align.matchAtoms(mol1, mol2, sanitize=True)
print(mapping)
{0: 1,
 1: 2,
 2: 7,
 3: 6,
 4: 5,
 5: 4,
 6: 3,
 13: 13,
 12: 14,
 11: 16,
 7: 0,
 8: 11,
 9: 12}
```

(This isn't the same as your mapping, since you've not sanitized the molecule when asking for a prematch, but it does include the 0 --> 1 mapping.)

Note that sanitization won't work if we need to fall back on Sire for the MCS, e.g. in case RDKit fails, or if the prematch that you want isn't included in RDKits result. This is because Sire has no comparable internal sanitization routines.

We had previous situations where non-desirable mappings were obtained due to lack of sanitization. See [here](https://github.com/michellab/BioSimSpace/issues/124) and [here](https://github.com/michellab/BioSimSpace/issues/162) for details.

**Comment by JenkeScheen** [comment]
ah! this is the first case I've seen where a sanitised mapping is more correct than a non-santised one. Great, I'll take care to validate both modes next time. Thanks!

**Comment by lohedges** [comment]
Yes, it would be good to get a better understanding of when/why sanitisation works well. At the moment it is a bit of a black art, so that's another reason that we not turned it on as the default option. This could also be another issue with using PDB files as input to RDKit (c.f. the LOMAP issues) so we might want to think about using Mol2 if that was the original format for the input (since we can now preserved _all_ information in the file.) I went with PDB since it was what FESetup used, is generally more robust to poor formatting, and works better if we're writing a molecule loaded from, e.g. AMBER format, to PDB.

**Comment by JenkeScheen** [comment]
I'm going to have to iterate through my dataset (~2500 perts) and check whether mappings correspond between the modes. Would it be helpful if I post a summary here of the non-corresponding ones?

**Comment by lohedges** [comment]
That would be great. I don't think we have any extensive test of running with and without sanitisation for a large data set. It would be really useful if we could figure out any common molecular features that lead to poor mappings with the default options. That way we might be able to detect them and warn the user, or perform a mapping in both modes and notify the user when they are substantially different.

**Comment by lohedges** [comment]
At present we just score mappings on the size (largest is best) and RMSD following alignment based on the mapping (or flexibly aligning). The only case when we take a lower scoring mapping is when the user requests a pre-match and the largest mapping doesn't include it. We could always update the rulels if required, e.g. this type of atom can never map to this other type of atom, but that might get a bit complicated. (I guess we could also have the inverse of a pre match, i.e. these two atoms must never map to each other.)

**Comment by JenkeScheen** [comment]
perfect. It will take a bit of time to get through the whole set (some mappings take a while, esp. when sanitised), should have these results somewhere next week. I do notice that sanitised mapping calculations take longer for some reason.. might result in a lot of overhead if we set both mappings by default

**Comment by JenkeScheen** [comment]
see https://github.com/JenkeScheen/hydra_quintup_analyses/blob/main/domain_checks/bss_mapping_checks.ipynb for some 20 examples of atom mapping mismatches. Mistakes seem to mostly be due to a methyl being mapped on to a cyclic carbon, and in all cases sanitisation fixes the issue.
