### ISSUE TITLE
Core dump on ssh without X forwarding

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#21]
importing BioSimSpace without X forwarding on an ssh session results in a core dump:

```/home/ppxasjsm/BioSimSpace.app/sire.app/lib/python3.5/site-packages/BioSimSpace-0+unknown-py3.5.egg/BioSimSpace/__init__.py:74: UserWarning: Missing 'AMBERHOME' environment variable. Please download and install AMBER from: http://ambermd.org
/home/ppxasjsm/BioSimSpace.app/sire.app/lib/python3.5/site-packages/BioSimSpace-0+unknown-py3.5.egg/BioSimSpace/__init__.py:85: UserWarning: Cannot find 'gmx' executable. Please download and install GROMACS from: http://gromacs.org
/home/ppxasjsm/BioSimSpace.app/sire.app/lib/python3.5/site-packages/BioSimSpace-0+unknown-py3.5.egg/BioSimSpace/IO/__init__.py:47: UserWarning: BioSimSpace.IO: Please install GROMACS (http://www.gromacs.org) for GROMACS topology file support.
/home/ppxasjsm/BioSimSpace.app/sire.app/lib/python3.5/site-packages/BioSimSpace-0+unknown-py3.5.egg/BioSimSpace/Solvent/__init__.py:45: UserWarning: 'BioSimSpace.Solvent' is not supported. Please install GROMACS: http://www.gromacs.org

In [2]: QXcbConnection: Could not connect to display 
Aborted (core dumped)

```

Importing nglview or matlplib on its own is fine and does not lead the core dump.

**Comment by lohedges** [comment]
Could you try importing Sire on its own and see if that causes the same
problem? Maybe also try importing pyplt directly, as is done in the
BioSimSpace.Notebook._plot.py module.

Cheers.

**Comment by lohedges** [comment]
Seems like [this](https://github.com/ipython/ipython/issues/10627) problem.

**Comment by lohedges** [comment]
Basically, the admin/user of the server of the server would need to set the following in `~/.matplotlib/matplotlibrc`

```bash
backend: Agg
```

We could detect whether the `DISPLAY` environment variable is set during the install step, then set an appropriate backend for them if not (I do something similar anyway to avoid issues with MatPlotlib on macOS). However, this would result in crappy graphics if they install without an X session, then log in with X forwarding later on. As such, I don't think this is something that we want to set for them. (Maybe just put a warning in the documentation.)

FYI: The conda matplotlib uses Qt5 as the default backend, hence the issue. Qt5 is good since it supports HiDPI displays.

**Comment by chryswoods** [comment]
I would rather we have BioSimSpace detect the environment it is in and only import matplotlib.pyplot if DISPLAY is set or if we detect we are running in a Jupyter notebook.

For example, on importing BioSimSpace we could have a function run that detects then environment

‘’’
bss_env = getBSSEnvironment()

if bss_env == “batch_terminal”:
    only import modules for batch terminal work

elif bss_env == “jupyter”:
    Do/import jupyter stuff
    Do/import interactive stuff

elif bss_env == “interactive_terminal”:
    Do/import interactive stuff 

elif bss_env == “graphical_terminal”:
    Do/import graphical stuff
    Do/import interactive stuff 
‘’’

Also, I’d rather we defer warnings about missing dependencies until those dependencies are used. If someone is using parts of BioSimSpace that don’t involve gromacs or BSS.Solvate then they shouldn’t be bombarded with warnings to install gromacs every time they import BSS. The warning should only come when BSS.Solvate is used. You can achieve this using shadow classes. I can show you how to do this later today.

**Comment by lohedges** [comment]
Good idea, I'm already doing that for the method calls, e.g. returning None if someone tries to visualise in a batch script, just not wrapping around the actual import statements for external packages (since I didn't realise that the actual import would break). I'll add the bit for pyplot and Toni can test that it works.

Agree that I don't need to bombard the user with messages. I already have warnings elsewhere, so can simply remove the warnings from the top level import.
