### ISSUE TITLE
Solvation issue

### ISSUE THREAD

**Issue by dlukauskis** [michellab/BioSimSpace#212]
Hey Lester, I'm using BSS to set up some systems but every once in a while I get a solvation-related issue. It complains for some systems that the box is too small, which is strange because when I use the same script to solvate other CDK2 systems, it works fine. I'm attaching [a ZIP with input files](https://github.com/michellab/BioSimSpace/files/6502609/issue_solvation.zip) to show you what I mean.

**Comment by lohedges** [comment]
Thanks, Dom. Running in a working directory I see the following error from `gmx grompp` when setting things up for `gmx genion` to run its calculation:

```
ERROR 1 [file solvated.top, line 75]:
  Atomtype 1.008000 not found
```

Looking at the corresponding line in `solvated.top` I see:

```
    16     hn      1     LZ2  H1 1     16   0.447842     1.008000
```

The issue is the space in the atom name, i.e.  `H1 1`. Changing this to `H1_1` in both `solvated.gro` and `solvated.top` fixes things. This formatting is coming from the original PDB file, i.e:

*2vth/ligand.pdb*:
```
HETATM 4879 H1 1 LZ2 A1300      26.064   6.792  60.073  1.00  0.00           H
HETATM 4880 H1 2 LZ2 A1300      27.037   8.087  59.411  1.00  0.00           H
```

This doesn't match the PDB specification since there should be no spaces in names. I guess I could update the PDB parser to add underscores for whitespace. However, you then run into issues where there might already be a name that matches and you'd need to choose another replacement character and so on.

Do you know where the PDB came from? If this is a common problem then I'll look into a solution. Even warning the user when spaces appear in names might be helpful.

**Comment by dlukauskis** [comment]
Thanks for that, so it was just an issue with the input files... Maybe giving the user some warning might be useful, for now I'll just fix the files myself.

**Comment by lohedges** [comment]
No problem. Yes, I think a warning would be useful since the current error message is misleading. Normally if you get this far in the parameterisation / solvation pipeline, then the only reason `gmx grompp` fails is because the box is too small. We don't care about atom names internally, but clearly `gmx` is splitting on whitespace with its own internal parser. (Note that `gmx solvate` is fine with the naming, so the error isn't caught earlier.)
