### ISSUE TITLE
Memory usage of BSS.FreeEnergy.Binding

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#217]
Hi, the following code took up **8G** memory,  when the box length was set to 10 nanometer, it took up **13G** memory. Is that in line with expectations?  I used a `num_lam` of  `42`, compared to the default setting, since I'm concerned about the space overlap. 

```
import BioSimSpace as _BSS

lig1 = ['CHEMBL92812.prmtop', 'CHEMBL92812.inpcrd']
lig2 = ['CHEMBL93461.prmtop', 'CHEMBL93461.inpcrd']
lig1 = _BSS.IO.readMolecules(lig1)[0]
lig2 = _BSS.IO.readMolecules(lig2)[0]
pert = _BSS.Align.merge(lig1, lig2)
pert = pert.toSystem()
pro = _BSS.IO.readMolecules('pro.*')
sys = pert + pro.getMolecules()
protocal = _BSS.Protocol.FreeEnergy(num_lam=42)
sys = _BSS.Solvent.tip3p(sys, box=3*[8*_BSS.Units.Length.nanometer], work_dir='test_case')
sys = _BSS.FreeEnergy.Binding(sys, protocal, work_dir='test_case')
```
[pert.zip](https://github.com/michellab/BioSimSpace/files/6758535/pert.zip)

**Comment by lohedges** [comment]
Hi there. I think 42 lambda windows per leg is quite large. Others probably have more insight, but I've never used that many.

Since the free energy setup creates isolated processes for each window of each leg, the memory usage can get quite large for a sizable system, i.e. you have a unique copy of the system for each simulation. In your case you would have 42 copies of the full system for the bound leg and 42 of the solvated ligand for the free. Normally this isn't an issue on an HPC system where there is likely a lot of RAM, but could be an issue on a laptop or workstation. As mentioned previously, in most cases BioSimSpace is just used to set things up, with the simulations run elsewhere. As such, the per-simualtion memory is fine

**Comment by lohedges** [comment]
If we removed the ability to run the simulations from within BioSimSpace, then the memory footprint would be much lower, since you'd only need to store one copy of the solvated protein ligand complex, and one of the solvated ligand.

**Comment by kexul** [comment]
Wow, it would create 84 process for one perturbation, no wonder my program hanged when I tried to create 32 perturbated system with `multiprocessing`. 

Another thing makes me worried about was the time comsuming, it took me about fifteen minutes to finish one perturbation.  I'm wondering that,  if I set `num_lam` to 2 or 3, then copy and modify the content (somd.cfg, somd.prm7...)  by some postprocess script, would that be feasible? would that be faster?

**Comment by lohedges** [comment]
I would advise not using multiprocessing with BioSimSpace since we have our own background process management system. In affect, you will end up creating duplicate processes.

I would first just try a smaller number of lambda windows then examine the overlap matrix generated by the analysis. If the overlap is poor, then you can just fill in with intermediate values.

As you say, you could just create a very coarse-grained setup, then use some scripts to fill in the extra directories that you need. I might think about just have a FEP setup object that doesn't actually create the process objects, which are the things that take up the memory. We did it this way since we were planning on providing a means of automatically distributing the processes over HPC resources. For pure setup, it is rather resource hungry.

**Comment by jmichel80** [comment]
Just to add, doing a setup with 3 windows, then extract inputs, works fine. See https://github.com/michellab/BioSimSpace/blob/devel/nodes/playground/prepareFEP.py for an example

**Comment by kexul** [comment]
Thanks for the information, closing this thread since it seems like a feature rather than a bug.

**Comment by lohedges** [comment]
You can now pass `setup_only=True` to the `FreeEnergy` constructor to disable the creation of simulation processes. This is _much_ quicker if you just want to setup simulations to run externally, as well as having a far smaller memory footprint.

I've also added the option to pass two protocol objects via a list, allowing the user to specify a different protocol for each leg, e.g. if it's useful to specify a different lambda schedule or run time.

@jmichel80: It would probably be useful to update and test `prepareFEP.py` using the `setup_only` mode.

**Comment by kexul** [comment]
Thanks so much for your work! Can not wait to try this feature.

**Comment by lohedges** [comment]
Hi @kexul. Thanks for testing out our FEP code and workflow pipeline, it is of great help. Just to let you know that I've just pushed some FEP API changes to devel. These were implemented following discussion with @jmichel80 and @JenkeScheen. We now _decouple_ the setup for individual perturbation legs to make it obvious that you can use a different protocol for each, and also that you need to prepare and equilibrate a system for each leg independently. (Before we would create the system for the second leg for you, which is fine when it is a vacuum system, but not when it is solvated and needs to be equilibrated.) It also makes it more obvious how simulations from a particular leg can be re-used in a different calculation. Updated documentation can be found [here](https://biosimspace.org/api/index_FreeEnergy.html).

If you need to play around with the code, or the tutorials, then feel free to fork the repositories.

Cheers.

**Comment by kexul** [comment]
Good job! @lohedges , I've done similar jobs by setting `free_leg=False` and `vacuum_leg=False` in binding and solvation to create the system separately. Now the API seems unified, thanks for the update.
