### ISSUE TITLE
MCS matching on specific substructure

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#218]
Hi all,

I'm using BSS to generate a series of FEPs that are 'abstractions' of real FEPs. I make the series (mostly using rdkit) through SMARTS generation between two (drug-like) ligands and then I graft the R groups onto a benzene scaffold:
![image](https://user-images.githubusercontent.com/43140137/125067809-a1e3f500-e0ac-11eb-917f-12222a8638cd.png)

So going into BSS is just two input files that are both some sort of benzene derivative. _I would like to force BSS into selecting the benzene scaffold as MCS_.

With a standard approach there is no certainty that this happens consistently (imagine e.g. toluene~benzonitrile), and it is very likely that for more complex cases such as:
![image](https://user-images.githubusercontent.com/43140137/125068471-6d246d80-e0ad-11eb-962c-21fa9342385c.png)
I might end up having the wrong MCS. I have about 4000 of these so manual `prematch` isn't possible, unfortunately.

The SMILES for the above 'complex' case is **C1=CC=CC=C1**CC(C)C -> **C1=CC=CC=C1**CCC2=CC3=C(C=C2)C=[N][N]3C, where potentially we could expose a method to force MCS on the bold parts? I realise that I might run into trouble in case of e.g. bibenzene, but I'd probably be okay with discarding those edge-cases if they turn out to be too complex to setup robustly.

Sorry if this is a slightly complex problem, I'm only just digging into this. I also need to be able to take all 'combinations' of FEPs, i.e. for a given benzene-benzene perturbation, do all possible R group combinations (so 'rotating' the MCS, as it were). This is probably out of scope for this particular issue though.

**Comment by JenkeScheen** [comment]
I ran into a practical example of where my quintuplicate standard error of the mean is very low (~0.08 kcal/mol) because of a faulty MCS:
![image](https://user-images.githubusercontent.com/43140137/125074275-fab78b80-e0b4-11eb-9e22-ce59b4dfbbdc.png)
In this case the 'real' perturbation would have a very large SEM because of the perturbation of the fused ring, but because BSS here takes a naphtalene MCS the perturbation becomes (reasonably) easy. So, for this type of edge case especially I need to be able to force the MCS as a single benzene. cSMARTS for reference:
N#Cc1cncc2ccc(CF)c(F)c12 <--> N#Cc1cc(Cl)cc2ccccc12

**Comment by lohedges** [comment]
There are quite a lot of details regarding the RDKit MCS algorithm [here](https://www.rdkit.org/docs/source/rdkit.Chem.fmcs.fmcs.html). It might give us some clues as to what options we could tweak.

Is it possible to detect the particular substructures that you're interested in, then make a prematch from the indices, or is it still unreliable even with a manual prematch?

**Comment by JenkeScheen** [comment]
thanks, I was just looking for that page. 

I think the detection part of that idea is rather difficult, as you can detect benzene-benzene mapping, but at that point you can't be 100% sure you've picked the right benzenes.

Perhaps there is a way to tag the benzene scaffold in the RDKit part of my code? I believe that the way I'm generating the benzene derivatives the intended benzene scaffold always has indices 0-5. BSS doesn't see this at the moment because I write to file from RDKit, then load with BSS which will reset atom indexing.

**Comment by lohedges** [comment]
I've mostly found that indexing between BioSimSpace and RDKit is consistent, at least for the molecular formats that I've used. The MCS wouldn't work otherwise. I guess it would be worth seeing if the scaffold indices are accessible within BioSimSpace and using those.

We could also try using the Sire MCS code instead since it gives us a lot of flexibility for tagging things to include in the search, e.g. we could just tag all scaffold atoms in Sire and insist that they are part of the MCS inside the algorithm.

**Comment by JenkeScheen** [comment]
I think that could work. I'll do some tests to find out if I can get consistent atom indices when loading the benzene derivatives into BSS.

**Comment by kexul** [comment]
> Perhaps there is a way to tag the benzene scaffold in the RDKit part of my code?

It might be helpful if you want to tag something: https://github.com/rdkit/rdkit/issues/3123

**Comment by JenkeScheen** [comment]
That's clever, thanks! I'm using SMILES as a way to pass molecules from rdkit to BSS. I could tag the SMILES notation with isotope information for the scaffold atoms, then make BSS compare only isotopes. In that way, I could make sure that indices 0-5 are always matched correctly (0:0, 1:1, etc). 

@lohedges, do you think that isotope information would be conserved when loading a ligand SMILES into a BSS mol object, and would the rdkit MCS under the hood be able to get that isotope information?

**Comment by lohedges** [comment]
I don't think so. We just use some functionality from OpenFF to convert SMILES to a molecule (I think it uses RDKit as the backend) then write to file then read back in. However, an RDKit molecule is the starting point for our MCS (behind the scenes) so we might be able to do something there, e.g. passing a SMILES scaffold as an argument to matchAtoms.

**Comment by JenkeScheen** [comment]
would passing the complete tagged SMILES (i.e. with the isotopes for just the scaffold atoms) to `matchAtoms` not work in that case? That way we could get rdkit to do that trick.. We would have to be sure that the returned MCS matches the BSS mol object (which at that point hasn't been used for the MCS)

**Comment by lohedges** [comment]
Possibly. I guess you'd need to be careful that the SMILES ordering matches that of the molecule that BioSimSpace passes to RDKit behind the scenes. We could probably enforce this somehow, and it might even be fine if you start from a SMILES to begin with, e.g. for parameterisation.

I think it would be nicer if we could work out a way of doing this with the prematch option, since it would perhaps be more general and match watch we've been doing up till now. Maybe we could even use the prematch to create a SMILES behind the scenes (from the molecule) then inject the isotope information relating to the prematch. Maybe this isn't supported easy, and there might be reordering issues too.

I'm still interested in knowing what happens if you just get RDKit to get the indices that match the scaffold then use those as an existing prematch. I imagine it will fall back on the Sire code, but might still work.

**Comment by lohedges** [comment]
Maybe I'm misunderstanding the RDKit example, but wouldn't that _only_ match the scaffold in each molecule, rather than the MCS _including_ the scaffold?

**Comment by JenkeScheen** [comment]
you're right, through that we would give BSS information on just the benzene atoms, not the R groups. I'll have to postpone looking into the indexing to early next week, unfortunately. I suspect that SMILES parsers allocate index 0 to the first heavy atom they run into, which would mean that for
`c1ccccc1 <--> c1ccc(NC2CC2)cc1`
indices 0-5 would make sense, but for for instance
`NC(=O)c1ccccc1,CC(=O)Nc1ccccc1`
they wouldn't.

**Comment by JenkeScheen** [comment]
Just working on this now. I think I can probably discard edge-cases where I have a double fused benzene, that would make this whole thing a lot easier. With
```
lig4 = "N#Cc1cncc2ccc(CF)c(F)c12"
lig5 = "N#Cc1cc(Cl)cc2ccc12"
```
we get 
![image](https://user-images.githubusercontent.com/43140137/125276528-3d24d680-e308-11eb-97f1-83873105a583.png)
using which we can get the correct indices to use for a prematch: 
![image](https://user-images.githubusercontent.com/43140137/125276581-4c0b8900-e308-11eb-8e84-d791e452b545.png)

I'll just check now if the BSS matching is sensible (and whether I can find an example where the `prematch` matches on the benzene correctly whereas naive `matchAtoms` does not).

**Comment by JenkeScheen** [comment]
just a note, https://github.com/michellab/BioSimSpace/issues/190 would be super useful in this case.

**Comment by lohedges** [comment]
Great, thanks for the update. The major issue with using the prematch is that it is only applied post-mapping for RDKit, i.e. your check whether the mapping that you got included the prematch, it's not part of the score itself. If no prematch is found then we fall back on Sire's MCS, which does impose the prematch condition while building the graph. However, it is slower and less reliable. I imagine there will be cases where, despite it being easy to get the prematch atoms for the scaffold, the MCS fails for some reason. (If a prematch is passed, then Sire returns this at a minimum, so you might just see cases where you only get the scaffold back.)

**Comment by JenkeScheen** [comment]
OK, I've done some tests now, just showing the results here. I observe that when letting BSS do the mapping itself, it seems to focus on the nitrogen (which we don't want):
![image](https://user-images.githubusercontent.com/43140137/125282674-8c223a00-e30f-11eb-9c78-aab46cc0ce4b.png)
However, when using a pre-match generated using:
```
def getBenzeneScaffoldIndices(molecule):
    """For a given RDKit molecule, return the atom indices for a benzene scaffold"""
    patt = Chem.MolFromSmiles('c1ccccc1')
    hit_ats = list(molecule.GetSubstructMatch(patt))
    return hit_ats

lig1_benzene_indices = getBenzeneScaffoldIndices(Chem.MolFromSmiles(lig1))
lig2_benzene_indices = getBenzeneScaffoldIndices(Chem.MolFromSmiles(lig2))
forced_mapping = {}

for at1, at2 in zip(lig1_benzene_indices, lig2_benzene_indices):
    forced_mapping[at1] = at2
```

We get the desired result, i.e.
![image](https://user-images.githubusercontent.com/43140137/125282875-c1c72300-e30f-11eb-8afb-50efe3795739.png)
`rmsdAlign`, and `merge` complete without issues, so I suspect that for this particular case our plan worked. One neat feature of this approach is that I can rotate through combinations by taking variations of the mapping dictionary, which is great.

Could you suggest further checks for this approach? I'm not sure if I follow your previous comment 100%.

**Comment by lohedges** [comment]
Nice, glad that worked.

Sorry if my previous comment wasn't clear. What I'm saying is that by specifying a prematch we want to take the _best_ result including the prematch, regardless of whether it is the largest MCS or not. In Sire this is possible, since the prematch is a condition of the graph building algorithm, i.e. we don't try things that don't include the prematch. With RDKit, this isn't possible (without digging into their C++ layer and modifying the algorithm) so we can only impose the prematch condition _after_ the MCS routine is complete. As such, what we get back might not contain the prematch, even if a state including the prematch was passed through at an early stage of the algorithm, e.g. if it was a smaller MCS.

The current process is:

1) Generate MCS with RDKit. We do this because it is quicker and, in general, more robust.
2) Check that MCS contains user prematch (If specified).
3) If prematch isnt found, then generate MCS with Sire. (For Sire we do two MCS mappings, both with and without mappings between heavy and light atoms and take the largest result.)

In previous testing I've found that getting back an MCS including a prematch isn't always that reliable, particularly for larger molecules where the search space is large.

**Comment by JenkeScheen** [comment]
OK, thanks for the input. I think potentially because of the nature of my series (all small-ish with a benzene scaffold) it's likely that the RDKit MCS will pick these out as well, so I think that at least for the vast majority of cases the MCS will contain the prematch. Is there a way to catch BSS reverting back to Sire MCS for these cases? I could just loop through the series until I find a case and then we can see what we can do about it (and whether Sire does it right).

On a side-node, in this example (copied from above):
![image](https://user-images.githubusercontent.com/43140137/125285690-d2c56380-e312-11eb-8f13-9efd29629995.png)
Even though the MCS is on the benzene, how would BSS set the perturbation for this transformation? Because we know that {2:3}, but are we sure that {1:4} in the merged molecule?

**Comment by lohedges** [comment]
>  Is there a way to catch BSS reverting back to Sire MCS for these cases?

Yes, BSS will warn you that RDKit didn't find the prematch and that we're trying Sire instead. It will also warn you if you choose to sanitize or match on complete rings only, since those options aren't supported by Sire.

```python
    # Sometimes RDKit fails to generate a mapping that includes the prematch.
    # If so, then try generating a mapping using the MCS routine from Sire.
    if len(mappings) == 1 and mappings[0] == prematch:

        # Warn that we've fallen back on using Sire.
        _warnings.warn("RDKit mapping didn't include prematch. Using Sire MCS.")

        # Warn about unsupported options.
        if sanitize:
            _warnings.warn("Using Sire MCS. Ignoring unsupported 'sanitize' option!")
        if not complete_rings_only:
            _warnings.warn("Using Sire MCS. Ignoring unsupported 'complete_rings_only' option!")

...
```

> Even though the MCS is on the benzene, how would BSS set the perturbation for this transformation? Because we know that {2:3}, but are we sure that {1:4} in the merged molecule?

I imagine it will be okay, since it is doing things through the bonding. Although it will set things up as if those parts are being perturbed, it should detect what things don't actually change and exclude them from the perturbation. (This would include the hydrogens around the benzene too.)

I guess I'm a little confused what's actually wrong with your original mapping, since what it's finding _is_ the actual MCS, and I imagine that is the perturbation that you would still end up with if you excluded things right down to the benzene ring scaffold. I thought the issue was that (perhaps not for this ligand pair) you were getting back an MCS that didn't include the scaffold at all?

I'm now also a little confused about your results above since it doesn't look like you are passing your scaffold indices as a prematch to `matchAtoms`, rather passing them as an _actual_ mapping to `drawMapping`, which will just highlight those atoms.

**Comment by JenkeScheen** [comment]
> I'm now also a little confused about your results above since it doesn't look like you are passing your scaffold indices as a prematch to matchAtoms, rather passing them as an actual mapping to drawMapping, which will just highlight those atoms.

You're right, seems I made a mistake. Doing it correctly gives a good result, still:
![image](https://user-images.githubusercontent.com/43140137/125293269-289e0980-e31b-11eb-96e6-c58b0b5757c2.png)

> I guess I'm a little confused what's actually wrong with your original mapping, since what it's finding is the actual MCS, and I imagine that is the perturbation that you would still end up with if you excluded things right down to the benzene ring scaffold. I thought the issue was that (perhaps not for this ligand pair) you were getting back an MCS that didn't include the scaffold at all?

It's true that the above perturbations would be the same. I think there are many examples in my set where this wouldn't be true, however. Because I've made abstractions from real perturbations by grafting R groups onto benzene scaffolds, I need to be able to have the benzene scaffold in the right 'rotation' in the MCS. consider e.g.
![image](https://user-images.githubusercontent.com/43140137/125294224-0062da80-e31c-11eb-9f1f-988ce67ae896.png)
where top 'real' perturbations are abstracted/grafted onto the benzene scaffold. We'd still want to make sure that the correct R groups are being perturbed into the corresponding ones, i.e. Cl -> x, F -> Br, Br -> F. In this example, BSS without prematch would probably map Cl -> Br, F -> F, Br -> x (so it will rotate the left-hand side benzene ligand clockwise).

If we're happy with catching the benzene MCS what we'll probably end up doing is iterate through all six possible perturbations and simulate them all for our training set.

Is that any more clear? I can see that this can be quite confusing, I can potentially walk you through some more project background but that might be too much for a github issue.

**Comment by lohedges** [comment]
Yes, that makes sense. I guess I'm confused why (in this case) providing a prematch excludes the nitrogen and other additional atoms from the MCS, even though that MCS would still included the scaffold prematch. (I agree that you might not want that, though.)

**Comment by JenkeScheen** [comment]
Closing this as the main question has been answered. With the code above I'm able to force BSS to Align on the benzene scaffold. Simply cycling through the mapping dictionaries allows me to make the 6 possible variations per perturbation as well.
