### ISSUE TITLE
BSS install

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#23]
Did a fresh install after compiling Sire 2018.2.0
Looks like mock and cython must be installed manually before running the install
Any reason why this can't be handled automatically?

Adding conda-forge channel
Disabling conda auto update
Installing package: mdtraj
Installing package: mdanalysis
Installing package: openbabel
Upgrading pip
mdanalysis 0.18.0 requires mock, which is not installed.
cftime 1.0.0b1 requires cython, which is not installed.
mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.4 requires cython, which is not installed.
Installing package: pypdb
Installing package: watchdog
Installing package: jupyter
Installing package: duecredit
Installing package: mock
Installing package: pygtail
Installing package: fileupload
Activating notebook extension: fileupload
Enabling notebook extension fileupload/extension...
      - Validating: OK
Installing package: nglview
Activating notebook extension: nglview
Enabling notebook extension nglview-js-widgets/extension...
      - Validating: OK
Cleaning conda environment

Done!

If you have problems with Jupyter permissions, try removing '$HOME/.jupyter' or '$HOME/.local/share/jupyter'

For optional package support...

**Comment by lohedges** [comment]
Typically these are packages that aren't required for BioSimSpace to work, e.g. conda packages where the maintainer has incorrectly listed the dependencies, or optional dependencies that conda thinks are essential. I could hide these spurious error messages by gobbling the stderr output of conda in the setup script, but chose not to as some time the messages are useful, e.g. when the dependencies genuinely change.

Perhaps I should instead hide the messages, then try importing BioSimSpace (or running a test script) at the very end of the the finally block of the setup script to confirm that everything installed as expected and reporting to the user if the import failed.

Could you try opening an IPython session:

`$HOME/sire.app/bin/ipython`

Next, try importing BioSimSpace:

```python
import BioSimSpace
```

If you don't get any errors, then all packages have been installed correctly. If not, then I'll update the setup script with the missing files. (Note that you may see errors because of missing packages that failed to install during the Sire install step, rather than BioSimSpace. This can occur if there is a network issue during the install, or even when the order of the package installation is different. As we've discovered, it can be very hard to maintain a stable conda environment.)

I'll have a better think tomorrow and close this issue when I come up with a more permanent solution.

**Comment by lohedges** [comment]
As discussed above, I now capture the stdout/stderr messages from conda and write them to file. At the end of the setup script (in the finally block) I test that the import works and point the user to the files if anything has gone wrong.

The issue will be closed when `feature-align` is merged into `devel`.
