### ISSUE TITLE
Setting chain IDs

### ISSUE THREAD

**Issue by dlukauskis** [michellab/BioSimSpace#240]
Hey Lester, is there any way of assigning chain ID to molecules in a BSS system? They went missing during the parameterisation and I need the chain IDs for a few things. Thanks.

**Comment by lohedges** [comment]
Hi @dlukauskis, just wondering if this solved your problem? If so, feel free to close.

Cheers.

**Comment by dlukauskis** [comment]
Not quite. I see that that snippet fixes the chain info within BSS, but I want the files written by BSS to have the chain IDs too. [Here's what I mean.](https://github.com/michellab/BioSimSpace/files/7569632/tmp.zip)

**Comment by lohedges** [comment]
This is because AMBER format files have no concept of chains, so the information is lost on write. (AmberTools would normally split the chains into separate molecules.)  If you want to cross-reference with the chain information from the original PDB file, then you'll need to use `makeCompatibleWith` on the required molecule(s) whenever you read back the AMBER files.

**Comment by dlukauskis** [comment]
Ahh, my fault for not knowing this! Thanks

**Comment by lohedges** [comment]
No problem. It seems like a lot of people want to reference information with respect to the original PDB topology, hence why we exposed `makeCompatibleWith`. It would certainly make my life a lot easier if all formats expressed the topology in the same way :-)
