### ISSUE TITLE
behaviour of setup.py

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#25]
Hi,

I think it would be good that when running `setup.py clean` nothing actually happens other than cleaning things and not a whole conda installation cycle is run such as this one:

```spy setup.py clean
running clean

Setting up python environment...
Updating conda

==============================================================
Sending anonymous Sire usage statistics to http://siremol.org.
For more information, see http://siremol.org/analytics
To disable, set the environment variable 'SIRE_DONT_PHONEHOME' to 1
To see the information sent, set the environment variable 
SIRE_VERBOSE_PHONEHOME equal to 1. To silence this message, set
the environment variable SIRE_SILENT_PHONEHOME to 1.
==============================================================

Adding conda-forge channel
Disabling conda auto update
Installing package: mdtraj


```

**Comment by lohedges** [comment]
Good suggestion. I'll modify the finally block so that it is only executed
if not in clean mode.

**Comment by lohedges** [comment]
Okay, I've updated the `setup.py` script and will push some changes soon. However, I think we need to decide exactly how the `setup.py` script should be used, because BioSimSpace can't be used without the additional third party packages that are installed into the Sire application.

At the moment I generally run the following once...

```bash
$HOME/sire.app/bin/python setup.py install
```

...to ensure that I have all dependencies installed, then just make use of `PYTHONPATH` when developing.

Do we only want the conda/pip dependencies to be installed if the user passes the `install` flag? (This is what I've changed things to). I'm not really sure we want to support all the other options like `develop`, `build` and `clean`, since this isn't working quite the same as a regular python package, i.e. it's being installed into an existing Sire miniconda. (You'd still need the dependencies installed to be able to use BioSimSpace if you ran `build` or `develop`, and `clean` would only remove the build dir.)

Are you doing things a different way? If so, do you have any suggestions.

**Comment by ppxasjsm** [comment]
I use it in the same way you use it. But basically, all I wanted to do was remove the build directory hence using the clean option.

**Comment by lohedges** [comment]
Great. My current changes support that workflow, so I'll push them now.
