### ISSUE TITLE
gasteiger charge support during parameterisation (gaff/gaff2)

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#253]
Related to #249 - @jmichel80 suggested speeding up parameterisation by using gasteiger charges because we only care about the amber atom types for our particalur use case. Looking at [`Parameters/Protocol/_amber.py`](https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/Parameters/Protocol/_amber.py#L323) there seems to be code in place to deal with alternative charge methods but I don't think I can access this through the API through e.g. `Parameters.gaff2()`.

Is there any recommended way to expose this?

**Comment by lohedges** [comment]
We could add a `charge_method` option to the `Parameters.gaff` and `Parameters.gaff2` functions, then pass this through when creating the protocols (defaulting to BCC). As you say, it looks like I added functionality to do this at the protocol level, but never exposed this higher up. (Probably because there wasn't a need at the time.) I'll try to add this this afternoon when I get a moment. Should be straightforward.

**Comment by lohedges** [comment]
This was actually super easy. Let me know how you get on.

**Comment by JenkeScheen** [comment]
Thanks @lohedges, works like a charm - this reduces the time needed to parameterise drug-like ligands (the TYK2 congeneric series) to 2.46 it/s.
