### ISSUE TITLE
recognising multiple molecules in pdb output from flare

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#26]
If ligand poses are generated with Flare, they can be written to a single pdb file. When this is read with the devel version of sire+devel BioSimSpace they are not recognised as multiple molecules. 

The ligand file is attached. The code to replicate the issue is:
```python
import BioSimSpace as BSS
mols = BSS.IO.readMolecules('ligands_docked.pdb')
mols.nMolecules()
```

Last line gives the answer of 1, instead of 7 or 8, can't quite remember how many there should be. 

[ligands_docked.txt](https://github.com/michellab/BioSimSpace/files/2401067/ligands_docked.txt)

**Comment by lohedges** [comment]
This is because the Flare file is not a properly formatted PDB file. We only break the contents into multiple molecules if the PDB contains multiple MODEL entries (with appropriate ENDMDL records) or if there are TER records between the molecules. The Flare file has neither, but just concatenates together a bunch of individual PDB files. (There should only be one MASTER and END per file.) We also can't use the CONECT records to break the system into molecules, since these are often incomplete or entirely missing.

I'd recommend writing to separate PDD files, then loading all of them at one go. You could also load them individually and add them to a system.

**Comment by ppxasjsm** [comment]
ok, I thought it was something like that. I'll find a way to write them out individually.

**Comment by lohedges** [comment]
No problem. If we end up using these Flare files a lot then it would be easy for me to modify the PDB parser (since we know what the format is). In the short term, splitting to multiple files is probably the best option.
