### ISSUE TITLE
Updating OpenMM >= 7.5

### ISSUE THREAD

**Issue by CoryKornowicz** [michellab/BioSimSpace#263]
I am curious what the current stipulations are that prevent migrating to newer versions of OpenMM to gain the updated features/kernel enhancements? If a project plan could be laid out with what sections have conflicts, the process could be streamlined.

**Comment by lohedges** [comment]
Hi there. The only reason that support for OpenMM 7.5+ isn't yet available is that Sire, on which BioSimSpace is built, uses the version from the Omnia Conda channel. This choice was motivated by the desire to not bloat our binary release and the easy ability to switch Cuda versions and support older hardware (still used by some colleagues). See [here](https://github.com/michellab/Sire/issues/334) for details.

Support will be available once we switch our build process over to the conda-forge eco system. We already have a working recipe, but the submission/acceptance process has been slow and tortuous. If you want to try your own build you could try following the instructions  [here](https://github.com/michellab/Sire/issues/347). (Note that the recipe builds against the 201.1.0 release of Sire, not devel, but can easily be updated if required.) Hopefully I'll have some time to push forward the conda-forge package in the coming months. Sire is a very non-standard package for conda-forge and it has been hard to get much support/time from their maintainers. (Which is annoying since the build works.)
