### ISSUE TITLE
HMR for water molecules

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#265]
I was just wondering how best to apply HMR to water molecules, or what is the standard practice for different molecular dynamics. At present I provide the option of ignoring waters, but should I be treating water differently if HMR is chosen to be applied? I guess it would be dependent on the engine in question and what (if any) constraint algorithm is applied to the waters. At present I apply HMR based on the molecular bonding generated internally by Sire, rather than the bonding from the molecular potential, since the latter will be different depending on the file format, e.g. could be explicit three-point waters.

Cheers.

**Comment by jmichel80** [comment]
HMR has mainly been used with rigid water models as far as I am aware. I would follow the approach used in AMBER as there were a few papers validating their HMR implementation some years ago.

**Comment by jmichel80** [comment]
See the conclusion from this paper  https://pubs.acs.org/doi/full/10.1021/ct5010406

´´One interesting remaining point for further study is more fully exploring the relative utility of the “repart” topology type versus the “repart_water” type; i.e., what advantages and disadvantages there are to applying HMR to the solvent atoms with the increased time step. Our results here indicate that the time step can be doubled in a stable fashion without repartitioning the masses of the TIP3P model, which avoids increasing the viscosity of the system and thus decreasing the sampling efficiency of the trajectory. This is due to the application of the analytic SETTLE algorithm in this water model; this algorithm does not suffer the same limitations as the iterative SHAKE. However, leaving the water molecules unchanged while increasing the time step leads to (i) more sampling of unfavorable configurations, because of the less-accurate integration of the librational movement in the water molecules, and (ii) higher stress in the solvent distribution. If the protein sampling is truly unaffected, as our results seem to indicate, then this would be the preferred simulation setup for protein studies as solute sampling efficiency is then truly doubled without the viscosity damping effect. A possible alternative to this approach could be to apply an overall mass scaling to only the solvent molecules after applying HMR, decreasing the total solvent mass, and thus lowering the system viscosity. Lin and Tuckerman (45) recently investigated a similar method as applied to peptide simulations. Although, as previously mentioned, the time scale of the solvent motion would be affected, it is possible that this type of setup would allow an accelerated sampling of the protein motion without the viscosity effect.´´

**Comment by lohedges** [comment]
Thanks, that's interesting. Perhaps I'll add an option to perform HMR on waters only too, i.e. you could apply it to the entire system, everything but water, or just water. That would give the user most flexibility. (Probably setting `ignore_water=True` as the default.)

**Comment by lohedges** [comment]
Closing since we now have a flexible HMR model. Still need to decide on whether this should be implemented within the `Process` setup, i.e. with HMR added as a `Protocol` option. (This would allow us to implement appropriate HMR schemes for different engines.)
