### ISSUE TITLE
BSS I/O with multiprocessing

### ISSUE THREAD

**Issue by msuruzhon** [michellab/BioSimSpace#266]
Hi,

Further to Issue https://github.com/michellab/BioSimSpace/issues/259, I have recently been interested in parallelising multiple system operations in BioSimSpace using `joblib` and `multiprocessing` (e.g. loading/writing of several `BioSimSpace` systems at the same time). However, if I try to use `multiprocessing` as the backend of `joblib`, I get the following error:

> multiprocessing.pool.MaybeEncodingError: Error sending result: '[<BioSimSpace.System: nMolecules=1>]'. Reason: 'RuntimeError('Pickling of "Sire.System._System.System" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)')'

This is the same error that used to be thrown when pickling in `Sire` was still not implemented. However, seeing that now we have the `BSS.Stream` functionality, shouldn't this mean that we should be able to pickle within Python as well?

I guess another question is whether it makes sense to parallelise file I/O in this way, since as far as I know `Sire` utilises all CPUs when reading/writing systems. Do you expect `multiprocessing` to speed up the file I/O of multiple systems? If I use `threading`, I get practically no speed-up (which makes sense).

I am attaching some [test files](https://github.com/michellab/BioSimSpace/files/7839298/multiwrite.zip) as well.

Many thanks.

**Comment by lohedges** [comment]
Hi there, this error:

```
Reason: 'RuntimeError('Pickling of "Sire.System._System.System" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)')'
``` 

is being thrown because `multiprocessing` can't pickle the wrapped Sire types. While we can stream the objects ourselves, regular Python tools, e.g. `multiprocessing`, (unfortunately) don't know how to do this, since they can only use the built in Python serialization model. I'm not sure if there's an easy way to work around this. I guess I can try to overload the `__getstate__` and `__setstate__` methods of the serializable objects, e.g. `System` and `Molecule` to see if they can be serialized directly by Python. I'll add this to my TODO list for when I'm back. (Typically these methods return and receive a dictionary, so I'm not sure if they can receive a handle to a binary intermediate, e.g. our s3 file, or it's representation in memory, a `QDataStream`.)

You are correct that Sire uses TBB parallelism for the IO, so will take advantage of whatever cores are available. If you divide the IO over a pool of processes then the number of cores/threads for each will be limited. As you say, you might not see a speed up since you are simply dividing the resources between more IO workers, rather than utilising all threads for one job. I imagine the result will be dependent on the size of the systems being read. There is also an overhead for using TBB, so sometimes you don't see a speed up until the system is a certain size, or you're running with enough threads.

Cheers.

**Comment by msuruzhon** [comment]
Thanks for that Lester, I will try to have a look at `__getstate__` and `__setstate__` as well and will report back if I find anything interesting.

**Comment by msuruzhon** [comment]
Adding some simple `__getstate__` and `__setstate__` methods to `BioSimSpace._SireWrappers._system.System` seems to fix all pickling problems:

```python

import os as _os
import uuid as _uuid

from BioSimSpace import Stream as _Stream

class System(_SireWrapper):

    <...>

    def __getstate__(self):
        filebase = _uuid.uuid4().hex
        _Stream.save(self, filebase)
        contents = open(filebase + ".s3", "rb").read()
        _os.remove(filebase + ".s3")
        return contents

    def __setstate__(self, state):
        filename = _uuid.uuid4().hex + ".s3"
        with open(filename, "wb") as file:
            file.write(state)
        system = _Stream.load(filename)
        _os.remove(filename)
        self._sire_object = system._sire_object
        self._reset_mappings()
```

**Comment by lohedges** [comment]
Fantastic, thanks for confirming. I'll add this next week along with some tests.

**Comment by chryswoods** [comment]
SireStream can save and load to memory, if you want to avoid using a temporary file?

```
#include "SireStream/streamdata.hpp"

auto data = SireStream::save(sire_object);

auto restored_object = SireStream::load(data);
```

The data is a `QByteArray`, which should be wrapped for Python. Could this be exposed via the BioSimSpace `Stream` module?

**Comment by lohedges** [comment]
Yes, that would work. I had some functionality to pass around the `QByteArray` functionality when I added the Stream wrapper but decided on just supporting saving and loading as a first pass. I'll expose the `QByteArray` directly next week which will make pickling much easier.

Cheers.

**Comment by lohedges** [comment]
No, this won't work since the `pickle` module can't handle the wrapped `QByteArray` object. We'll need to go via an intermediate, reading the file as a regular binary data stream, as @msuruzhon has done.

```
RuntimeError: Pickling of "Sire.Qt._Qt.QByteArray" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
```

**Comment by lohedges** [comment]
Hi @msuruzhon. Just to let you know that Sire/BioSimSpace now supports native Python pickling, so there is no longer any need to use the stream subpackage, i.e you can do the follow (either to a binary object, or to binary file.)

```python
import pickle

system = BSS.IO.readMolecules("amber/ala/*")

p = pickle.dumps(system)

new_system = pickle.loads(p)
```

This works on _all_ of the wrapped Sire objects in BioSimSpace, and should also be supported for most of the other Sire objects if you use them directly.

(FYI: The `BioSimSpace.Stream` package has now been removed.)

Cheers.

**Comment by msuruzhon** [comment]
Many thanks Lester, I will start to test the new Sire features next week so I will let you know if there is anything and I will close my issues then.

**Comment by msuruzhon** [comment]
Hi @lohedges the pickling works without any issues. Many thanks!
