### ISSUE TITLE
Loading and saving GMX ligand files

### ISSUE THREAD

**Issue by dlukauskis** [michellab/BioSimSpace#277]
Hi Lester,

I've been trying to use BSS to load, manipulate and save ligand files. However, instead of Amber format, I need to use GMX files that were written by Acpype. The ligand GMX files seem to load fine but when I try to save them, my NB crashes. This isn't an issue when I load the ligand using Amber files. 

I'm attaching a [ZIP](https://github.com/michellab/BioSimSpace/files/8010792/BSS_issue.zip) so you can have a look. My BSS version is  `'2020.1.0+627.g4f37a27'`

**Comment by lohedges** [comment]
Thanks, @dlukauskis. I'll try to take a look at this later today. We've had issues with certain Acpype files before due to slightly non-standard formatting, so hopefully it's something simple.

**Comment by lohedges** [comment]
Hi again. The attached archive is empty. Could you re-upload the problematic files and example script.

Cheers.

**Comment by dlukauskis** [comment]
Thanks for looking into this. [There you go.](https://github.com/michellab/BioSimSpace/files/8013976/BSS_issue.zip)

**Comment by lohedges** [comment]
It works for me with the latest 2022.1.0 release of Sire and BioSImSpace. I recall fixing some `Acpytpe` issues related to inferring atomic elements from their mass in AMBER and GROMACS topologies, so perhaps we've already fixed the issue? Could you try at your end to see if it works for you?

**Comment by dlukauskis** [comment]
Yep, works fine with 2022.1. I should have tried the obvious before raising an issue... Also, the conda install is so quick now, well done. Thanks.

**Comment by lohedges** [comment]
Great, thanks for confirming. Yes, we've completely re-worked the Sire and BioSImSpace CI so that it uses a conda-forge compliant conda build. Sire is built in a way that ensures that its dependencies are consistent with the dependencies of BioSImSpace (at least at the time of build) so it is much easier to resolve a solution when installing BioSimSpace. We also have support for more CPU architectures and Python variants too.

Cheers.
