### ISSUE TITLE
How to find out pathways?

### ISSUE THREAD

**Issue by rubinanoor9** [michellab/BioSimSpace#280]
Hello, 
I am trying to find out the residence time and the binding and unbinding pathways of the protein-ligand complex system. I have amber (netcdf) trajectories in which ligand bind and unbind several times, these trajectories were generated by performing well tempered funnel metadynamic simulations by using the Biosimspace.  My question is that from these trajectories how we find out the pathways that followed by ligand, either they follow the same pathway in each time or different to bind to the active site of the protein also how we calculate the residence time of the ligand?
I am looking forward to hear from you.
Regards
Rubina

**Comment by jmichel80** [comment]
Hi @rubinanoor9  I am not sure that the API allow you to do that simply, though I imagine all the data you need is in the output files. Maybe @dlukauskis can comment ?

**Comment by lohedges** [comment]
Hello there,

Thanks for your question. Yes, the API currently doesn't allow you to do this. We do provide rudimentary functionality to sample configurations according to values of the collective variables, so that you can look at what the protein and ligand are doing at different points on your free energy surface once it is converged. Behind the scenes it just uses Plumed to compute the independent free energy components as a function of each collective variable, then map those to the indices of the trajectory frames. (This assumes that both are sampled at the same frequency.) Unfortunately this is tied to having a `Process` object in memory, so you can use the same functionality on existing data. The commands are very simple, though, so it could all be done with Plumed and (say) MDAnalysis after the fact.

As for computing the pathways, this would be more complicated and I'm not sure if there is a standard tool for the job. On a multi-dimensional free energy landscape you'd probably need to use something like the string method or similar to compute the "minimum energy path", 

Cheers.

**Comment by dlukauskis** [comment]
Hi Rubina, 

As Lester mentioned, calculating binding pathways or residence times isn't part of the BioSimSpace API. Getting the residence time should be fairly straightforward. Get the projection CV and count the picoseconds or nanoseconds of how long the ligand has been below a certain value. If you define proj < 1.5 nm as the bound state, then whenever the CV is below 1.5 nm counts towards the residence time. 

As for binding pathways, I don't have any experience, but I think it would require the use of Principal Component Analysis. Have a look at the literature, see which approach would work best for you.

Dom

**Comment by lohedges** [comment]
Closing as this is out of the scope of BioSimSpace. Suggestions made and no response from original poster.
