### ISSUE TITLE
Retrieve input ligands from previously setup SOMD lambda folders

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#283]
Hi,

I've (foolishly) removed system setup data to a series of SOMD FEP simulations setup with BSS late last year; I need to set up several additional FEPs for this set now. I've been trying to reproduce the system setup but can't seem to get to a bug-free setup (at least, without too many workarounds that risk the new systems to diverge from the original simulations).

I know there exists some code in the current form of the API to read a perturbable system, but e.g. running 

```
merged_lig = BSS.IO.readPerturbableSystem(
top0 = f"{pert_folder}/free/lambda_0.0000/somd.prm7",
coords0 = f"{pert_folder}/free/lambda_0.0000/somd.rst7",
top1 = f"{pert_folder}/free/lambda_1.0000/somd.prm7",
coords1 = f"{pert_folder}/free/lambda_1.0000/somd.rst7",
)[0]
```

throws:

> ~/miniconda3/envs/data_driven_fep_rel/lib/python3.7/site-packages/BioSimSpace/IO/_io.py in readPerturbableSystem(top0, coords0, top1, coords1, property_map)
>     834 
>     835     if not has_pert:
> --> 836         raise ValueError("No perturbable molecule was found?")
>     837 
>     838     # Extract the perturbable molecule.
> 
> ValueError: No perturbable molecule was found?

my plan was to take `merged_lig`, re-parameterise both `.molecule0` and `.molecule1`, write them to files, then use the new series of ligands as new input for setting up `BSS.FreeEnergy.Relative()`. Am I on the right track here? Is this even advisable?

**Comment by lohedges** [comment]
Hi @JenkeScheen, unfortunately this won't work since the prm7 and rst7 inputs to SOMD always correspond to the lambda = 0 state. The only thing that differs between the lambda input folders is the configuration file, which will just have a different value of lambda. (We could avoid duplicating everything, but wanted to keep each window self-contained.) The reason that you are seeing the `ValueError: No perturbable molecule was found?` is because the two end states are identical. (It checks to see if there are any differences in `ambertype`, `LJ`, or `charge` between the toplogies.)

**Comment by JenkeScheen** [comment]
Right, so retrieving inputs through previously setup simulation folders is not possible? Guess I'll have to dig some more then.

**Comment by lohedges** [comment]
Just to note that you might get slightly different mappings if you re-run the setup since RDKit now requires sanitization before you can call `GetSubsStructureMatches`. This means that some of our unit tests no longer pass or fail, since the MCS is different. I've marked these as XFAIL until we get some updated data sets. This might affect the `generateNetwork` output too, but I haven't tested.

We now have native Python pickling support, so you can just do the following to save a system (perturbable, or otherwise):

```python
mport pickle

system = BSS.IO.readMolecules("amber/ala/*")

p = pickle.dumps(system)

new_system = pickle.loads(p)
```
(Or from file.)

**Comment by lohedges** [comment]
> Right, so retrieving inputs through previously setup simulation folders is not possible? Guess I'll have to dig some more then.

Unfortunately, no. I still might try to write a SOMD reader at some point, although it is now redundant given the pickling support. (Perhaps we should always pickle the system and protocol that are passed to a process, though.) SOMD is also lossy, so reading the files wouldn't give you the _exact_ same system that was passed in.

**Comment by JenkeScheen** [comment]
okay, thanks for the feedback! Looking forward to using the pickle implementation soon!
