### ISSUE TITLE
Is there a bug for Funnel Correction Volume?

### ISSUE THREAD

**Issue by cyrushu** [michellab/BioSimSpace#284]
Dear Developer,

This is great job on openmm reproducing funnel metadynamics

I am reproducing metadynamics, Is there a bug on the line

https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/Metadynamics/CollectiveVariable/_funnel.py#L530
```python
        result = 0
        delta = delta.nanometers().magnitude()
        for x, y in zip(funnel[:-1], funnel[1:]):
            result += (x**2 + y) * delta * 0.5
```
Since the result slice volume should be
```python
        result = 0
        delta = delta.nanometers().magnitude()
        for x, y in zip(funnel[:-1], funnel[1:]):
            result += (x**2 + y**2) * delta * 0.5
```
for the averaging the slice at the top and bottom area.

**Comment by jmichel80** [comment]
pinging @dlukauskis for commenting on this ?

**Comment by lohedges** [comment]
Yes, I think this is a typo. I've just re-run against the original analysis scripts from @dlukauskis and I only get the right correction (within numerical error) when both terms are squared. I'm not sure how this arose, since the code was tested against the analysis scripts in the first place. Perhaps some refactoring broke something.
