### ISSUE TITLE
Q: Funnel Correction yields a negative energy?

### ISSUE THREAD

**Issue by cyrushu** [michellab/BioSimSpace#286]
Dear Developers,

Thanks for providing fantastic work on the funnel metadynamics pipeline.

Here is a question about funnel correction term since the [paper](https://www.pnas.org/doi/10.1073/pnas.1303186110) in Eq3 gives the 

![image](https://user-images.githubusercontent.com/10833165/159400069-4adad218-287c-4747-97d0-444c3c1a7deb.png)

where the correction form always yeilds positive free energy described in chapert **Protein–Ligand Binding Free Energy**.

I am stucked in this process, Is there any gudiance on this correction form? 

Best wishes,
Yilang

**Comment by lohedges** [comment]
Thanks for your question, and for your interest in BioSimSpace. I'll tag in @dlukauskis as he might have a better answer than me.

(Just to note that I've just spotted another error in the correction code. Although the volume was being converted to an area, the area wasn't being used when calculating the final correction (the volume was used instead). This has now been updated.)

**Comment by dlukauskis** [comment]
That equation is right, the correction term is itself negative, but because of the minus sign, it ends up positive. 

I think of it this way - because the unbound phase is approximated in a very small volume (the tip of the funnel), the ligand would much prefer to be bound than unbound, effectively **overestimating** the binding free energy. To give a more accurate account of the true gain in rotational and translational freedom in the unbound phase, you have to adjust for the funnel volume, making the binding free energy **less** favourable/negative.

I hope this makes sense. Correction terms are used in basically every type of ABFE calculation, making the calculated deltaG less negative in every case.

**Comment by cyrushu** [comment]
Thanks a lot for the nice gudiance! This gudiance really saved my days!
