### ISSUE TITLE
ERROR: Jacobi iterations did not reach desired tolerance

### ISSUE THREAD

**Issue by msuruzhon** [michellab/BioSimSpace#287]
Hello,

I recently ran into this very rare issue during atom-atom matching (I have only seen it once so far):

```
gsl: svd.c:712: ERROR: Jacobi iterations did not reach desired tolerance
Default GSL error handler invoked.
```

I am attaching a [minimal example](https://github.com/michellab/BioSimSpace/files/8325699/Archive.zip) to reproduce this error. The error seems to arise during this line in `_align.py`:

```python
molecule0 = molecule0.move().align(molecule1, _SireMol.AtomResultMatcher(sire_mapping)).molecule()
```

Any thoughts on what is going on here?

Cheers.

**Comment by lohedges** [comment]
Okay, I'm not sure how we can fix this in an easy way since it doesn't seem possible to change the GSL tolerances. (This is hitting the sweep limit on line 711 [here](https://github.com/ampl/gsl/blob/master/linalg/svd.c). As a workaround, I'd advise _minimising_ your ligand structures prior to generating the mapping and aligning. For example, the following works for me.

```python
import BioSimSpace as BSS

mol0 = BSS.IO.readMolecules(["lig_67_vac.parm7", "lig_67_vac.rst7"])[0]
mol1 = BSS.IO.readMolecules(["lig_52_vac.parm7", "lig_52_vac.rst7"])[0]

protocol = BSS.Protocol.Minimisation(steps=1000)

process = BSS.Process.OpenMM(mol0.toSystem(), protocol)
process.start()
process.wait()
mol0 = process.getSystem()[0]

process = BSS.Process.OpenMM(mol1.toSystem(), protocol)
process.start()
process.wait()
mol1 = process.getSystem()[0]

print("Calculating MCS...")
mcs = BSS.Align.matchAtoms(mol0, mol1)
```

**Comment by lohedges** [comment]
On another note, I'm also trying to work out why `Process.Gromacs.getSystem()` is so flaky. It always seems to take two attempts to work (the `trjconv` frame extraction) even though the command line call is _exactly_ the same in both cases. Also, if I just do it on the command-line (rather than using BioSimSpace) then it works straight away. This was why I used OpenMM rather than GROMACS in the example above.

**Comment by lohedges** [comment]
Okay, fixed that by simple re-running the command if the frame extraction fails. (Still don't know why it fails, but its an easy workaround.)

I think I need to figure out where the GSL error is happening in Sire, and catch it properly there.

**Comment by lohedges** [comment]
Nope, I'm unable to catch the GSL error in Sire and the segmentation fault still occurs. It looks like GSL itself might not be doing some memory cleanup when handling its own `GSL_ERROR` during the SVD routine. I'm not sure what else we can do here.

**Comment by lohedges** [comment]
Looking at the [Sire code](https://github.com/michellab/Sire/blob/8049f0e5daf84df1848574758876c25e11bd4b4d/corelib/src/libs/SireMaths/matrix.cpp#L659-L665), the GSL error should already be caught:

```cpp
        // calculate single value decomposition of A into V S W^T
        int ok = gsl_linalg_SV_decomp_jacobi(A, W, S);


        if (ok != 0)
            throw SireMaths::domain_error( QObject::tr(
                    "Could not calculate the single value decomposition of %1.")
                        .arg(this->toString()), CODELOC );
```

When I get a chance I'll check the values of the vector and matrix that are triggering the segmentation fault, since it might be possible to catch the issue before the GSL routine is called.

**Comment by lohedges** [comment]
There doesn't appear to be anything particularly unusual about the matrices and vector. I guess we just need to chalk this up as a GSL issue and hope that anyone who comes across this problem will be able to find this thread.

**Comment by msuruzhon** [comment]
Thanks for investigating @lohedges, maybe we could raise an issue there as well? Is this the correct repo: https://github.com/ampl/gsl?

**Comment by lohedges** [comment]
I think that's just a clone of the original source with a few tweaks to make it easier to integrate into other projects, e.g. using CMake. The main page is [here](https://www.gnu.org/software/gsl/), which contains a link to various mailing lists, including one for bugs.

**Comment by lohedges** [comment]
Reading the [bug tracker](https://savannah.gnu.org/bugs/?group=gsl) it looks like there are a few other open reports of error handling issues , e.g. [here](https://savannah.gnu.org/bugs/?55687). From the comments it looks like there's only a single maintainer for the project. The related issues were posted some time ago and are still open.

**Comment by lohedges** [comment]
Okay, I've fixed it. We can just used the following before calling the function:

```cpp
gsl_set_error_handler_off();
```

This disables the default GSL error handler, so the function just returns the error code and does nothing else. Following this change, we correctly catch the error code in Sire and I see the following output:

```
Exception 'SireMaths::domain_error' thrown by the thread 'master'.
Could not calculate the single value decomposition of / 310.229, -200.643, 35.5843 \
| -157.983, 281.687, 44.2894 |
\ -5.87562, 40.6398, 73.2926 /.
Thrown from FILE: /home/lester/Code/Sire/corelib/src/libs/SireMaths/matrix.cpp, LINE: 669, FUNCTION: boost::tuples::tuple<SireMaths::Matrix, SireMaths::Matrix, SireMaths::Matrix> SireMaths::Matrix::singleValueDecomposition() const

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "script.py", line 8, in <module>
    mcs = BSS.Align.matchAtoms(mol0, mol1)
  File "/home/lester/Code/BioSimSpace/python/BioSimSpace/Align/_align.py", line 825, in matchAtoms
    property_map0, property_map1)
  File "/home/lester/Code/BioSimSpace/python/BioSimSpace/Align/_align.py", line 1446, in _score_rdkit_mappings
    raise _AlignmentError(msg) from e
BioSimSpace._Exceptions._exceptions.AlignmentError: Failed to align molecules when scoring based on mapping: {0: 0, 1: 1, 2: 2, 3: 3, 10: 10, 9: 9, 4: 4, 42: 39, 5: 5, 6: 6, 7: 7, 8: 8, 27: 26, 26: 25, 25: 24, 24: 23, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 23: 16, 21:
```

I can now catch the verbose Sire error message in BioSimSpace and suggest a solution. In this case it's one of the MCS matches that fails, rather than all of them. I'm not sure whether to just discard this result, or suggest a workaround, e.g. minimisation.

**Comment by lohedges** [comment]
Weirdly, if I take the failed mapping from the scoring and just call the `rmsdAlign` function based on that, then I don't see the error. The call to the underlying Sire move functionality is _identical_ in both cases.

**Comment by lohedges** [comment]
Looks like GitHub actions isn't working. 'll try to re-trigger the Sire build tomorrow, then push the BioSimSpace changes when it's run.

**Comment by msuruzhon** [comment]
That's great, thanks for fixing this so quickly @lohedges .

**Comment by msuruzhon** [comment]
Hi again @lohedges, I wasn't sure whether to post a new issue but I have issues importing Sire when `gsl=2.7.1` is used (as defined in the `anaconda` channel). If `gsl=2.7` is used instead, it imports fine, so maybe we should pin this dependency? Is it something that you could reproduce as well? Thanks.

**Comment by lohedges** [comment]
I'll try to reproduce at my end. Out of interest, what error are you seeing? Since the CI passed, and this is a minor version number change to gsl it must be a conda error, i.e. the changes should be API backwards compatible and the library version should be identical.

**Comment by msuruzhon** [comment]
Yes, I thought the same but this error is still quite strange for a minor release. That's the error I get:

```ImportError: libgsl.so.25: cannot open shared object file: No such file or directory```

So this seems to be a packaging issue?

**Comment by msuruzhon** [comment]
And this is the error I get on macOS, which pretty much boils down to the same thing:

```
ImportError: dlopen(/Users/msuruzhon/miniconda3/envs/bss_orion_new/lib/python3.7/site-packages/Sire/Base/_Base.so, 2): Library not loaded: @rpath/libgsl.25.dylib
Referenced from: /Users/msuruzhon/miniconda3/envs/bss_orion_new/lib/libSireCAS.2022.1.0.dylib
Reason: image not found
```

**Comment by msuruzhon** [comment]
Yes so the one I am talking about is confusingly enough not available on `conda-forge` but on `anaconda` instead: https://anaconda.org/anaconda/gsl. And in some cases that's the one that gets pulled automatically.

**Comment by lohedges** [comment]
Ah, okay. Well, that sounds like a packaging issue on behalf on the default conda channel, which is pretty annoying. I assume that 2.7.1 will be available on conda-forge in the near future, which _should_ resolve this.

As a quick test I created a fresh (Linux) conda environment using:

```
conda create -n biosimspace-dev -c conda-forge -c michellab/label/dev biosimspace
```

This still pulls in the conda-forge version of gsl, even though the one from `pkgs/main` is newer, i.e. the channel priority takes higher precedence it seems (at least for a minor version difference). Perhaps your channel priority is different, or you have some configuration settings that mean that it is always taking the latest version.

**Comment by lohedges** [comment]
It might also be that you've pulled in the non conda-forge `gsl` version when installing some other package, so have it in your conda cache. When installing BioSimSpace, the cache may then take precedence over the channel priority, i.e. it tries to avoid downloads and changing the environment where possible.

I've tried using `mamba` too, and this also pulls in the correct conda-forge `gsl` when creating a fresh environment.

**Comment by msuruzhon** [comment]
Yes I think my problem is that the `defaults` channel is always picked up first. But in any case, once `2.7.1` makes it to `conda-forge`, then this will break things in general. Would it make sense to pin the dependency as a precautionary measure?

**Comment by lohedges** [comment]
I don't think we need to, since it sounds like a packaging issue on the `defaults` channel. I don't really want to start pinning since it becomes a maintenance nightmare and isn't the way that conda is meant to work anyway (`conda-forge` frown at pinning unless required, i..e for API compatability). If it's still an issue when the `conda-forge` package is updated, then I can raise an issue on their [feedstock page](https://github.com/conda-forge/gsl-feedstock).

Looking at the contents of the two package archives on the Anaconda cloud I see the following in the lib directory (for Linux):

_conda-forge gsl 2.7_:

```bash
ls -l lib
total 12M
drwxr-xr-x 2 lester lester 4.0K Mar 29 10:21 pkgconfig
-rw-r--r-- 1 lester lester 6.8M Jul 15  2021 libgsl.a
-rw-r--r-- 1 lester lester 594K Jul 15  2021 libgslcblas.a
lrwxrwxrwx 1 lester lester   13 Jul 15  2021 libgslcblas.so -> libcblas.so.3
lrwxrwxrwx 1 lester lester   13 Jul 15  2021 libgslcblas.so.0 -> libcblas.so.3
-rwxr-xr-x 1 lester lester 357K Jul 15  2021 libgslcblas.so.0.0.0
lrwxrwxrwx 1 lester lester   16 Jul 15  2021 libgsl.so -> libgsl.so.25.1.0
lrwxrwxrwx 1 lester lester   16 Jul 15  2021 libgsl.so.25 -> libgsl.so.25.1.0
-rwxr-xr-x 1 lester lester 3.4M Jul 15  2021 libgsl.so.25.1.0
```

_defaults gsl 2.7.1:_
```bash
ls -l lib
total 12M
drwxr-xr-x 2 lester lester 4.0K Mar 29 10:21 pkgconfig
-rw-r--r-- 1 lester lester 6.9M Mar 21 13:33 libgsl.a
-rw-r--r-- 1 lester lester 537K Mar 21 13:33 libgslcblas.a
lrwxrwxrwx 1 lester lester   20 Mar 21 13:33 libgslcblas.so -> libgslcblas.so.0.0.0
lrwxrwxrwx 1 lester lester   20 Mar 21 13:33 libgslcblas.so.0 -> libgslcblas.so.0.0.0
-rwxr-xr-x 1 lester lester 298K Mar 21 13:33 libgslcblas.so.0.0.0
lrwxrwxrwx 1 lester lester   16 Mar 21 13:33 libgsl.so -> libgsl.so.27.0.0
lrwxrwxrwx 1 lester lester   16 Mar 21 13:33 libgsl.so.27 -> libgsl.so.27.0.0
-rwxr-xr-x 1 lester lester 3.4M Mar 21 13:33 libgsl.so.27.0.0
```

As you can see, the packages have different shared object versions, despite there only being a minor/patch difference in the version number. This _shouldn't_ be the case assuming the same build system and build environment. I imagine that the numbering will be correct when it appears on `conda-forge`, and if not we can bug them about it. (As I have already had to do for other packages, such as `fontconfig` [here](https://github.com/conda-forge/fontconfig-feedstock/issues/54).)

You should be able to remove `defaults` as follows:

```bash
# Check your current channels.
conda config --show channels

# Remove defaults.
conda config --remove channels defaults
```

Alternatively, if you are creating an environment file, in which BioSimSpace is one of the packages that is installed you can do:

```yaml
channels:
  - conda-forge
  - michellab/label/dev
  - nodefaults
```

This would make sure that `defaults` isn't used, even if the user happened to have it in their `~/.condarc` file.

Dealing with all this stuff is one of the things that I hate about conda. Essentially it doesn't work once you start mixing channels, even with large standard channels such as `conda-forge` and `defaults`. Since we intend to move to `conda-forge` in future we have made efforts to make our build process compliant with their own build system. This means that (other than potential packaging issues) our packages _should_ work assuming that you get _all_ dependencies from `conda-forge`.

**Comment by lohedges** [comment]
Thinking about the numbers, it could be that the conda-forge version is wrong to begin with, i.e. I imagine the SO number is the major and minor, so would make sense to be 27, not 25. I'll look on their feedstock to see if anyone has reported this, or to see how the number is generated.

**Comment by lohedges** [comment]
No, it doesn't use the MAJOR/MINOR and is just generated by `libtool`. I imagine the build system is different on the two platforms, hence the different numbering. I would assume that `2.7.1` build on `conda-forge` will still give `libgsl.so.25`.

Looking at the `conda-forge` packages and docs, they also recommend using:

```
conda config --set channel_priority strict
```

This means that the channel priority will take precedence over other things that may be used for scoring when trying to resolve an environment change.

**Comment by msuruzhon** [comment]
Thanks Lester, this makes sense. I think we just have to keep an eye on this library to make sure it's not breaking something in `conda-forge`.
