### ISSUE TITLE
Setting force constants for equilibration

### ISSUE THREAD

**Issue by annamherz** [michellab/BioSimSpace#291]
Hello!

I was wondering if it would be possible to expose the force constants for restraints so that they can be set during the Protocol stage? This would be useful for having a more defensive equilibration protocol.
I was thinking this could be possible with including it as an option during the protocol setup (in the same way that restraints is included as an option), and then when the input files are written it adds it as a `protocol_dict["restraint_wt"]` for Amber. Regarding Gromacs, I don't think(?) restraints are currently possible to set and I think it is not possible for Somd either. Regarding Gromacs, setting restraints usually requires using genrestr to generate the restraints itp file and then this must be included with the topology file, so I think implementing this isn't as straightforward as for Amber.
I was thinking I could initially make the changes for Amber by adding it to the protocol as an option, but I think the feature-amber-fep branch protocol folder differs a bit from the current devel branch (eg _config.py) so I was wondering if now would be the best time to do it? Currently the restraint_wt for Amber can be added as an extra options during process, but I think this is probably not ideal for a long-term solution.

Thank you!

**Comment by lohedges** [comment]
Hi there,

Thanks for the question. Restraints are implemented in _all_ supported engines SOMD, i.e. AMBER, GROMACS, OpenMM, and NAMD. (Everything apart from SOMD.) The issue with specifying the force constant as an option is that it isn't supported in all engines, so doesn't generalise. (This is partly due to how the constraints are actually implemented by the engines.) We _could_ add it as a general MD option that is only used by specific engines as appropriate, although this might be a bit confusing to the user. Alternatively, the we could provide a specific option for the specific processes where it is supported, e.g. AMBER / GROMACS. (This would just take the default if things are setup via `BioSimSpace.MD`.)

Cheers.

**Comment by lohedges** [comment]
Looking at the code, I think only NAMD and OpenMM are outliers. NAMD currently uses `fixedAtoms`, but it should be possible to switch to using constraints instead. For OpenMM, we implement position restraints by bonding restrained atoms to zero-mass dummy atoms. This is used to avoid issues with position restraint rescaling during barostat updates. While this involves a "force constant" for the bond, it's a little different to how things would be implemented normally.

When I get a chance, I'll try to switch NAMD to the constraint approach, which will make it easier to add a general option.

Cheers.

**Comment by annamherz** [comment]
Okay, thank you so much!

> When I get a chance, I'll try to switch NAMD to the constraint approach, which will make it easier to add a general option.

Great, thank you!

> There would also be issues with the range of allowed values for the force constant.

I was also wondering regarding the default units of this when the user is specifying it, as it would need to be converted depending on the engine eg Amber uses kcal/mol Å^−2 but I think Gromacs has units of kJ/mol nm^2?

**Comment by lohedges** [comment]
No problem. I've now made NAMD consistent with the other engines. (This was the first engine that was supported, so I think I just used `fixedAtoms` as a quick way of getting restraints working.) I should be able to add a `force_constant` option to `Protocol.Equilibration` on Monday.

> I was also wondering regarding the default units of this when the user is specifying it, as it would need to be converted depending on the engine eg Amber uses kcal/mol Å^−2 but I think Gromacs has units of kJ/mol nm^2?

Yes, that's right, I'll just document the unit in the class docstring. This is the case for all internal units used by the different engines, i.e. when writing values to configuration files etc. BioSimSpace internally converts to the correct unit using `BioSimSpace.Types` and `BioSimSpace.Units`.

**Comment by lohedges** [comment]
I just need to have a think about our unit/type system before implementing this. At present we require strong typing in order to be able to easily validate input from BioSImSpace nodes, particularly when parsing input from the command line. Things get tricky when we want to handle general unit types, such as force constants, etc. Ideally we would be able to use something more flexible, such as `openmm.units` behind the scenes, but this would require some refactoring and care to make sure that we can still validate everything correctly. (This is certainly possible, but might be tricky given the existing framework.) I think `openmm.units` will soon be a standalone pacakge, so it might make sense to use that going forward. (We currently use Sire Units behind the scenes, but there are a few workarounds to make things work consistently.)

**Comment by jmichel80** [comment]
Would it be acceptable to treat OpenMM a little different from the other engines behind the scene to for the purpose of offering a MD package agnostic restraints definition ? That should allow folks to specify interoperable equilibration scripts.
