### ISSUE TITLE
Unpickling error of Sire.Units.GeneralUnit

### ISSUE THREAD

**Issue by msuruzhon** [michellab/BioSimSpace#294]
Hi,

I have been playing around with the newest `devel` version and I have run into this unpickling error:

```
  File "/Users/msuruzhon/Projects/BioSimSpace/python/BioSimSpace/Types/_general_unit.py", line 111, in __new__
    raise TypeError("__new__() missing positional argument(s): 'value' and 'unit', "
TypeError: __new__() missing positional argument(s): 'value' and 'unit', or 'string' or 'Sire.Units.GeneralUnit'
```

The error is straightforward to reproduce if one tries to pickle a `Protocol`:

```python
import BioSimSpace as BSS
import pickle

a = BSS.Protocol.Equilibration()
dump = pickle.dumps(a)
b = pickle.loads(dump)
```

Any idea what is going on here? Many thanks.

**Comment by lohedges** [comment]
Hi @msuruzhon, thanks for catching this. The issue is that I've overloaded the `__new__` operator in `GeneralUnit` since it is possible to return an object of a different type. I forgot that pickle uses this behind the scenes, so I'll need to update it to handle whatever it passes in. (Alternatively I could overload the `__getitem__` and `__setitem__` operators instead.)

`GeneralUnit` is used to store unit based types that can be created via multiplication and division of our existing types, e.g. for a force constant associated with a distance based harmonic restraint:

```python
k = 10*BSS.Units.Energy.kcal_per_mol / BSS.Units.Area.angstrom2
print(k, type(k))
10.0000 M Q-1 T-2 <class 'BioSimSpace.Types._general_unit.GeneralUnit'>)
```

If this were to then be multiplied by an `Area` type, we would get back an `Energy`, i.e.:

```python
e = k * BSS.Units.Area.nanometer2

print(e, type(e))
1000.0000 kcal/mol <class 'BioSimSpace.Types._energy.Energy'>
```

While I could do everything using `GeneralUnit`, having distinct types makes it _much_ easier to validate input to nodes, and also makes it possible to provide convenience functions for conversions to the user, i.e. once you have a type, such as the `Energy` above, you can call methods to convert it to the other supported units without needing to know their names, e.g. `e.kj_per_mol()`. It also makes it possible to have nice print output too.

**Comment by msuruzhon** [comment]
Thanks for the quick fix @lohedges!
