### ISSUE TITLE
UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.

### ISSUE THREAD

**Issue by jasmin-guven** [michellab/BioSimSpace#297]
Context
* Operating System: Linux
* Installation method: conda
* python 3.9.12
* numpy 1.22.3
* 

I'm trying to import BioSimSpace in my conda environment. I am also using AmberTools 21 and have sourced it in my bashrc:
`source /home/jguven/Software/miniconda3/envs/ambertools/amber.sh`

When importing biosimspace, I get the following warnings:
```
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import BioSimSpace
/home/jguven/Software/miniconda3/envs/ambertools/lib/python3.9/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/jguven/Software/miniconda3/envs/ambertools/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/jguven/Software/miniconda3/envs/ambertools/lib/python3.9/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/jguven/Software/miniconda3/envs/ambertools/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
>>> 
==============================================================
Sending anonymous Sire usage statistics to http://siremol.org.
For more information, see http://siremol.org/analytics
To disable, set the environment variable 'SIRE_DONT_PHONEHOME' to 1
To see the information sent, set the environment variable 
SIRE_VERBOSE_PHONEHOME equal to 1. To silence this message, set
the environment variable SIRE_SILENT_PHONEHOME to 1.
==============================================================
```

I already tried importing numpy first, but this didn't help. Any suggestions or advice would be much appreciated!

**Comment by lohedges** [comment]
Hello there,

This isn't a BioSImSpace bug, rather a warning from the `numpy` package. This is likely due to an inconsistency between one of our dependencies and the version of `numpy` that is installed, `1.22.3` in this case. For example, the `opencv` package (not used by us) has previously modified `numpy` such that values close to zero are replaced by zero, see [here](https://stackoverflow.com/questions/70612364/numpy-warning-with-django-4-numpy-float64-type-is-zero) for details. Presumably, one of our dependencies is doing the same.

This can likely be safely ignored, although you might want to perform some simple checks to confirm that you get the results that you anticipate. Note that BioSimSpace makes only minimal use of `numpy` internally, so an affect will likely be in the output from third-party packages, e.g. `mdtraj`. You could also try downgrading `numpy` to see if the warning goes away.

For reference, I also see this issue locally for certain Python variants and haven't experienced any problems. I have also previously seen the issue disappear, presumably when a dependency was rebuilt.

Cheers.

**Comment by jasmin-guven** [comment]
Hi!

Thanks so much for replying so quickly and sorry to post it in the wrong place.

Cheers.

**Comment by lohedges** [comment]
No problem whatsoever. These warnings are often very confusing and it's not easy to know how it might impact results.
