### ISSUE TITLE
Redundant checking of nPerturbableMolecules

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#320]
When one run the RBFE, the nPerturbableMolecules will be checked first in
https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/FreeEnergy/_relative.py#L186
Then it will be checked again in
https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/Process/_gromacs.py#L173

I think one checking is enough and we should just keep the one in BioSimSpace.FreeEnergy.Relative? Then I could check for nDecoupledMolecules in BioSimSpace.FreeEnergy.Absolute.

**Comment by lohedges** [comment]
As already mentioned in a previous thread, we have high-level interfaces to set up and run full RBFE simulations, and low level Process objects that can be used to run individual lambda windows. As such, the check occurs in two places. This dual level approach naturally leads to some redundancy.

**Comment by xiki-tempula** [comment]
@lohedges If the high-level one (BioSimSpace.FreeEnergy.Relative) is based on the low-level function (BioSimSpace.Process.Gromacs) Then wouldn't a single check in the low-level function to be enough?

**Comment by lohedges** [comment]
It would, but I prefer to catch the problem earlier in the high-level functionality and raise an exception immediately, rather than doing partial setup and failing later.

There are several places in BioSimSpace where error checking might be performed multiple times, but this is just a result of the multi-level way in which it can be used. I only make a big effort to avoid redundancy of this nature when it would otherwise significantly impact performance.

Hopefully this makes sense.
