### ISSUE TITLE
A protein-ligand system for testing

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#324]
**Is your feature request related to a problem? Please describe.**
I'm interested in creating a protein-ligand system for the unit testing of ABFE. I wonder if there is an existing example?

**Describe the solution you'd like**
So I could write tests to extract it in the sense that

```
from BSSdata.protein_ligand import protein, ligand
assert isinstance(protein, BSS._SireWrappers.Molecule)
assert isinstance(ligand, BSS._SireWrappers.Molecule)
system = ligand + protein
solvated = BSS.Solvent.tip3p(molecule=system,
                             box=3 * [10 * BSS.Units.Length.nanometer])
```

In my ABFE test, I will do
```
from BSSdata.protein_ligand import protein, ligand
decoupled_ligand = decouple(ligand)
system = decoupled_ligand + protein
solvated = BSS.Solvent.tip3p(molecule=system,
                             box=3 * [10 * BSS.Units.Length.nanometer])
```

**Comment by jmichel80** [comment]
Hi @xiki-tempula there isn't one yet. It would be useful to use inputs from https://github.com/michellab/BioSimSpaceTutorials/tree/main/04_fep to create such test protein-ligand systems. Tyk2 would be a good test case for various implementations.

**Comment by xiki-tempula** [comment]
@jmichel80 Thanks for the answering. So the ligands in BioSimSpace/test/input/ligands/ (https://github.com/michellab/BioSimSpace/tree/devel/test/input/ligands) and the protein in BioSimSpace/test/input/molecules/ (https://github.com/michellab/BioSimSpace/tree/devel/test/input/molecules) cannot be combined to form a protein-ligand system.

I will create new test files for them in `test/input/protein_ligand/` then.

**Comment by lohedges** [comment]
Yes, they can be combined, as described in the workshop tutorials. The inputs just give the bare PDB/Mol2 files, which are then parameterised, combined, and solvated within BioSimSpace. The directory doesn't contain the parameterised protein/ligand systems, since we wanted to test against different force fields.

As mentioned previously, we'd rather not have large files in the internal BioSimSpace test suite, e.g. if you happen to test a large protein ligand system, and are working to introduce a way of downloading the files when the tests are run. If you do need large files for you tests, then I'd suggest uploading them to a repo and using something like `requests` to download them within your test script. (You can then switch to the native method once it is live.)

Cheers.

**Comment by xiki-tempula** [comment]
@lohedges Thanks. I wonder if you know which ligand from BioSimSpace/test/input/ligands/ can be combined with the protein in BioSimSpace/test/input/molecules/? I have tried ligand CAT-13a and ligand01, which doesn't seems to work (where there is clash).
