### ISSUE TITLE
Bug in updateMolecule()

### ISSUE THREAD

**Issue by msuruzhon** [michellab/BioSimSpace#343]
Hi,

I have found a small bug in the `updateMolecule()` function:

```
if type(index) is int:
    raise TypeError("'index' must be of type 'int'")
```

The link to this line is [here](https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/_SireWrappers/_system.py#L533).

As a side question, what is the most efficient way to replace a subset of the molecules with some other molecules?

Many thanks.

**Comment by lohedges** [comment]
Thanks for this, if it's okay I'll update this in the PR. (We're still trying to fix the macOS CI so that this can proceed. I think this might be resolved when Christopher's Sire updates are merged in.)

> As a side question, what is the most efficient way to replace a subset of the molecules with some other molecules?

I'm not sure, are you seeing performance issues with the current methods? Using the built-in methods will preserve the existing molecular ordering, which wouldn't be the case if you remove molecules then add new ones. It's a bit tricky to do this in a consistent way (at least consistent with how Sire treats MolNums, UUIDs etc), since we have quite a lot of functionality that edits molecules behind the scenes, but we still want the updated molecule to be in the same "position" within the system.

**Comment by msuruzhon** [comment]
Thanks Lester, this sounds good. I haven't benchmarked the efficiency, I was just wondering if you had any experience with batch replacing molecules. But no worries, I will look at it. Cheers.

**Comment by lohedges** [comment]
As with some of the other performance issues you found, it is often quicker to delete and re-add molecules (or create a completely new system) rather than calling the `update` method on a Sire system. I imagine that this would only be an issue if you were batch replacing a _large_ amount of molecules, though.
