### ISSUE TITLE
Duplicated atom name 

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#346]
Dear BioSimSpace developers: 
There are duplicated atom names when merging two molecules, is this an expected behavior?

Here is a simple test case: 
![image](https://user-images.githubusercontent.com/5920217/176614793-129acd20-6b92-43d8-8f33-c8aac1097a1c.png)

```python 
import BioSimSpace as BSS
mol1 = BSS.Parameters.gaff("C1CCCC1").getMolecule()
mol2 = BSS.Parameters.gaff("C1=CC=CC=C1").getMolecule()
merged = BSS.Align.merge(mol1, mol2, force=True, mapping={0:3, 1:4,2:5,3:0, 4:1, 6:9, 7:10, 9:11, 11:6,13:7})
BSS.IO.saveMolecules('merged', merged, ['gro87', 'grotop'])
```

Output `merged.gro`:
![企业微信截图_16565730533972](https://user-images.githubusercontent.com/5920217/176615175-3c37f3ca-d12d-4747-b750-5e999f8a1ceb.png)

**Comment by lohedges** [comment]
Hi there,

Yes, the merged molecule might contain duplicate names. For SOMD this is an issue since the PERT file maps by atom name to the topology. As such, we perform a de-duplication when setting things up, although any updated information from the trajectory, e.g. coordinates, are copied back into the original system with the original names. For GROMACS, the parameters come from the `[ atoms ]` section, which are added on a per index basis regardless of the name.

Let me know if things aren't behaving as expected and we can think about de-duplicating things for GROMACS too.

Cheers.

**Comment by lohedges** [comment]
Your question may also be related to [this](https://github.com/michellab/Sire/issues/382) recent issue. We do have some internal code within the GROMACS parser to de-duplicate, e.g. when two distinct atom types have different parameters on merging, such as when an `H1` in one molecule has different parameters to an `H1` in another. It might be worth updating Sire to see if this fixes your issue. (The Gro87 will be unaffected, but it _should_ just match by index.

**Comment by kexul** [comment]
>  As such, we perform a de-duplication when setting things up

Thanks, as you said, for SOMD there is no duplicated name. 

> Let me know if things aren't behaving as expected and we can think about de-duplicating things for GROMACS too.

No, the simulation runs fine. Just a bit confused when trying to locate the atom manually in pymol or VMD 😕 .

**Comment by lohedges** [comment]
> No, the simulation runs fine. Just a bit confused when trying to locate the atom manually in pymol or VMD confused .

Thanks, that's good to know. Since the GROMACS coordinate/topology parsers are decoupled, there's no easy way to update the names in both simultaneously. We _could_ try to do the name de-duplication in BioSimSpace before writing (as we do for SOMD) but I think it might be a bit more tricky. (SOMD is just ensuring completely unique names, GROMACS is ensuring that there are unique atom types.)

**Comment by chryswoods** [comment]
That is good to know. We've tried to use the philosophy in BioSimSpace that the code doesn't rename or renumber atoms / residues etc if we don't need to do that. This is to reduce surprise, i.e. that may be caused if one piece of the workflow renamed the atoms, while another piece of the workflow assumed that the atoms had the same name as was loaded at the beginning.

Normally we would let the user name things themselves, and then leave it to them to make sure that there were no duplicate names if that was important to them. However, I can see in your example that the names are being generated by BioSimSpace via the smiles string. I wonder if we should add something sets a starting number, so that atoms aren't always numbered from `1` in a smiles string, e.g.

```
import BioSimSpace as BSS
mol1 = BSS.Parameters.gaff("C1CCCC1").getMolecule()
mol2 = BSS.Parameters.gaff("C1=CC=CC=C1", start_index=(mol1.nAtoms()+1)).getMolecule()
merged = BSS.Align.merge(mol1, mol2, force=True, mapping={0:3, 1:4,2:5,3:0, 4:1, 6:9, 7:10, 9:11, 11:6,13:7})
BSS.IO.saveMolecules('merged', merged, ['gro87', 'grotop'])
```

This way the atoms in `mol2` would start their numbering from 11, e.g. `C11`, `H12` etc.

An alternative is that we create an explicit `make_unique_atom_names` function in BioSimSpace that you could call on a group of molecules that would rename atoms to ensure that all names are unique, e.g.

```
import BioSimSpace as BSS
mol1 = BSS.Parameters.gaff("C1CCCC1").getMolecule()
mol2 = BSS.Parameters.gaff("C1=CC=CC=C1").getMolecule()
(mol1, mol2) = BSS.make_unique_atom_names(mol1, mol2)
merged = BSS.Align.merge(mol1, mol2, force=True, mapping={0:3, 1:4,2:5,3:0, 4:1, 6:9, 7:10, 9:11, 11:6,13:7})
BSS.IO.saveMolecules('merged', merged, ['gro87', 'grotop'])
```

What do you think?

**Comment by kexul** [comment]
> It might be worth updating Sire to see if this fixes your issue.

Nope. 

> there's no easy way to update the names in both simultaneously.  We could try to do the name de-duplication in BioSimSpace before writing (as we do for SOMD) but I think it might be a bit more tricky. 

Thanks, it's good to know that this is expected behavior. I've tested the energy sometimes before and found no observable mismatch, so it might be safe to stick with the current implementation. The only side effect would be that it may confuse some novices who are not so familiar with the Gromacs file format. 

> An alternative is that we create an explicit make_unique_atom_names function in BioSimSpace that you could call on a group of molecules that would rename atoms to ensure that all names are unique, e.g.

Hi @chryswoods , I'd prefer the `make_unique_atom_names` if it's viable 😃 , I have parametrized files as input in most of my use cases.
