### ISSUE TITLE
MD error with FESetup output

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#36]
Running MD simulations from minimised and equilibrated FESetup output crashes using sander from amber2018. 

The error zip file is attached. 
The code that lead to the error is:
```
import BioSimSpace as BSS
system = BSS.IO.readMolecules(['FESetup2/_complexes/cats:CatS_155/solvated.rst7', 'FESetup2/_complexes/cats:CatS_155/solvated.parm7'])
protocol = BSS.Protocol.Production(runtime=20*BSS.Units.Time.nanosecond, frames=1000)
process = BSS.MD.run(system, protocol)
print(process.isError())
process.getOutput()

```
[md.zip](https://github.com/michellab/BioSimSpace/files/2501778/md.zip)

**Comment by lohedges** [comment]
Do you have the unmodified FESetup output files (rather than the ones written by BioSImSpace). If those don't run, then it's an issue with the configurations, rather than BioSImSpace (although we might be able to modify the protocol to help). I usually see crashes like this when the system hasn't been minimised correctly.

**Comment by lohedges** [comment]
For reference, sander can't even perform a miminisation using these input files (at least with SHAKE on, which is what I was told we want to use).

**Comment by lohedges** [comment]
It looks like the original configuration is a bunch of junk (I don't know what FESetup uses for minimisation/equilibration). If I disable SHAKE and re-minimise the system using BioSimSpace, then production MD runs just fine.

**Comment by skfegan** [comment]
If FESetup is doing minimization/equilibration its default is to use amber16/sander although you can use other programs if you specify the mdengine in the input file. However, for each of the three categories of molecules (ligand, protein, and complex) the minimization/equilibration must be set separately, i.e. if you minimize/equilibrate the ligand or protein it does not automatically minimize/equilibrate the complex. fesetup/_complexes/*/solvated.rst is the input for minimization not the result.

**Comment by lohedges** [comment]
Thanks for the clear explanation of the protocol, that's interesting.

Sorry for any confusion, I wasn't trying to imply that you can just minimise with BioSimSpace and be good to go, only that minimisation fixes whatever steric clashes are left after the FESetup step. I just wanted to do the simplest thing to see if I could then run _any_ protocol using the re-minimised system (since the FESetup configurations crashed within the first few iterations).

**Comment by lohedges** [comment]
If I am reading the above correctly, it sounds like we can't rely on SOMD, i.e. OpenMM, to correctly minimise or equilibrate the system. At the moment I'm making using of the minimisation and equilibration options in SOMD during my free energy simulations, since it is currently the only MD engine that can run dynamics with a system containing perturbed molecules.

For the purposes of the D3R challenge I could hack the other engines to write atom properties at lambda = 0, then copy the updated coordinates back into the original system following minimisation/equilibration, but this would take a bit of work. (I discussed something like this with Christopher last week.)

**Comment by lohedges** [comment]
Great, this is pretty much what I'm doing anyway. It sounds like I'll need to add another keyword option to my protocols to all the restraint of all non-solvent atoms. I'll also need to deal with writing input files for the lambda=0 state (using the property map) then just re-adding the updated solvent coordinates back into the original system.
