### ISSUE TITLE
Add extra arguments to some functions

### ISSUE THREAD

**Issue by cespos** [michellab/BioSimSpace#372]
Hi! 
If possible, it would be helpful to have some extra arguments in "wrapper" functions.
For example, while the Process functions `BioSimSpace.Process.Amber(), 
BioSimSpace.Process.Gromacs(), 
BioSimSpace.Process.OpenMM(), 
[...]`
support the arguments `name, work_dir, seed,...`, the function BioSimSpace.Process.createProcess() does not.

Similarly, while the Parameters functions `BioSimSpace.Parameters.ff14SB(), BioSimSpace.Parameters.ff99SB(), [...]` support the argument `leap_commands`, the function `BioSimSpace.Parameters.parameterise` does not. Although not all Parameters functions have this argument, it would still be useful to have it. Maybe here a possible solution would simply be to add a **kwargs argument
`BioSimSpace.Parameters.parameterise(**kwargs)`.

And, sorry, just one extra request...
would it be possible to add the `restart` argument to `Protocol.Equilibration()`?

Many thanks!
Carmen

**Comment by lohedges** [comment]
Thanks, yes those should all be possible. The extra arguments are missing from some of the wrapper functions only because they were written before the full functionality was fleshed out.

With regards to the restart option: This is something that we are planning to do, only it turns out to be quite tricky to implement in an interoperable way, particularly with regards to equilibration protocols where the temperature isn't constant. When using `BioSImSpace.Process.Gromacs` we allow the user to pass a _checkpoint_ file using the `checkpoint_file` option. This only currently only supports equilibration protocols, allowing a simulation to pick up where it left off.

Cheers.

**Comment by cespos** [comment]
@lohedges Great to hear that you are already working on these points!
I will check for future updates.

Many thanks

**Comment by lohedges** [comment]
These functions now except `**kwargs`. Let me know if there are others places where this would be useful.
