### ISSUE TITLE
'BioSimSpace._SireWrappers.System' can only contain unique molecules.

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#386]
Dear BioSimSpace developers,
I'd like to merge the ligand and protein, but the following error occurred, what should I do? 
```
  File "/data/miniconda3/envs/biosimspace-github/lib/python3.9/site-packages/BioSimSpace/_SireWrappers/_system.py", line 167, in __add__
    system.addMolecules(other)
  File "/data/miniconda3/envs/biosimspace-github/lib/python3.9/site-packages/BioSimSpace/_SireWrappers/_system.py", line 441, in addMolecules
    raise ValueError("'BioSimSpace._SireWrappers.System' can only "
ValueError: 'BioSimSpace._SireWrappers.System' can only contain unique molecules. Use the 'copy' method of 'BioSimSpace._SireWrappers' objects to create a new version of them.
```

Code to reproduce, I run script 1 and then run script 2: 

Script 1: 
```python
import pickle
import BioSimSpace as BSS

pro = BSS.IO.readMolecules(['protein.prmtop', 'protein.inpcrd'])
with open('pro.pkl', 'wb') as f:
    pickle.dump(pro, f)
```

Script 2:
```python
import pickle
import BioSimSpace as BSS
morph = BSS.IO.readPerturbableSystem('morph0.prm7', 'morph0.rst7', 'morph1.prm7', 'morph1.rst7')
with open('pro.pkl', 'rb') as f:
    pro = pickle.load(f)

print(morph + pro)
```

Input files: 
[temp.zip](https://github.com/michellab/BioSimSpace/files/9656874/temp.zip)

Thanks!

**Comment by kexul** [comment]
This error occurs in both the 2022 and 2023 versions.

**Comment by lohedges** [comment]
I've not had a chance to test, but assume the error is occurring since the objects have the same `MolNum`. To get a unique number, you could create a copy of one, e.g.

```python
print(morph + pro.copy())
```

I guess the issue here is that `MolNum` identifiers are unique to a Sire session, so there can be a clash if you pickle/unpickle and object. I think we will need to implement a copy of unpickling, or similar, although this could lead to other issues.

**Comment by kexul** [comment]
Hi @lohedges , many thanks for your quick reply! 

I've tried using the `.copy()` function, but the `MolNum` remains unchanged. 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/5920217/192576632-c4229a09-ccce-47f9-a4db-26357f4760fd.png">

**Comment by kexul** [comment]
Thanks, `pro[0].copy()` works! 🎉 🎉

**Comment by lohedges** [comment]
Great. I'll update the `System` copy method to copy each of the molecules in it, then recombine them.

**Comment by lohedges** [comment]
Just a quick update on this, since we might need to have a rethink on how we constrain and compare molecules in BioSimSpace. In Sire, there is the concept of a molecule _number_ and _version_. This means you can have different versions of the same molecule number, i.e. if you edit it. The combined version _and_ number is guaranteed to be unique.

For BioSimSpace, I have needed to place some additional restrictions on molecule (and residue and atom) numbering within a System due to the requirements of SOMD, i.e. it assumes unique and ascending numbering, even though this isn't a requirement of SIre itself. For example, SOMD completely re-orders the atoms in a system on load, so we need to use some unique identifiers, e.g. atom number, to re-map updated coordinates from a trajectory file.

For the above, doing a `.copy()` doesn't really make sense in terms of the behaviour of Sire, so we are thinking of changing this to `.renumber()`. We had discussed implicitly doing this on unpickling, but this could cause other issues, e.g. if you wanted to unpickle a System and Molecule, then check that the Molecule was in the System.

When we eventually re-write SOMD I will make sure that it is designed in a way that doesn't require invalid assumptions about a Sire system. This will hopefully avoid issues like this.

Just to note that we realised that your issue could also be resolved by changing the order of the read and pickle in your second script, i.e. if you unpickle first, then load the perturbable system, i.e.:

```python
import pickle
import BioSimSpace as BSS
with open('pro.pkl', 'rb') as f:
    pro = pickle.load(f)
morph = BSS.IO.readPerturbableSystem('morph0.prm7', 'morph0.rst7', 'morph1.prm7', 'morph1.rst7')
print(morph + pro)
```

This is because the molecule in morph is correctly assigned a unique number on read.

**Comment by kexul** [comment]
Thank @lohedges  for the detailed information 🤗 

> Just to note that we realised that your issue could also be resolved by changing the order of the read and pickle in your second script, i.e. if you unpickle first, then load the perturbable system, i.e.:

Thanks! that's good to know.
