### ISSUE TITLE
nglview

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#4]
I am still struggling to get nglview to work for me, as in nothing actually gets displayed. 

Using: Safari Version 11.0.3 (13604.5.6)
OSX 10.13.3
nglview version: '1.1.2'

I followed the instruction in the readme, but no molecule gets displayed. @chryswoods I know you have it working for you. Could you summarise versions you are using? Thanks!

**Comment by lohedges** [comment]
Hi Toni, this is what I get doing `$HOME/sire.app/bin/pip show package`:

nglview: 1.0
numpy: 1.14.0
ipywidgets: 7.1.1
ipykernel: 4.8.0
jupyter: 1.0.0

(NGLview only requires `ipywidgets` and `numpy`, but I've see reports regarding issues with certain versions of `ipywidgets`.)

It looks like you are using a more recent version of nglview which was pushed to pip a few weeks ago. I'll see if that version works for me too. (That said, I'm sure you were using the same version as me when we failed getting it to work in Nottingham.)

Just to make sure: you are running the `nglview_patch.sh` script in the demos directory? This fixed the empty display problem for me since there was an issue with handling binary data streams.

**Comment by lohedges** [comment]
Hello again,

I've just upgraded all of my pip packages and the molecule viewer still works. One thing I spotted is that someone has fixed the binary data stream issue, so the viewer now works for me without needing the patch script. (They have added a conditional check for binary data.)

It could be possible that the patch has actually broken a working nglview installation, so perhaps try reinstalling it.

Cheers.

**Comment by ppxasjsm** [comment]
The patch changes a  line from 'rb' to 'b' right?

I just tried to fix that manually.

**Comment by lohedges** [comment]
No, it changes 'rb' to 'r', but it shouldn't be needed with the version of nglview that you have since they have fixed the issue.

**Comment by ppxasjsm** [comment]
I am just doing a clean install to see if it works.

**Comment by ppxasjsm** [comment]
I did a clean install of Sire and BioSimSpace into sire with the latest version on github. the 'rb' and 'r' bit seems to look fine code wise, but still the problem of no display persists following your instructions.

**Comment by ppxasjsm** [comment]
I have tried with Chrome. Same problem. I have been searching online. I may post something on the NGL git page. 

I tried to just go back to nglviews examples. See this:
![screen shot 2018-03-26 at 16 07 19](https://user-images.githubusercontent.com/3668316/37914751-d6c8a978-310f-11e8-9c00-49af8b3b4cac.png)

i should be able to see the protein structure if I do something like that I assume. Doesn't seem to work for me.

**Comment by ppxasjsm** [comment]
Then I get the gui, whithout the molecule shown. As in what I get when just running the bits in the amber notebook.

**Comment by lohedges** [comment]
Okay, that's what I expected.

This issue has been mostly tracked [here](https://github.com/arose/nglview/issues/726). Might be worth adding to the discussion there, or seeing if there's anything in the comments that we've not tried.

**Comment by ppxasjsm** [comment]
Can you try one thing? Print these for me?

`
import traitlets, ipywidgets, notebook, numpy, nglview, ipykernel
print(traitlets.__version__, ipywidgets.__version__, notebook.__version__, numpy.__version__, ipykernel.__version__)
`

**Comment by hainm** [comment]
@ppxasjsm  what does the web console say? 

(In Chrome: right click -> Inspect -> Console)

You might want to try: https://github.com/arose/nglview/issues/718#issuecomment-346041897

**Comment by lohedges** [comment]
I'll close this for now since it seems to be a problem with NGLView rather than BioSimSpace. Feel free to add another comment if you discover a solution. This will help us when deciding the best way of bundling the various python dependencies, e.g. if the conda version of a package works, but the pip one doesn't.
