### ISSUE TITLE
Would it be possible to include HiMap as an alternative to LoMap in the generateNetwork method?

### ISSUE THREAD

**Issue by DreamCykl** [michellab/biosimspace#409]
**Is your feature request related to a problem? Please describe.**
No, however more efficient FEP calculations could be run using more optimal pertubation networks.  [HiMap](https://chemrxiv.org/engage/chemrxiv/article-details/63894b1f836ceb6cd16f7987) claims to achieve this and looks like a very useful successor to LoMap.

**Describe the solution you'd like**
Include an option to run HiMap as a network generation tool as oppose to LoMap

**Describe alternatives you've considered**
Of course this could be run independently of BSS but including it as a built-in feature could be useful!

**Comment by lohedges** [comment]
Hello there,

Thanks for your question. At present we would be unable to support the code since it isn't available as a conda package. Our code is based on  [lomap2](https://anaconda.org/search?q=lomap2), which is being maintained by the OpenFE team [here](https://github.com/OpenFreeEnergy/Lomap). (They took over the old code, modernised parts of it, etc.) The [himap code](https://github.com/MobleyLab/HiMap) appears to vendor a version of `lomap`. It is not clear to me whether this is the _same_ as the OpenFE version, or whether it is a specific version required to use `himap`. In any case, this approach would break our packaging and isn't desirable.

That said, I'm sure that we would be able to support `himap` in future as the package becomes more mature. (For example, I don't know if the OpenFE team plan to adopt this too?) If it proves useful, we could also write conditional wrappers for it, i.e. don't include it as a hard dependency but expose functionality when we detect that it is installed.

Cheers.

**Comment by DreamCykl** [comment]
Hey,

Okay that makes sense. I will keep an eye out to see how things develop! I think HiMap just uses the core functionality of LoMap to read in molecules and then create a similarity matrix with scores. HiMap then does all the fancy stuff in terms of clustering and optimizing FEP networks, so I would guess that any version of LoMap would interface with HiMap successfully, although I have no evidence to back up this claim.

Thanks
