### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jasmin-guven** [michellab/biosimspace#425]
Hi, 

I'm trying to run FEP with a ligand set from [here](https://pubs.acs.org/doi/10.1021/acs.jmedchem.9b00728). 

Everything seems fine for almost all my edges, except those containing ligand 11 (attached `ligand.sdf` file).  It looks like when I use `BSS.Align.merge()`, the phosphonate group of the ligand (common to all ligands) gets assigned dummy atoms. 

I've attached a screenshot of VMD for the ligand 11 -> ligand 5 transformation:
![Screenshot from 2023-03-28 14-22-24](https://user-images.githubusercontent.com/57833295/228252156-f5c64dc7-e05f-4f40-98f2-15b85d58e5fa.png)

I've also attached all the other ligands which are transformed with ligand 11 here, for reference.  

I checked all the other transformations, and there I do not get the issue of the phosphonate group being assigned dummy atoms. 

Context:
 - OS: Linux (Ubuntu 22.04),
 - Version of Python: 3.9.16
 - Version of BioSimSpace: 2023.1.1+34.g0a6d34f1 
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

Is there something I might be doing wrong with my input files or something else I'm missing? 

Thanks a lot in advance!

**Comment by lohedges** [comment]
Thanks for reporting. I can't see the attachment containing the ligands. Were you meant to attach, or are they available from the paper link?

**Comment by jasmin-guven** [comment]
Hi Lester, Sorry I forgot to attach the zip file... 
[issue.tar.gz](https://github.com/michellab/BioSimSpace/files/11090473/issue.tar.gz)

**Comment by jmichel80** [comment]
hi @jasmin-guven , can you also share the BSS script you used to generate a merged molecule so we can check the syntax used to generate atom mappings ? 
It would be good to use https://github.com/OpenBioSim/biosimspace/issues for reporting future issues

**Comment by lohedges** [comment]
I can't even parameterise the ligands using both GAFF or OpenFF, so can't perform the merge from the SDF files alone. That said, I've checked the mappings manually and all involving ligand11 include the `P` element in the mapping, e.g. mapping atom index 15 in ligand11 to atom index 16 in ligand5 and ligand4.

```python
mapping_11_5
Out[23]:
{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 6: 6,
 7: 7,
 8: 8,
 9: 9,
 10: 11,
 11: 12,
 12: 13,
 13: 14,
 14: 15,
 15: 16,
 16: 18,
 17: 19,
 18: 22,
 19: 23,
 20: 24,
 21: 25,
 22: 26,
 23: 10}
```

```python
mapping_11_4
Out[24]:
{0: 1,
 1: 2,
 2: 3,
 3: 4,
 4: 5,
 5: 6,
 6: 7,
 7: 8,
 8: 9,
 9: 10,
 10: 11,
 11: 12,
 12: 13,
 13: 14,
 14: 15,
 15: 16,
 16: 20,
 17: 21,
 18: 22,
 19: 23,
 20: 24,
 21: 25,
 22: 0,
 23: 26}
```

**Comment by jasmin-guven** [comment]
> hi @jasmin-guven , can you also share the BSS script you used to generate a merged molecule so we can check the syntax used to generate atom mappings ? It would be good to use https://github.com/OpenBioSim/biosimspace/issues for reporting future issues


Hi @jmichel80,
Here's my code: 
https://github.com/meyresearch/metalloenzymes/blob/main/scripts/prepafe.py 

And sorry, will report these in the above repo in the future!

**Comment by lohedges** [comment]
No problem. Could you share the equlibrated prm/rst files for the ligands as well so that I can try to merge. It may be that the mapping is fine with the original SDF file, but is failing for the topology loaded from AMBER format. We now have a direct RDKit conversion, which should make things like this more robust.

**Comment by jasmin-guven** [comment]
Hi, @lohedges
Here are equilibrated prm7 and rst7 files for ligand 11 and ligand 3, 4, 12 and 14. 

[ligand_3.zip](https://github.com/michellab/BioSimSpace/files/11090710/ligand_3.zip)
[ligand_11.zip](https://github.com/michellab/BioSimSpace/files/11090682/ligand_11.zip)
[ligand_4.zip](https://github.com/michellab/BioSimSpace/files/11090716/ligand_4.zip)
[ligand_14.zip](https://github.com/michellab/BioSimSpace/files/11090726/ligand_14.zip)
[ligand_12.zip](https://github.com/michellab/BioSimSpace/files/11090723/ligand_12.zip)
[ligand_5.zip](https://github.com/michellab/BioSimSpace/files/11090742/ligand_5.zip)

Thanks!

**Comment by lohedges** [comment]
Hi again. I've tested locally and with the latest BioSimSpace from OpenBioSim I get the same mapping using either the SDF input _or_ the PR7/RST7 AMBER files, which doesn't have dummies for the phosphonate group.  I would expect this to be the case since we now use the native Sire to RDKit conversion behind the scenes, which has some tools to recover stereochemistry.

Prior to this addition, conversion to RDKit format went via an intermediate file format, so information could be lost depending on the format used. If molecules were loaded from SDF, then we would try use that format as the intermediate in order to preserve stereochemistry. (Which assumes that the original SDF file was well formatted.) If it wasn't loaded from SDF, then we go via PDB format and hope that RDKit can recover missing information during sanitisation. In your script you are performing the merge using the ligands loaded from AMBER format files, not the original SDFs, so are going via PDB format. I can only assume that some of the ligands aren't being loaded into RDKit in an optimal way, hence the strange MCS mappings. (Perhaps the equilibrated coordinates are sub-optimal, or some stereochemistry is lost.)

I'd advise the following:

1) Try with the current BioSimSpace from OpenBioSim:

```
mamba create -n openbiosim -c conda-forge -c openbiosim/label/dev biosimspace ambertools gromacs
mamba activate openbiosim
```

(You can replace `mamba` with `conda` if you don't use it.)

2) Try changing your script to load the SDF ligands to perform the MCS mappings.

**Comment by lohedges** [comment]
For reference, this is what I see using your AMBER files with the latest code:

![lig_11_5](https://user-images.githubusercontent.com/648557/228479284-881ccf69-ac27-4f98-b25c-41380127d97c.png)

The two phosphonate groups map onto each other. The only things that don't map are:

1) A hydrogen attached to atom index 10 in ligand11 becomes a dummy in the lambda = 1 end state.
2) Three hydrogens attached to atom index 10 in ligand5 become dummies in the lambda = 0 end state.

**Comment by jasmin-guven** [comment]
Hi Lester, 

Sorry for my delayed response. 

I tried equilibrating the systems again and now it seems I don't get weird mappings. I also installed openbiosimspace, but was met with other errors along my workflow (which I will try to raise issues for on the correct site, if they persist). 

If I get this error again, I will probably try using the SDF files to set up the mappings, unless I get my openbiosimspace to work. 

Thanks again for helping, I will close this issue now.
