### ISSUE TITLE
Latest devel does not run setup demo

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#50]
I am trying to run a slightly modified version of: https://github.com/michellab/BioSimSpace/blob/devel/demo/molecular_setup.ipynb

This is run on a fresh devel_latest binary. 
The input molecule used is attached. 

The following line:
```python
system = BSS.Solvent.solvate(node.getInput("water"), molecule=molecule,
                                                     box=3 * [node.getInput("box_size")],
                                                     ion_conc=node.getInput("ion_conc"))
```
Generates the following error:
```bash 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-a6abde39c84c> in <module>
      1 system = BSS.Solvent.solvate(node.getInput("water"), molecule=molecule,
      2                                                      box=3 * [node.getInput("box_size")],
----> 3                                                      ion_conc=node.getInput("ion_conc"))

~/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2018.1.1+712.g23cf502-py3.7.egg/BioSimSpace/Solvent/_solvent.py in solvate(model, molecule, box, shell, ion_conc, is_neutral, work_dir, property_map)
     97             raise ValueError("Supported water models are: %s" % waterModels())
     98 
---> 99     return _model_dict[model](molecule, box, shell, ion_conc, is_neutral, work_dir, property_map)
    100 
    101 def spc(molecule=None, box=None, shell=None, ion_conc=0,

~/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2018.1.1+712.g23cf502-py3.7.egg/BioSimSpace/Solvent/_solvent.py in tip3p(molecule, box, shell, ion_conc, is_neutral, work_dir, property_map)
    246     # Create the solvated system.
    247     return _solvate(molecule, box, shell, "tip3p", 3, ion_conc,
--> 248             is_neutral, work_dir=work_dir, property_map=property_map)
    249 
    250 def tip4p(molecule=None, box=None, shell=None, ion_conc=0,

~/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2018.1.1+712.g23cf502-py3.7.egg/BioSimSpace/Solvent/_solvent.py in _solvate(molecule, box, shell, model, num_point, ion_conc, is_neutral, work_dir, property_map)
    655 
    656                 # Add the space property from the water system.
--> 657                 system._sire_system.setProperty(prop, water._sire_system.property(prop))
    658         else:
    659             system = water

AttributeError: 'list' object has no attribute '_sire_system'
```
[2-cyclopentanylindole.txt](https://github.com/michellab/BioSimSpace/files/2894675/2-cyclopentanylindole.txt)

**Comment by lohedges** [comment]
This is now fixed. The problem was introduced when closing issue #46, i.e. adding a molecule to a list of molecules now extends the list, rather than creating a System object. (Previously, any multi-molecule data structure was converted to a System.) I've updated [`_solvent.py`](https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/Solvent/_solvent.py) to reflect the changes.

I'll also have to update the [`binding_freenrg.py`](https://github.com/michellab/D3R2018/blob/master/CatS/BSS/binding_freenrg.py) script used for the D3R2018 challenge as it will no longer work, i.e. the line...

```python
system = merged + protein + waters
```

...will no longer create a system, but a list of molecules instead. We'll probably need to rethink this, as there is currently no way for the user to create a system from a list of molecules. (The `System` object is deliberately hidden from the user and is only used internally.)

**Comment by ppxasjsm** [comment]
Thank you!

**Comment by lohedges** [comment]
No problem.

To get around the other issue I'll create a `MoleculeList` object that is subclassed from a regular Python list. I can then add a `toSystem` method that converts the `MoleculeList` to a system. Just noting here so I don't forget :-)
