### ISSUE TITLE
Scope for supporting non-orthorhombic periodic boxes

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#54]
Another limitation is that currently conversions between file format is limited to cuboid boxes. CHARMM and GROMACS support a wider variety of PBCs.

Adding support for a broader range of PBCs in Sire could be one solution. I suspect this would help supporting a lot of GROMACS use cases since many protein simulations with this code use a dodecahedral box.

**Comment by chryswoods** [comment]
I agree. All periodic boxes can be described via three cell vectors as a triclinic box. Writing a triclinic box space class for reading and writing to files is very trivial (just read and save the three cell vectors into a TriclinicBox class that inherits from Space). Writing the code to calculated distances in this TriclinicSpace is more difficult, but not necessary for BioSimSpace. It would only be needed if we wanted to run MC or MD simulations in Sire/somd themselves. For now, a simple read/write TriclinicBox is all we need.

**Comment by chryswoods** [comment]
Check the link here - https://hoomd-blue.readthedocs.io/en/stable/box.html

**Comment by jmichel80** [comment]
Yes a simple read/write is easy but we have to be careful about conversion operations in BioSimSpace that manipulate coordinates (e.g. to fix treatment of solvent molecules as in 
https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireIO/watermodel.cpp )

**Comment by lohedges** [comment]
Agreed, it should be easy enough to add support for reading/writing. With regards to the water topology conversion: only the naming of the atoms in the water template is changed, the coordinates are preserved. The only issue would be conversion from a three-point model to a 4- or 5-point, since the calculation of the virtual site positions would need to take account of the periodic boundary condition (although most programs fix this at start up anyway).

Since we use `gmx solvate`, we could also add options to `BioSimSpace.Solvent` to allow the creation of more exotic periodic boxes. However, this would limit the scope of file formats to which the system could be written, so would limit interoperability. (This would be fine if the user specifically wanted to use a particular package, e.g. Gromacs.)

**Comment by chryswoods** [comment]
I think we should support everything that gmx supports. Nearly all MD packages support triclinic boxes (I think). We could add it as an extra feature test for an MD code, so that we don't choose to use it if the user wants a very exotic box.

**Comment by lohedges** [comment]
Closing as issue is being covered [here](https://github.com/michellab/BioSimSpace/issues/155).
