### ISSUE TITLE
Bonding parameters for water missing in parm7: this may be related to issue #52

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#60]
As stated in issue #52 there is a problem converting directly between gromacs and amber. However, I also seem to be running into this problem when running a simple solvation minimisation workflow. 

I have generated a set of parameters with tleap directly using ff99sbildn (because it wasn't supported by BSS).

If I then run the following:
```python
import BioSimSpace as BSS
mol = BSS.IO.readMolecules(['leap.crd', 'leap.top'])
system = BSS.Solvent.solvate("tip3p", molecule=mol,
                                      box=3*[4*BSS.Units.Length.nanometer])
protocol = BSS.Protocol.Minimisation(2000)
## This will be run with gromacs by defaul
process = BSS.MD.run(system, protocol, name="minimise")
minimised = process.getSystem()
## Amber parameters written now do not have bonding information for the water molecules
# however in this case we are going from an internal representation.
BSS.IO.saveMolecules('minimised', minimised,['PRM7','RST7', 'PDB'])
```
The Amber files are now save do not contain bonding information for the water. This is also obvious in a VMD representation:
![water_bad](https://user-images.githubusercontent.com/3668316/53636658-e166c080-3c18-11e9-9f1f-5a86897e0a92.png)

Carrying on with Gromacs everything works fine. Carrying on with Amber a second minimisation with Amber will fail, so will an equilibration. This is because there is no bonding information of the water molecules in the parm7 file. 

All input and scripts are attached. 
[biosimfail.zip](https://github.com/michellab/BioSimSpace/files/2919291/biosimfail.zip)

**Comment by ppxasjsm** [comment]
I am using amber 18 and GROMACS version:    2018.2

**Comment by lohedges** [comment]
Yes, it's exactly the same as the other issue. BioSimSpace only converts the water model topology where it needs to internally, e.g. for running SOMD simulations. If you want to do it yourself then you'll need to use something like the example in the other issue [thread](#52).

The problem occurs because, although you originally load AMBER files, these are converted to GROMACS format for the solvation stage. When they are loaded back in the explicit hydrogen-hydrogen bonding information is lost.

This is one of the major problems with converting between AMBER and GROMACS format and we need to discuss whether it's something that needs to be be added to the parsers themselves.

**Comment by ppxasjsm** [comment]
Cool I thought so. What I don't understand then how can I actually get anything setup. If I solvate with Gromacs it will automatically minimise with Gromacs and I can't actually get to a working AMBER file  version?
So before doing a write out of AMBER I would simply add this:
```python
waters = setAmberWater(system._sire_system.search("water"), "tip3p")
```

**Comment by ppxasjsm** [comment]
Could this be why nothing equilibrated with D3R?

**Comment by lohedges** [comment]
Yes, that's right. I'll discuss whether we should convert the water topologies before writing the files. Normally we don't monkey with the system, e.g. molecule naming, behing the user's back but this is a case where vital information is clearly not preserved during file translation. One problem is that, unless the system is solvated with BioSimSpace (where we know the exact solvent model), it might be tricky to detect the model manually. Ideally GROMACS would actually put the information in the topology file, rather than setting the rigid water bonding as a configuration parameter.

No, this wasn't the equilibration problem with D3R. I tested by solvating the system with tLEaP.

I'll see if I can modify the solvation stage within BioSimSpace so that bonding information is preserved there.

**Comment by lohedges** [comment]
Actually, looking at your script more closely you can see that the bonding information is lost when reading the GROMACS files written during the minimisation simulation. BioSimSpace correctly loads a bonded water topology during the solvation stage (by setting `#define FLEXIBLE 1` in the topology file and the bonds are preserved if writing to AMBER format.

```python
import BioSimSpace as BSS
mol = BSS.IO.readMolecules(['leap.crd', 'leap.top'])
system = BSS.Solvent.solvate("tip3p", molecule=mol,
                                      box=3*[4*BSS.Units.Length.nanometer])
system.getWaterMolecules()[0]._sire_molecule.property("bond")
```

prints

```python
TwoAtomFunctions( nFunctions() == 2 )
```

The files written by GROMACS during the minimisation don't contain `#define FLEXIBLE 1` in the topology, so Sire doesn't read the bonds. Perhaps I should update the GROMACS parser so that it always sets this option, or allow it to be passed in the property map.

**Comment by lohedges** [comment]
This should now be fixed since the `getSystem` method of `BioSimSpace.Process.Gromacs` always copies the coordinates back into the original system. This ensures that we preserve the original water topology, regardless of what is written to the restart file by GROMACS.
