### ISSUE TITLE
a Bioconda package would be great

### ISSUE THREAD

**Issue by bgruening** [michellab/BioSimSpace#63]
It would be great if BIoSimSpace would be available from [Bioconda](https://bioconda.github.io/). Please let me know if this is interesting for you and you need help.

**Comment by lohedges** [comment]
Thanks for your interest. We are close to having a working conda build for BioSimSpace. I'll be in touch if I have any questions.

**Comment by chryswoods** [comment]
Thanks for your interest and offer of help. We are getting close but any suggestions you have for documentation or step by step guides would be really helpful.

BioSimSpace is built on top of Sire, which is a C++ library exposed to python using Py++. This used to be a real pain to compile cross-platform, but now we have everything compiling using the conda compilers and linking to all dependencies (except one) which are installed and managed by conda. Everything sire-based is in a correct conda pkgs directory with libraries and custom executables copied into the main conda lib and bin directories. All binaries are built against old OS X or old glibc so that single binaries support most post 2011 operating systems. We believe all we need now is to tar up the libraries so that they can be unpacked as part of a conda install (so conda install sire would work). Then, as BioSimSpace is pure python, the existing setup.py can be used to help build the BioSimSpace conda package.

Does this sound about right? Do you have any advice?

**Comment by chryswoods** [comment]
(Recent pull requests and issues are us cleaning up the windows binaries - ideally conda install sire/BioSimSpace should work on OS X, Linux and Windows)

**Comment by bgruening** [comment]
> Does this sound about right? Do you have any advice?

This sounds perfect! Instead of Bioconda, maybe the channel for Sire should be https://conda-forge.org instead. They are also building for Windows.

Thanks for you positives answers!

**Comment by lohedges** [comment]
We're currently hosting on our own Conda channel [here](https://anaconda.org/michellab/biosimspace). This is to get around build restrictions on Conda-Forge. See the README for installation instructions.

**Comment by bgruening** [comment]
@lohedges thanks a lot!
Did you had any problem with conda-forge or bioconda? I'm happy to help.

**Comment by lohedges** [comment]
@miroslav351  Thanks. Unfortunately there are still several non-conda packages that are dependencies of BioSimSpace. Once you've done the conda install you'll need to do:

```bash
pip install fileupload pygtail pypdb
```

If you're using BioSimSpace via Jupyter, then you'll also likely need to activate the fileupload extension:

```bash
jupyter-nbextension install fileupload --py --sys-prefix 
jupyter-nbextension enable fileupload --py --sys-prefix
```

(Hopefully these dependencies will have conda packages at some point. I don't want to maintain them myself.)

**Comment by miroslav351** [comment]
@lohedges Ah, that sounds fair enough. Thanks for the useful info.

**Comment by lohedges** [comment]
@bgruening Since BioSimSpace is built on top of [Sire](https://github.com/michellab/Sire) we also needed to be able to create a Conda package for that too. Conda Forge only allow source builds we can't build Sire on their platform because of the dependency on OpenMM, which is part of the [Omnia](https://anaconda.org/omnia/repo) channel. (The Omnia team have ported pretty much all of their packages to Conda Forge, apart from OpenMM and anything that depends on it. This is because of GPU dependencies.) I'm not sure if this would be an issue with BioConda too.

The Sire build also takes several hours, so we didn't want to overburden their servers. Since we build a binary package from a vanilla miniconda environment during our Azure pipeline, it seemed sensible to strip out and package the compiled libraries, which can be unpacked within our conda recipe. Obviously this means that we're pinning to specific versions of dependencies, but the Sire build is pretty restrictive anyway so this would always be an issue.

Conda Forge also seemed reluctant about using labels for dev and release packages, even though this seems to be done by plenty of other packages, e.g. numpy. We have rolling builds from the devel branch on GitHub with are pushed with the label "dev". Tagged commits are pushed with the label "main".

**Comment by bgruening** [comment]
Don't be afraid of non-source builds. There are exceptions and yours sounds like a valid exception to me. The will be GPU support in conda-forge as one of the core-devs is working for NVidea now. But I would not wait for this and go for the binary version for now.

> Conda Forge also seemed reluctant about using labels for dev and release packages, even though this seems to be done by plenty of other packages, e.g. numpy. We have rolling builds from the devel branch on GitHub with are pushed with the label "dev". Tagged commits are pushed with the label "main".

That's true. The idea is to have a stable channel and focus on reproducibulity and dev releases can go to separate channels. This has practical reasons, like space, infrastructure burdon and keeping the search space manageable of the solver.

It would be great to have it in conda-forge or bioconda as a few workflow management systems only allow these two by default.

Thanks for all your effort!
