### ISSUE TITLE
prematch option to BSS.Align.matchAtoms not working

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#64]
It seems that the prematch option to findMCS fails to actually match the desired atoms with the following example where the user wishes to enforce mapping of the hydroxyl oxygen in moleculeB (index 4) onto a phenyl hydrogen in moleculeA (index 17). 

![image](https://user-images.githubusercontent.com/11722212/54062698-a0197680-41ff-11e9-829c-9681c91c75a0.png)

Using 
https://github.com/michellab/BioSimSpace/blob/devel/nodes/playground/prepareFEP.ipy

`~/sire.app/bin/python ~/software/devel/BioSimSpace/nodes/playground/prepareFEP.py --input1 molA.prm7 molA.rst7 --input2 molB-2.prm7 molB-2.rst7 --output AtoB-2 --prematch 17-4`

Gives as a merged molecule

![image](https://user-images.githubusercontent.com/11722212/54062787-30f05200-4200-11e9-9dc1-441a3d2440f3.png)

where the oxygen atom in molB-2 as been mapped onto the sulphur atom in molA. 

The desired merged molecule would have the methyl group bonded to the sulphur turned into dummy atoms, the sulphur turned into a hydrogen. the other hydrogen meta to the methyl group on the phenyl would turn into a oxygen, and a dummy atom would be bonded to the oxygen. 

The same output is obtained without setting the prematch option

`~/sire.app/bin/python ~/software/devel/BioSimSpace/nodes/playground/prepareFEP.py --input1 molA.prm7 molA.rst7 --input2 molB-2.prm7 molB-2.rst7 --output AtoB-2`

It is not surprising that without prematching the mapping matches the S atom with the O atom since this gives the largest MCS. However the purpose of prematching should be to allow generation of mappings with a smaller MCS (in the spirit of the manual matching option of FESetup). In this case this is desirable since the -SMe and -OH groups should be placed on two different sides of the benzyl ring. 

The input files can be downloaded here 
[input.zip](https://github.com/michellab/BioSimSpace/files/2947876/input.zip)

**Comment by lohedges** [comment]
Thanks, Julien. I'll take a look at this on Monday.

From my understanding, the Sire findMCSmatches should not return a match if
it doesn't include the pre-match. (Although it doesn't actually start from
the pre-match when searching.)

It's possible that I messed something up when adding the code to return
multiple matches. If you know what you're doing, you could see if calling
the original Sire findMCS function directly returns what you expect. (Look
at the code in the _align.py module to see how this is done.) If not, then
it looks like the Sire code isn't doing what is advertised.

Cheers.

**Comment by lohedges** [comment]
Actually, the logic is that the match should always include the pre-match,
i.e. if no match is found then the pre-match is returned because that is
what the user has stated is known to be true.

**Comment by chryswoods** [comment]
It sounds like the pre-match is not being passed correctly into the Sire findMCS code. This can happen if the atom selection does not select anything, or selects something you weren't expecting. You should debug by looking at what BioSimSpace is passing to the Sire findMCS code (the exact QHash<AtomIdx,AtomIdx> used for pre-matching) then re-enable the qDebug code in findMCS to get it to print out what it is doing. Absolutely, Sire cannot return a match that does not include the pre-match, as this code in SireMol/findmcs.cpp shows;

```c++
        BGL_FORALL_VERTICES_T(v0, g0, G0)
        {
            if (get(map01, v0) != graph_traits<G1>::null_vertex())
            {
                nmatch += 1;

                //count up the number of user-matched vertices
                if (user_matched_verts.contains(v0))
                    nuser += 1;
            }
        }

        //we must match all user-supplied vertices
        if (nuser >= user_matched_verts.count())
        {
            if (nmatch > *max_size)
            {
                //qint64 ns = t_delta->nsecsElapsed();
                t_delta->restart();
                *max_size = nmatch;
                best_matches->clear();
                //qDebug() << "nmatch ==" << nmatch << " " << *max_size;
                //qDebug() << "FOUND LARGER MATCH!";
                //qDebug() << (0.000001*ns) << " ms since last maximum match...";
            }    
```

(we count the number of user-matched-vertices that we have found, and can only progress to return this match if the number of found user-matched-vertices is greater or equal to the number of user-supplied user-matched-vertices).

As Lester points out, if we can't find a match that includes the prematch, then an empty match is returned.

**Comment by lohedges** [comment]
Calling the underlying findMCS routine directly always works as expected. However, calling findMCSmatches doesn't always work. For some reason, matches that don't include the prematch are sometimes included in the list of possible matches, so the best match might not contain the prematch once they have been scored and sorted.

I'm not quite sure why this is, since the list of best batches is accumulated inside the if condition Christopher shows above. I'll try to track down the bug.

**Comment by lohedges** [comment]
Actually, scratch the above. The behaviour is inconsistent for both and I'm getting different behaviour depending on the number of input arguments that I'm giving the functions (using defaults). Something fishy is going on somewhere!

**Comment by lohedges** [comment]
I've fixed the bug. There was an issue in the original findMCS code from Sire within the conditional check for valid matches that let through invalid matches if the number of user supplied vertices was zero. See [here](https://github.com/michellab/Sire/commit/83db1fc3452b776f500328eff0da6108da7db935) for details. I've also cleaned up the findMCS and findMCSmatches API to fix a few minor issues with the overloaded methods. (This didn't affect BioSimSpace.)

@jmichel80: Having fixed the problem, I now come across another issue with your example script. When I force the requested prematch, the two ligands cannot be aligned based on the resulting mapping and BioSimSpace throws an error:

```sh
__EndTrace__
Exception 'SireError::program_bug' thrown by the thread 'master'.
Attempt to find the alignment matrix failed to produce a valid rotation matrix. Determinant should be 1. It is equal to 0.
Thrown from FILE: /home/lester/Code/Sire/corelib/src/libs/SireMaths/align.cpp, LINE: 508, FUNCTION: SireMaths::Matrix SireMaths::kabasch(const QVector<SireMaths::Vector>&, const QVector<SireMaths::Vector>&)
```
To get the mapping, I had to swap line 105 of your Python script with:

```python
mappings = BSS.Align.matchAtoms(lig1, lig2, matches=10, prematch=prematch, scoring_function="RMSD")
print(len(mappings[0]))
1
```

This means that we just use a basic RMSD scoring function, rather than first aligning the ligands based on the mapping and then computing the RMSD score. Looking at the mapping, I see that it contains only one entry, i.e. the original pre-match. This means that the MCS search timed out without finding any match containing the pre-match, so only the pre-match was returned. I increased the timeout to one minute and then it works.

```python
mappings = BSS.Align.matchAtoms(lig1, lig2, matches=10, timeout=BSS.Units.Time.minute, prematch=prematch)
```

However, you now get the following error:

```sh
Traceback (most recent call last):
  File "prepareFEP.py", line 115, in <module>
    lig2 = BSS.Align.rmsdAlign(lig2, lig1, mapping)
  File "/home/lester/Code/BioSimSpace/python/BioSimSpace/Align/_align.py", line 336, in rmsdAlign
    % (idx0, idx1, molecule0.nAtoms(), molecule1.nAtoms()))
ValueError: 'mapping' dictionary key:value pair 'AtomIdx(17) : AtomIdx(4)' is out of range! The molecules contain 16 and 19 atoms.
```

This is because you are aligning lig2 to lig1 based on the mapping from lig1 to lig2, i.e. you either need to align lig1 to lig2, or invert the mapping. I've fixed your notebook and Python script. Can you check that they now do what is expected?

I've updated the error handling in the `BioSimSpace.Align` package to throw sensible exceptions when things go wrong.

(Note that we still need to speed up the MCS routine as it's far too slow. This is partly because BioSimSpace does two types of mapping: one without heavy to light atom matching, and one with. These are currently done in serial. However, it is the main MCS routine that is the main bottleneck.)

**Comment by lohedges** [comment]
Actually, this still isn't working as expected. Now you don't get a match unless you request a prematch. I've figured out the problem in the MCS code and I'm working on a fix.

The problem arises because of the way we do multiple matches, i.e. light excluded, heavy to light, etc, and the pre-match might not be valid for some of these matches, so the `user_match_vertices` set will be empty. (The set isn't populated.) There are a few edge cases we need to check for to make sure we always get the intended match.

**Comment by lohedges** [comment]
Now fixed. Corresponding Sire commit can be seen [here](https://github.com/michellab/Sire/commit/64b8c55145077138161f1661325e4f1e1ce10fc3).

**Comment by jmichel80** [comment]
Hi @lohedges 

I could get the example to work following your instructions. However I am concerned that RMSD is not as good scoring function as RMSDalign

Do you have more insights about why the SireMath code fails to align the two molecules? They do not seem particularly unusual.

__EndTrace__
Exception 'SireError::program_bug' thrown by the thread 'master'.
Attempt to find the alignment matrix failed to produce a valid rotation matrix. Determinant should be 1. It is equal to 0.
Thrown from FILE: /home/lester/Code/Sire/corelib/src/libs/SireMaths/align.cpp, LINE: 508, FUNCTION: SireMaths::Matrix SireMaths::kabasch(const QVector<SireMaths::Vector>&, const QVector<SireMaths::Vector>&)

**Comment by lohedges** [comment]
Yes, the RSMD scoring is not as good. That's why I wrote "RMSD align" and use it as the default.

I had forgotten to mention that some of the tweaks I mentioned above are no longer necessary following the fixes to the Sire code. (The timeout was a result of it not be able to match correctly.) I now get a match of 16 atom pairs (including the pre-match) with the following line:

```python
mappings = BSS.Align.matchAtoms(lig1, lig2, matches=10, prematch=prematch)
```

This is what you had originally (I think). It uses the default "RMSD align" scoring function and a timeout of 5 seconds. This works fine on my machine. I can align based on the mapping and the node runs to completion without error. Could you confirm that the same works for you?

With regards to the error. I have previously seen it when trying to align planar molecules. The problem occurs when one of the coordinate dimensions, e.g. z, is zero for all of the mapped atoms. This resulted in an error when trying to generate a valid rotation matrix for the alignment. I thought @chryswoods and I fixed the problem, but it's possible that there are other edge cases that trigger it.

**Comment by lohedges** [comment]
Looking at [this](https://github.com/michellab/Sire/commit/20679af34377e2b8595a81d3efae90970d74a7d9#diff-56e383ece62c650f7378c99a8f31e80e) commit message it looks like the fix only considers the z dimension. For your broken alignment, do you know if the x or y coordinates are all zero (or the same)?

If this continues to be a problem I suggest that we open an issue within Sire regarding the `Sire.Maths.align` function, since it is no longer a result of the pre-matching bug and is a little off topic.

Cheers.

**Comment by lohedges** [comment]
With the updated scoring functions the ligands now align based on the generated mapping. I will close this issue for now and we can open a Sire issue regarding the failing of `Sire.Maths.align` if we experience similar problems in the future.
