### ISSUE TITLE
system from nvt equilibration cannot be run with npt equilibration

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#69]
I ran a heating using NVT with gmx. I then try and get the system of the process and run and NPT equilibration but get an error that it cannot find an appropriate MD engine to run the next set of simulations. 

![Screenshot from 2019-03-15 11-46-37](https://user-images.githubusercontent.com/3668316/54429800-6f62a100-4719-11e9-9bca-26c2ea49182c.png)

**Comment by ppxasjsm** [comment]
Saving the system in gromacs format and reloading it works. The same issue happens when trying to go from an NPT equilibrated system to a production run.

**Comment by lohedges** [comment]
Hi Toni,

Thanks for this, it's an interesting one. The problem is that the `getSystem` method reads a trajectory file during an equilibration or production run and takes the most recent frame. The file format associated with the frame happens to be RST (rather than Gro87) which isn't linked with Gromacs in the MD driver. (For minimisation Gromacs writes a GRO file which is read by the Gro87 parser, so has the correct file association for Gromacs.)

I'll either updated the `BioSimSpace.MD` package so that "GroTop,RST" is a valid format for a Gromacs simulation, or convert the output of `getSystem` to Gromacs format before returning it (which might be slower).

**Comment by lohedges** [comment]
I've fixed this by preserving the original file association when loading from trajectory within the `BioSimSpace.Process.getSystem` method. Let me know if you still have issues.
