### ISSUE TITLE
Atom Mapping Error: Merge has changed the molecular connectivity

### ISSUE THREAD

**Issue by maxkuhn** [michellab/BioSimSpace#80]
Hi all,

I have successfully run some test cases using the new atom mapping functionality. However, when I tried to run the preparation on molecules 31<=>4 and 31<=>2 the following error message came up:

`"BioSimSpace._Exceptions._exceptions.IncompatibleError: Merge has changed the molecular connectivity! Check your atom mapping."`

I have checked the mappings several times and did not find any error. Could you run the preparation on those files and tell me at which stage of the mapping the error occurs?

The files can be found here: [mcl_test_cases.tar.gz](https://github.com/michellab/BioSimSpace/files/3108582/mcl_test_cases.tar.gz)
I have also added an example of a similar perturbation which does **not** give an error  (31<=>38).

The command to run the preparations is `~/sire.app.devel/bin/python ~/BioSimSpace/nodes/playground/prepareFEP.py --input1 parm7/mcl1_lig31.parm7 rst7/mcl1_lig31.rst7 --input2 parm7/mcl1_lig38.parm7 rst7/mcl1_lig38.rst7 --mapping maps/mcl1_lig31~mcl1_lig38.map --output test`

**Comment by ppxasjsm** [comment]
Will try it tomorrow.

**Comment by lohedges** [comment]
Unlike FESetup, BioSimSpace currently doesn't support mappings that open
rings, i.e. the number of bonds in the initial and final states must be the
same. We're currently thinking of ways to relax this constraint in a way
where we can still result detect issues caused by problematic mappings.

I'll check your merge tomorrow to see if this is the reason why you see the
error.

**Comment by maxkuhn** [comment]
All three test cases provided are indeed opening the ring.
You can see that the mapping from phenyl to tetralin works fine (31 <=> 38), but phenyl to indane does not (31 <=> 4). I do not know how the code works in detail, but I cannot see why the first perturbation was possible and the other was not.
So far I have used BioSimSpace to prepare five such perturbations (Phenyl <=> fused ring), which gave reasonable results in the free energy calculations.

**Comment by lohedges** [comment]
Thanks for the clear description and examples. I've taken a look and in both cases the exception is being triggered because the connectivity of the merged molecule in the lambda = 0 state is inconsistent with the ligand from which it was generated (the `input1` argument). This is because a connection that was part of a dihedral in the original ligand is now part of an angle, which can't be correct. (This is irrespective of any ring opening in the final state.)

BioSimSpace has some self-consistency checks during the merge, one of which is that the partial molecules at lambda = 0 and lambda = 1 correspond to the ligand1 and ligand2 inputs to the script, i.e. energies computed for the partial molecules agree with those of the original ligands. 

I'll take a closer look at your mapping to see if I can figure out why it's triggering this error.

**Comment by lohedges** [comment]
Looking more closely, the problem arises because of the ring growth around atoms H37 and H38 from the first ligand. Initially these are connected via a dihedral, whereas in the merged topology they are connected through an angle via the top-most carbon of the ring. See below, where the second ligand is represented as lines:

![snap](https://user-images.githubusercontent.com/648557/56674200-7fbf5180-66b1-11e9-9f6f-07b44a585db9.png)

(Note that I've used FKCombu to flexibly align the molecules so that they overlap nicely.)

As you say, your mapping is correct and this should lead to a valid perturbation. When developing the code we had issues with some initial mappings that resulted in partially overlapping rings. In this case, the connectivity constraint was a good way of throwing away a junk perturbation, but clearly there are cases where it should be relaxed.

I'll have a think of how best to relax the connectivity constraint for situations involving ring forming or breaking. I think the `Sire.Mol.Connectivity` object has an `inRing` method, so perhaps we could allow changes in connectivity that go from a dihedral to an angle (or vice-versa) and involve going to or from a ring. (Perhaps there are other valid transitions too.)

**Comment by chryswoods** [comment]
Yes, Connectivity has several robust and well-tested `inRing' functions

https://github.com/michellab/Sire/blob/31eeea936579b4335d8c32d0f9f4b5b1f6c9d967/corelib/src/libs/SireMol/connectivity.h#L137

These are used extensively as part of the code to perform intramolecular Monte Carlo moves, so are very quick. I agree that the best route forward is to relax the test if the type of connection (1-2, 1-3, 1-4) changes if the "inRing"ness of the pair of atoms change.

**Comment by maxkuhn** [comment]
Hi Lester,
thank you for looking into this. I agree that this constraint actually makes a lot of sense for "normal" perturbations.
I will gladly run some test cases once the changes have been implemented.

**Comment by lohedges** [comment]
Thanks. I'm away for the next couple of days so this will probably be
implemented early next week. I'll let you know when it's ready for testing.

**Comment by lohedges** [comment]
This is a little trickier than I thought, since hydrogens (or anything else) that are connected to a ring carbon are considered to be part of a ring. This means that the atom pair that change connection type from dihedral to angle are part of a ring in both end states, so the "inRing-ness" check doesn't work.

Perhaps there is another simple test that can robustly detect this type of perturbation.

**Comment by lohedges** [comment]
Also, if `inRing` is meant to check that atoms are part of the same ring, then it fails for a simple benzene molecule:

```python
import BioSimSpace as BSS
from Sire.Mol import AtomIdx, Connectivity

# Load the benzene molecule. (Assumes we're in the demo directory.)
mol = BSS.IO.readMolecules("molecules/benzene.pdb").getMolecules()[0]

# Create a connectivity object for the molecule.
conn = Connectivity(mol._sire_molecule)

# All atoms (6 carbons and 6 hydrogens) should be part of the same ring,
# regardless of what pair of atoms we choose to test.
for idx0 in range(0, mol.nAtoms()):
    for idx1 in range(idx0+1, mol.nAtoms()):
        if not conn.inRing(AtomIdx(idx0), AtomIdx(idx1)):
            print(conn.inRing(AtomIdx(idx0), AtomIdx(idx1)))
            print(mol._sire_molecule.atom(AtomIdx(idx0)),
                    mol._sire_molecule.atom(AtomIdx(idx1)))
            print()
```

This prints the following:

```bash
False
Atom( C : 1 ) Atom( H : 7 )

False
Atom( C : 2 ) Atom( H : 8 )

False
Atom( C : 3 ) Atom( H : 9 )

False
Atom( C : 4 ) Atom( H : 10 )

False
Atom( C : 5 ) Atom( H : 11 )

False
Atom( C : 6 ) Atom( H : 12 )
```

Looking at the atoms, `inRing` is returning False for a direct bond between a carbon and a hydrogen. Any other connection returns true, e.g. a carbon bonded to a hydrogen that is attached to a different carbon (where the connection passes through the ring.) Similarly, the connection between any two hydrogens returns True.

This seems a little confusing to me, since the `inRing` documentation states that:

```c++
inRing(...) method of Sire.Mol._Mol.Connectivity instance
    inRing( (ConnectivityBase)arg1, (AtomIdx)atom0, (AtomIdx)atom1) -> bool :
        This function returns whether or not the two passed atoms are part of
        the same ring

        C++ signature :
            bool inRing(SireMol::ConnectivityBase {lvalue},SireMol::AtomIdx,SireMol::AtomIdx)
``` 

which seems like it should return true regardless of the atom pair. Perhaps it actually means: "whether or not the two passed atoms are connected through a ring".

**Comment by lohedges** [comment]
The above occurs because the test for `inRing` is that there are more than one paths between two atoms. Direct bonds between a hydrogen and carbon in the benzene only have a single path because a path can't pass through the same atom twice, i.e. you don't count that you could go all the way round the ring and back.

To make sense to me I think the test should be updated to the following. First check whether there is more than one path between the pair. If yes, then the bond is part of a ring. If not, then check all bonds between each atom in the pair (the neighbouring atoms to which they are bonded). If any of these is in a ring, then the original bond must also be connected to the ring too.

Applying this to the benzene example: The carbon-hydrogen bond only has one path so fails the `inRing` test. However, checking the carbon with any of its neigbouring carbons will return True, so the original carbon-hydrogen bond is connected to the ring.

**Comment by lohedges** [comment]
This updated two atom `inRing` method fixes the problem:

```cpp
/** This function returns whether or not the two passed atoms are part of
    the same ring */
bool ConnectivityBase::inRing(AtomIdx atom0, AtomIdx atom1) const
{
    QList< QList<AtomIdx> > paths = findPaths(atom0, atom1);

    // If there is more than one path between the atoms then they must
    // be part of a ring.
    if (paths.count() > 1)
        return true;

    // However, since a path can't pass through the same atom twice we will
    // miss any terminal atoms that are connected to a ring, e.g. a hydrogen
    // connected to a carbon in a benzene ring. To fix this, we also check to
    // see if there is more than one path between any of the immediate
    // connections of each atom. If there are, then the original bond must also
    // be connected to the ring.
    else
    {
        // Check paths between connections for atom0.
        for (const auto &atom : this->connectionsTo(atom0))
        {
            QList< QList<AtomIdx> > paths = findPaths(atom0, atom);

            if (paths.count() > 1)
                return true;
        }

        // Check paths between connections for atom1.
        for (const auto &atom : this->connectionsTo(atom1))
        {
            QList< QList<AtomIdx> > paths = findPaths(atom1, atom);

            if (paths.count() > 1)
                return true;
        }

        // If we've made it this far, then the atoms are not part of the
        // same ring.
        return false;
    }
}
```

@chryswoods Let me know if this is the intended behaviour of `inRing` and I'll update Sire and also add a simple unit test using benzene. Perhaps there is a reason why these bonds are excluded, although it would be good to update the docstrings to make this clear, i.e. the atoms are "connected through a ring" ratner than being "part of the same ring"

**Comment by chryswoods** [comment]
The intended behaviour is whether the path between two atoms passes through a ring. So H1-...-H2 going through the carbons in a benzene ring are “inRing” as the pathway between then goes through a ring. This is needed as we split molecules into two parts for internal moves, and cannot split if the two atoms are connected by a pathway that goes through a ring. Yes, the documentation should make this more clear.

**Comment by chryswoods** [comment]
Similarly H1-C1 is not inRing as the bond between them is not in the ring

**Comment by lohedges** [comment]
Hi @maxkuhn, I've added some additional functionality to handle ring opening/closing perturbations. I've tested for the example ligands provided above and it appears to work as expected. You'll need to use the updated [prepareFEP.py](https://github.com/michellab/BioSimSpace/blob/devel/nodes/playground/prepareFEP.py) script, which adds an optional `allow_ring_breaking` option. You can run the script as follows:

```sh
~/sire.app.devel/bin/python ~/BioSimSpace/nodes/playground/prepareFEP.py --input1 parm7/mcl1_lig31.parm7 rst7/mcl1_lig31.rst7 --input2 parm7/mcl1_lig38.parm7 rst7/mcl1_lig38.rst7 --mapping maps/mcl1_lig31~mcl1_lig38.map --allow_ring_breaking --output test
```

Let me know if you have any questions, or run into any problems. Note that the update requires the latest version of Sire. Since I've already pushed the BioSimSpace changes to GitHub (since I'm about to go home) I'll need to rebuild later in order for the binary and Conda packages to work correctly (since they will be built against an outdated Sire). They should be available later this evening.

Cheers.

**Comment by maxkuhn** [comment]
Hi @lohedges, thanks for your effort! I will run some tests and give an update once they are finished.

**Comment by lohedges** [comment]
For reference: The 31 <=> 38 perturbation didn't trigger the exception since the equivalent hydrogen atoms are part of a dihedral in both end states. This is because the ring that is formed has six sides. For all the other transformations the ring had five sides, which causes the connectivity to change from dihedral to angle (4 to 3 atoms).

![snap](https://user-images.githubusercontent.com/648557/56959368-20e05900-6b45-11e9-9791-3f13d7411ab1.png)

**Comment by lohedges** [comment]
I've now improved the ring-breaking handling so the above perturbation would also be caught. I've also added some tests to validate the code.

**Comment by maxkuhn** [comment]
When I try to run a command like
`/data/max/devel/sire.app.devel_190430/bin/python /data/max/devel/BioSimSpace_190430/nodes/playground/prepareFEP.py --input1 ../../1-fesetup-noequil/_ligands/mcl1_lig31/solvated.parm7 ../../2-openmmequil/rst7_files/mcl1_lig31_equilibrated.rst7 --input2 ../../1-fesetup-noequil/_ligands/mcl1_lig2/solvated.parm7 ../../2-openmmequil/rst7_files/mcl1_lig2_equilibrated.rst7 --mapping maps/mcl1_lig31~mcl1_lig2.map  --allow_ring_breaking --output prepareFEP/mcl1_lig31~mcl1_lig2/solvated/mcl1_lig31~mcl1_lig2`

I get this error message:

`Traceback (most recent call last):
File "/data/max/devel/BioSimSpace_190430/nodes/playground/prepareFEP.py", line 186, in <module>
    merged = BSS.Align.merge(lig1, lig2, mapping, allow_ring_breaking=node.getInput("allow_ring_breaking"))
TypeError: merge() got an unexpected keyword argument 'allow_ring_breaking'`

I am using the Sire version as of yesterday afternoon and the BioSimSpace version as of this morning. Any idea why merge cannot handle the argument?

**Comment by lohedges** [comment]
Hmm, I'm not sure. How are you installing BioSimSpace: source, binary, or conda? We've been having some issues with our Azure Pipeline (macOS builds aren't working) so it's possible that something is out of sync. I'm also having issues getting the conda package to update correctly with conda update, which was previously working fine.

**Comment by lohedges** [comment]
I've just tested the latest Linux conda package and the `allow_ring_breaking` option works fine.

**Comment by maxkuhn** [comment]
I installed Sire and BioSimSpace from source. I will try the conda package, thanks!

**Comment by maxkuhn** [comment]
The preparation worked fine using the conda installation.
I just looked at the results of 31 <=> 2 and 31 <=> 4  and the energies are reasonable.
Thanks again!
