### ISSUE TITLE
RDKit Dependency

### ISSUE THREAD

**Issue by miroslav351** [michellab/BioSimSpace#85]
Hello,

I have been trying to build a conda package with BioSimSpace as a dependency and I noticed that the package refuses to build when the RDKit software is supplied from `-c conda-forge` rather than `-c rdkit` even if they are supposed to be the exact same version. Does anyone have any ideas why this might be the case?

Many thanks.

**Comment by lohedges** [comment]
Hi there,

I initally thought the same, but it turns out that they pull in different dependencies. The one from the `rdkit` channel uses `defaults` for dependencies, whereas the `conda-forge` one sticks to `conda-forge`. When I try to use the `conda-forge` package I end up with an error when I import RDKit due to a missing `libboost_python` library. This is actually installed, i.e. the one that Sire was built against, but this version doesn't work with RDKit, even though the `conda-forge` install didn't complain or try to pull in a different version. (This makes me think that the dependencies in the recipe for the RDKit `conda-forge` package are incorrectly specified.) For the package from the `rdkit` channel it pulls in a dependency called `pt-boost`, which appears to work fine alongside the bundled `libboost_python`.

Note the order of channels in the BioSImSpace Conda install:

```sh
conda install -c rdkit -c conda-forge -c omnia -c michellab/label/dev biosimspace
```

This makes sure that the `rdkit` channel has highest priority, so you get the package from there rather than `conda-forge`. (If you install the `conda-forge` package you actually end up with an outdated version of RDKit from 2018.)

I hope this helps. It's a pain that things are such a mess, but I'm not sure what else is possible as Conda stands right now. (I don't want to maintain my own versions of all dependencies in a single channel, but that's basically what one needs to do.) No doubt the above install line will no-longer as dependencies are updated.

Cheers.

**Comment by miroslav351** [comment]
Thanks for the reply, this was not obvious at all! Conda dependencies are really a nightmare with all different package flavours from different channels and I can only imagine how difficult it must have been to completely port Sire into Conda in the first place...

**Comment by lohedges** [comment]
No problem, happy to be of help, and I agree that this stuff is far from obvious.

Yes, creating a working Sire Conda package was a massive pain in the proverbial. This is basically why we have always provided binary versions of Sire and BioSImSpace, i.e. have total control over the dependencies, test that it works, etc. However, it turns out that most people love Conda packages :-)
