### ISSUE TITLE
Cannot access tutorials

### ISSUE THREAD

**Issue by atbogetti** [michellab/BioSimSpace#86]
Hello,
This isn't the correct place to ask this but I cannot access your website or find out any way of contacting you other than through Github.  I cannot access the biosimspace tutorials, I keep getting 404 error messages or something saying 'webpage not found'.  Would you be able to upload those somewhere else?  Thanks,
Anthony Bogetti
Graduate student at University of Pittsburgh

**Comment by lohedges** [comment]
Hi there,

Which specific tutorials are you referring to?

We currently have full API documentation with examples on our website:
https://biosimspace.org

There is also a self contained workshop on our notebook server:
https://notebook.biosimspace.org (navigate to the biosimspace_workshop
directory). However, this is a little out of date and is currently in the
process of being updated.

Cheers.

**Comment by atbogetti** [comment]
Thank you for linking those workshop materials. That was just what I was looking for. The website I am referring to is one like this: https://www.biosimspace.org/tutorials/ . It says the server cannot be found for me.
One other question I could not find on the workshop documents: how can I write a trajectory and specify how many steps to write to that trajectory? I tried this in Amber and when I typed traj = system.getTrajectory() and then traj.nFrames() it said I didn’t have any frames. How can I make sure I wrote a trajectory and how can I copy that file to my workstation after the process has completed?

Thanks.

**Comment by lohedges** [comment]
Ah, yes. The new website has a different layout and the old tutorials section is no longer included since the information is (mostly) part of the API documentation.

With regards to the trajectory: when you set a `process` running and do `process.getTrajectory()` you are getting back a BioSimSpace object that wraps around the `MDTraj` and `MDAnalysis` modules, rather than the trajectory file.

At the moment we don't have functionality for writing this object back to disk, but if you wanted to get access to the original trajectory file then you could simply run `process.getOutput(block=True)` to generate a zip file containing all of the output of the process, making sure to block until it actually finishes.

This will create an archive in the current directory which will probably be called `md.zip` or `amber.zip` depending on how you started the process. If you want to give it a different name, you can do `process.getOutput(name="output", block=True)` and if you're running in a Jupyter notebook you can do `process.getOutput(block=True, file_link=True)` to return a download link to the archive.

Hope this helps.
