### ISSUE TITLE
Wrongly detected ring breaking

### ISSUE THREAD

**Issue by maxkuhn** [michellab/BioSimSpace#88]
I was trying to setup the following four perturbations with prepareFEP, using custom mappings:

![bace_prepareFEP_bug](https://user-images.githubusercontent.com/43338350/58164123-211fd000-7c7d-11e9-808a-ca44034920a5.png)

In all cases, I got the error message that the mapping has opened/closed a ring:
`BioSimSpace._Exceptions._exceptions.IncompatibleError: The merge has changed opened/closed a ring! If you want to allow this perturbation, then set the 'allow_ring_breaking' option to 'True'.`

After ensuring that the mappings were correct, I ran prepareFEP with the `--allow_ring_breaking True` flag. I obtained reasonable pert files. However, I noted that some atom names of the phenyl ring (in the centre of the molecules) have changed. As far as I understand, this indicates that these atoms are not recognised as identical by BioSimSpace, despite atom type and parameters staying the same.

It might be that this issue has to do with the aromaticity of R1, since I did not encounter any issues when morphing 37 to ligands containing aliphatic rings at the R1 position (cyclohexyl, -pentyl, -butyl, -propyl). However, I do not see why this should be particularly problematic. Furthermore, it does not explain why 10~14 fails as well.

All relevant files for reproducing this can be found here: 
[prepareFEP_ring_breaking_bug.tar.gz](https://github.com/michellab/BioSimSpace/files/3206667/prepareFEP_ring_breaking_bug.tar.gz)

**Comment by lohedges** [comment]
The renaming is probably because of the way that SOMD implements the perturbation. It does this by mapping atom names from the pert file to those in the AMBER PRM file, which are not necessarily unique. (Index or number would be much more useful!) This means that if a multiple atoms with the same name are perturbed, then we need to rename them with a unique identifier so that SOMD knows to which particular atom the perturbation applies. Note that the update is only performed to the molecule that is used to generate the SOMD input (PERT file and AMBER PRM7/RST7), i.e. the naming in the original molecules is unchanged.

Could you possibly post a snippet from `atoms` record section one of the problem PERT files, since I'm struggling to see one where no parameters are changing. It could be possible that the `charge` or `LJ` properties are different beyond the precision that is written in the PERT file, so the records appear identical.

**Comment by lohedges** [comment]
I've had another quick look at this and noticed that the `allow_ring_breaking=True` option is only required by the `merge` function if you pass the `use_rdkit_prematch=True` option to `matchAtoms`. 

For example, looking at the mapping between ligands 38 and 39, BioSimSpace alone (using Sire's findMCS) matches 34 atoms:

```sh
0 --> 0
1 --> 1
2 --> 2
3 --> 3
4 --> 4
5 --> 5
6 --> 12
7 --> 13
8 --> 14
9 --> 15
10 --> 16
11 --> 17
12 --> 18
13 --> 19
14 --> 20
15 --> 21
16 --> 22
17 --> 23
18 --> 24
19 --> 25
20 --> 26
22 --> 27
23 --> 28
24 --> 29
25 --> 30
26 --> 37
27 --> 38
28 --> 39
29 --> 40
30 --> 41
31 --> 42
32 --> 43
33 --> 44
34 --> 31
```

With the RDKit prematch there is an additional atom match:

```sh
0 --> 0
1 --> 1
2 --> 2
3 --> 3
4 --> 4
5 --> 5
6 --> 12
7 --> 13
8 --> 14
9 --> 15
10 --> 16
11 --> 17
12 --> 18
13 --> 19
14 --> 20
15 --> 21
16 --> 22
17 --> 23
18 --> 24
19 --> 25
20 --> 26
21 --> 6
22 --> 27
23 --> 28
24 --> 29
25 --> 30
26 --> 37
27 --> 38
28 --> 39
29 --> 40
30 --> 41
31 --> 42
32 --> 43
33 --> 44
34 --> 31
```

(21 --> 6)

I've checked the PERT file output in both cases don't find records in the `atom` section where the parameters stay the same. (In some cases the charges are very similar, but differ in the third or fourth decimal place.)

**Comment by maxkuhn** [comment]
> The renaming is probably because of the way that SOMD implements the perturbation.

I am sorry, this issue just slipped my mind. Thanks for the clarification regarding the atom names.

> I've had another quick look at this and noticed that the allow_ring_breaking=True option is only required by the merge function if you pass the use_rdkit_prematch=True option to matchAtoms.

As I used "-mapping xyz.map" I did not explicitly specify not to use the RDKit prematch. However, this match should not be carried out if a mapping is provided - or am I missing something?

> For example, looking at the mapping between ligands 38 and 39, BioSimSpace alone (using Sire's findMCS) matches 34 atoms:

It is interesting that two different mappings are generated, as I originally thought Sire uses an similar method from RDKit. Could you please briefly state which packages are used to match the ligand pair in both cases? I would like to compare the output to an internal mapping tool.

> Could you possibly post a snippet from atoms record section one of the problem PERT files, since I'm struggling to see one where no parameters are changing. It could be possible that the charge or LJ properties are different beyond the precision that is written in the PERT file, so the records appear identical.

I have looked through some of my perturbation files and find the same issue, i.e. the charges often differ in the third/fourth decimal place. However, there are also cases in which the parameters stay the same for some atoms. However, these have been processed with an older version of BioSimSpace:
[BSS_issue088_more.tar.gz](https://github.com/michellab/BioSimSpace/files/3252321/BSS_issue088_more.tar.gz)

**Comment by lohedges** [comment]
> I am sorry, this issue just slipped my mind. Thanks for the clarification regarding the atom names.

No problem. I originally tried to retain sensible atom names, e.g. by appending a number to duplicates, but this became problematic in large systems, and there are often atoms named C1, C2, C3, etc. anyway, so care needed to be taken to make sure that the new names were definitely unique.

> As I used "-mapping xyz.map" I did not explicitly specify not to use the RDKit prematch. However, this match should not be carried out if a mapping is provided - or am I missing something?

Sorry, I didn't spot this. You are correct, the RDKit pre-match will only be used in the absence of a custom user pre-match (with `use_rdkit_prematch=True` also passed).

> It is interesting that two different mappings are generated, as I originally thought Sire uses an similar method from RDKit. Could you please briefly state which packages are used to match the ligand pair in both cases? I would like to compare the output to an internal mapping tool.

They both implement a maximum common substructure search, but there are differences in how the algorithm is implemented. If you want to see how I call the relevant functions from Sire and RDKit, you can look at lines 228 to 276 of [_align.py](https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/Align/_align.py#L228). Note that I pass various options to the RDKit `FindMCS` function, but these don't seem to have any affect on the output. (I've searched online for reasons why, but can't find any answer.) This means we still need to use Sire in order to be able to generate matches between heavy and light atoms, i.e. RDKit is only ever used to generate a prematch, not a full mapping. Since FESetup exclusively uses RDKit for its MCS mappings, and seems to have no problem generating sensible results, I assume that something has changed between RDKit 2016 and 2019 that I don't understand.
 
> I have looked through some of my perturbation files and find the same issue, i.e. the charges often differ in the third/fourth decimal place. However, there are also cases in which the parameters stay the same for some atoms. However, these have been processed with an older version of BioSimSpace:
BSS_issue088_more.tar.gz

I think I used to print data for all atoms in the previous version, not just those that change type, LJ, or charge between the end states. This would explain the records with identical initial and final parameters.

**Comment by lohedges** [comment]
Just to confirm: I processed the data from `BSS_issue088_more.tar.gz` with the latest version of BioSimSpace and found no duplicate parameters in the PERT file. I assume the entries that you were seeing was indeed a result of me writing _all_ atom records to file.

**Comment by maxkuhn** [comment]
Thanks for the feedback, I will check which version of RDKit we are using and whether I can find any inconsistencies.
I just reran the files from 'BSS_issue088_more.tar.gz' and can confirm there are no identical entries in my output files as well.

**Comment by lohedges** [comment]
Just an update to say that I've improved the atom renaming for the SOMD pert file. It is now more inline with what is done in FESetup, i.e. dummy atoms renamed to DU##, where ## is a two digit number. This makes it easier to identify dummy atoms in the lambda = 0 state at a glance. Non-dummy atoms will still be renamed if there are duplicates, and this is still done by appending a random suffix to the name to ensure uniqueness.

**Comment by maxkuhn** [comment]
Great, thanks!

With regard to this:
> I think I used to print data for all atoms in the previous version, not just those that change type, LJ, or charge between the end states.

I am currently running some test cases in which I fiddle around with the charges and automatically redistribute any excess charge equally to all other atoms in the pert file. However, if I was to use newer files generated with BioSimSpace, this could probably cause problems for me, since the total number of atoms in the pert file is likely to be very small.
Would it be possible for you to allow for the generation of a "verbose" pert file which contains all atoms by an additional flag?

**Comment by lohedges** [comment]
Yes, that would be no problem, I'll update the code after lunch. Since all atoms will be recorded in the pert file, I assume that there won't be a problem if the charges are different in the prm7 file since they'll be overwritten by the values in the pert file anyway. This means that you can monkey with the atom parameters in the pert file without breaking things. (This won't be true for other other terms like bonds, angles, dihedrals.)

**Comment by lohedges** [comment]
This is now added. You can pass the option `print_all_atoms=True` to the `_toPertFile` method of the merged molecule. Note that this isn't an option that is used when the SOMD process object configures things for the free energy perturbation simulation, so you'll need to manually create the pert file from the merged molecule. For example, after line 186 in the latest `prepareFEP.py` you could do:

```python
merged._toPertfile(filename="all_atoms.pert", print_all_atoms=True)
```

**Comment by maxkuhn** [comment]
Thanks a lot!
However, when I try to run this, I get the error message `AttributeError: 'Molecule' object has no attribute '_toPertfile'. Do the conda packages take a while to update?

**Comment by lohedges** [comment]
Sorry, there is a typo above, it should read:

```python
merged._toPertFile(filename="all_atoms.pert", print_all_atoms=True)
```
(Upper case F in File.)

The Conda packages take around an hour or so to be updated following a push to devel.

**Comment by maxkuhn** [comment]
Cheers, I had not noticed that.

I assume I did not fully understand your instructions above. At least, I seem to  be missing something. When I run

`~/anaconda3/envs/sire/bin/python /data/max/devel/BioSimSpace_190606/nodes/playground/prepareFEP.py --input1 1b.parm7 1b.rst7 --input2 1d.parm7 1d.rst7 --out `

on the files provided in BSS_issue088_more.tar.gz (cf. above)

using [prepareFEP.txt](https://github.com/michellab/BioSimSpace/files/3262414/prepareFEP.txt) (won't let me upload as .py)

I get the following pert file which does not contain all atoms: [pert.txt](https://github.com/michellab/BioSimSpace/files/3262452/pert.txt)

Any ideas?

**Comment by lohedges** [comment]
If I run the following:

```bash
python prepareFEP.py --input1 1b.parm7 1b.rst7 --input2 1d.parm7 1d.rst7 --out test
```

I get these output files in my working directory:

```
1b_1d.pert
1b.parm7
1b.rst7
1d_1b.pert
1d.parm7
1d.rst7
all_atoms.pert
output.yaml
prepareFEP.py
test.mapping
test.mergeat0.pdb
test.pert
test.prm7
test.rst7
```

If I grep the generated pert files for the number of `endatom` entries I can see how many records there are. (I'll ignore the `1b_1d.pert` file, since this was included in the archive).

First the pert file generate when initialising the SOMD process. (Perturbed atoms only.)

```sh
grep endatom test.pert | wc -l
32
```
Now the file created directly from the merged molecule. (Requesting that all atoms are printed.)

```sh
grep endatom all_atoms.pert | wc -l
52
```

Let's check how many atoms there are in the merged molecule:

```sh
grep ATOM test.mergeat0.pdb | wc -l
52
```

or

```sh
wc -l test.mapping
52
```
As you can see, the `all_atoms.pert` file contains 52 records, i.e. all of the atoms in the merged molecule. Since the `pert.txt` file that you uploaded contains 32 atoms, I can only assume that it is the one generated by the SOMD process.

**Comment by maxkuhn** [comment]
Argh, okay, it seems I am just blind and did not see the all_atoms.pert file at all. Should probably go home for today. Thanks!
