### ISSUE TITLE
BioSimSpace tutorial - minimisation.ipynb notebook

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#9]
The notebook doesn't explain how to write the help file described in 01_introduction.ipynb 

Should --help also reports the expected output of the node ?

**Comment by lohedges** [comment]
Yes, I think you should definitely be able to query the outputs when running from the command-line. At present, `argparse` doesn't make it easy to show these in the same way as the inputs, although I think you can write a completely custom formatted text block. This is probably what we'll want to do anyway since we'll likely have complicated inputs with units, etc, and it would be nice to display those too.
