### ISSUE TITLE
Sample ethane to methanol script with explicit amber. 

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#91]
Sorry this may be a weird repost. I feel like I had this issue before, but in theory the Gromacs and Amber behaviour should be the same, so I am confused why 
I am trying to run the following ethane-> methanol with Amber explicitly:

```
#!/usr/bin/env python
import BioSimSpace as BSS


# We assume the molecules to perturb are the first molecules in each system
ethane = BSS.IO.readMolecules('input/ethane.pdb').getMolecules()[0]
methanol = BSS.IO.readMolecules('input/methanol.pdb').getMolecules()[0]

# parameterise with gaff
ethane = BSS.Parameters.gaff(ethane).getMolecule()
methanol = BSS.Parameters.gaff(methanol).getMolecule()

# creating a mapping between the two ligands and merging them
mapping = BSS.Align.matchAtoms(ethane, methanol)
merged = BSS.Align.merge(ethane, methanol, mapping)


# solvating the merged molecule
solvated = BSS.Solvent.tip3p(molecule=merged, box=3*[40*BSS.Units.Length.angstrom])

# minimisation and equilibration
minimised = BSS.Process.Amber(solvated, BSS.Protocol.Minimisation()) \
               .start().getSystem()

equilibrated = BSS.Process.Amber(minimised, BSS.Protocol.Equilibration()) \
                  .start().getSystem()


# defining the free energy protocol
protocol = BSS.Protocol.FreeEnergy(timestep=2*BSS.Units.Time.femtosecond, runtime=4*BSS.Units.Time.nanosecond, num_lam=9)
freenrg = BSS.FreeEnergy.Solvation(equilibrated, protocol, work_dir="ethane_methanol", engine='SOMD')
freenrg.run()
```
The error I get:
```
Traceback (most recent call last):
  File "amber_ethane_methanol.py", line 22, in <module>
    minimised = BSS.Process.Amber(solvated, BSS.Protocol.Minimisation()) \
  File "/home/ppxasjsm/miniconda3/envs/ucb/lib/python3.7/site-packages/BioSimSpace/Process/_amber.py", line 226, in __init__
    self._setup()
  File "/home/ppxasjsm/miniconda3/envs/ucb/lib/python3.7/site-packages/BioSimSpace/Process/_amber.py", line 283, in _setup
    raise IOError("Failed to write system to 'PRM7' format.") from None
OSError: Failed to write system to 'PRM7' format.

```

Simply replacing Amber with Gromacs the script works fine. 

## Context

* Operating System: Linux
* Installation method: conda dev branch: Sire version: '2019.1.0+86.g9728655'

**Comment by lohedges** [comment]
Only the SOMD and GROMACS processes have support for writing systems containing perturbable molecules. The `AmberPrm7` parser doesn't know how to deal with it, hence the error.

If you want to pre-equilibrate for the SOMD simulations then you do the following:

* Use SOMD as your MD driver. The process will, by default, use the lambda = 0 system and updated copy coordinates back into your original system when you call `getSystem` on the process.
* Use AMBER by passing a property map so that it uses the lambda = 0 properties when writing the input files. You can then use the private `_updateCoordinates` method on your original perturbable system, passing in the minimised/equilibrated system from the process as an argument.

**Comment by ppxasjsm** [comment]
Ah! Good to know. I'll bear that in mind.
