### ISSUE TITLE
Cluster run issue

### ISSUE THREAD

**Issue by dlukauskis** [michellab/BioSimSpace#92]
Currently we are trying to use BSS to replicate the D3R 2018 data set on our local cluster. We modified the template.slm script to fit out cluster's batch system. The issue is running many jobs at the same time, as submitting a couple of them seems to work fine. If you submit a full set of ~40 jobs, currently running jobs can freeze or crash, while newly submitted jobs fail to start, often giving cryptic error messeges, such as the one below.

[error_messege.txt](https://github.com/michellab/BioSimSpace/files/3338097/error_messege.txt)

This isn't a fault of OpenMM, as submitting many OpenMM jobs doesn't raise any issues. Unclear whether or not this is an issue with SOMD or Sire. If each individual lambda calculation is submitted with just a somd-freenrg command, the issue is alleviated somewhat, but a lot of jobs still crash with a CUDA error.

[cuda_error.txt](https://github.com/michellab/BioSimSpace/files/3338096/cuda_error.txt)

Our cluster uses LSF scheduler (bsub).

[modified_submit.txt](https://github.com/michellab/BioSimSpace/files/3338103/modified_submit.txt)
[modified_template.txt](https://github.com/michellab/BioSimSpace/files/3338104/modified_template.txt)

**Comment by lohedges** [comment]
Hi there,

The error message in [error_messege.txt](https://github.com/michellab/BioSimSpace/files/3338097/error_messege.txt) comes from [here](https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireBase/process_unix.cpp#L376). Sire is trying to use `fork` to create a background process in which to run the free energy simulation, but it is failing. This could happen if existing processes have grabbed too many resources.

We actually updated the code to use GROMACS as the default free energy engine, rather than SOMD. However, this has caused problems on some platforms since sometimes GROMACS hardware auto-detection see the resources of the _whole_ cluster (rather than a node) and consumes too much. Also, the GROMACS free energy kernel isn't well optimised for GPU so simulations are rather slow, and appear to not work well on multi GPU nodes.

Could you try passing "engine=SOMD" on this line in `binding_freenrg.py`:

```python
freenrg = BSS.FreeEnergy.Binding(solvated, protocol, engine="SOMD", work_dir="CatS_%s_%s" % (num0, num1))
```

Let me know if that makes any difference. I've since changed the default back to SOMD on a feature branch, but haven't merged this into devel.

Just to note that we have found issues with the ligand data set used for the D3R 2018 run and are trying to resolve it. A colleague discovered that the ligands were badly prepped, leading to poor confirmations with bad charge distributions. If you are using the original data from [here](https://github.com/michellab/D3R2018), then you will also get poor results. (If you are just trying to get the infrastructure up and running, then no problems.)

**Comment by lohedges** [comment]
Also, when you tried running directly with `somd-freenrg`, the error was likely a result of multiple simulations trying to run on the same GPU within a node, i.e. the node was allocated to the first job, then a second job tries to access the same GPU id. In my original batch script I had some hacks to switch the order of the CUDA_VISIBLE_DEVICES array to make sure that OpenMM picked the right GPU.

**Comment by bcossins** [comment]
Hi, 
-Dom has tried the passing of "engine=SOMD" on the line in binding_freenrg.py.
-We routinely run amber, desmond and openMM simulations on our GPU clusters using the LSF template in the first post which uses exclusive mode. I think for amber it may skip around until it finds a free GPU and we don't define CUDA_VISIBLE_DEVICES manually. Have you ever used somd-freenrg with LSF? which scheduler do you use it with?

Thanks
Ben

**Comment by lohedges** [comment]
I've only run on clusters using SLURM. Depending how things are set up, SLURM will correctly set CUDA_VISIBLE_DEVICES for you. I've only needed to override this when I run jobs that launch two single GPU simulations on a node with two GPUS. (Forward simulation on the first GPU, reverse on the second.)

SOMD must use 0 as the gpu id variable for single GPU jobs as this is passed through to OpenMM, which uses it as an index into the CUDA_VISIBLE_DEVICES array. If a single GPU is requested, then OpenMM assumes that there is only one entry in this array. (Even if two GPUs are visible to the job.) This means I needed to swap the order of the indexes for the reverse job, i.e.:

```
# Forward simulation, run on the first gpu.

# SOMD cfg file entry.
gpu=0

# Environment variable.
CUDA_VISIBLE_DEVICES=0,1

# Reverse simulation, run on the second gpu.

# SOMD cfg file entry.
gpu=0

# Environment variable.
CUDA_VISIBLE_DEVICES=1,0
```

(See [here](https://github.com/michellab/D3R2018/blob/a71570c12546ffb73a300db72ced44a2cab5f16c/CatS/BSS/template.slm) for how this was used.)

(This issue is discussed in more detail [here](https://github.com/michellab/BioSimSpace/issues/35).)

You'd think it would be possible to set the SOMD gpu id to 1, which would correctly index device 1 if CUDA_VISIBLE_DEVICES was set to 0,1 but this didn't seem to work for some reason.

Eventually, BIoSimSpace will have automatic hardware detection so it will work out the number of available GPUs on start up, then set all of the environment variables and parameters for you automatically.

**Comment by bcossins** [comment]
Thanks,
We have been through this process for a few different systems now including YANK which uses openMM. The best weay seems to be to get the interation with the scheduler correct and allow the scheduler to choose the GPUs used.
LSF serves up the correct CUDA_VISIBLE_DEVICES for the requested resources so does that mean that SOMD should be picking this up and using the correct GPU? From what I read above I understood that SOMD cannot read CUDA_VISIBLE_DEVICES or at least the GPU you wish SOMD to use must be listed first in the CUDA_VISIBLE_DEVICES variable?

We have 8 GPUs per node, we can ask for two on the same node and then read the CUDA_VISIBLE_DEVICES from LSF and serve them up as you suggest with each one lists first in turn. Is this the best thing to do?
YANK had a nice way of doing this for LSF - https://github.com/choderalab/clusterutils/blob/master/clusterutils/build_mpirun_configfile.py

**Comment by dlukauskis** [comment]
I've tried running multiple jobs in parallel on a single node with the following script, and the same problem persists. All 8 jobs run okay while setting up the folders but as soon as somd-freenrg code starts running, the simulations crash without an obvious error messege. After killing the job on the cluster, I got the following error file. 

[new_submit.txt](https://github.com/michellab/BioSimSpace/files/3345600/new_submit.txt)

[stderr.txt](https://github.com/michellab/BioSimSpace/files/3345596/stderr.txt)

Any suggestions on what might be happening?

**Comment by lohedges** [comment]
Hi, sorry for the slow reply.

> From what I read above I understood that SOMD cannot read CUDA_VISIBLE_DEVICES or at least the GPU you wish SOMD to use must be listed first in the CUDA_VISIBLE_DEVICES variable?

As you say, just leaving things to the scheduler seems to play nicely with OpenMM. However, SOMD is a wrapper around OpenMM and, for some reason, it seems to specify the GPU index (CUDA_VISIBLE_DEVICES index) that is passed to OpenMM in its own config file. This is a real pain if you don't know what GPU will be available when the job actually starts running. (A real pain when you don't have exclusive access to the node.)

> All 8 jobs run okay while setting up the folders but as soon as somd-freenrg code starts running, the simulations crash without an obvious error messege.

I'm wondering if SOMD is consuming too many resources when it launches. If you notice, the `sire_python` command in your [submit script]([https://github.com/michellab/BioSimSpace/files/3345600/new_submit.txt) takes the command-line argument `--ppn=1`. This is so that `sire_python` only runs in a single thread. However, `somd-freenrg` itself launches `sire_python`, but places no restriction on the resources that it uses. (By default, it will try to run on as many threads as possible.) At present, it looks like there isn't a way to pass the argument through to SOMD. (I'll investigate further.) That said, I've not had issues doing the same thing, so this might not be the source of the problem.

Once again, the error messages in [stderr.txt](https://github.com/michellab/BioSimSpace/files/3345596/stderr.txt) are a result of Sire failing to fork a background process in which to run the free energy simulation. Have you had any previous issues forking on your cluster? In the past, I've had some weird issues on certain infiniband networks, although that was for jobs run with mpirun. Could you possible try submitting a job based on something like the following C code:

```c
#include <stdio.h>
#include <sys/types.h>

int main()
{
    pid_t pid = fork();

    if (pid == -1)
    {
        printf("Fork failed!\n");
    }
    else
    {
        printf("Fork successful!\n");
    }

    return 0;
}
```

Jusing paste into a file and save as something like `fork_test.c`, then compile as:

```sh
gcc fork_test.c -o fork_test
```

Then run as:

```sh
./fork_test
```

**Comment by jmichel80** [comment]
Hi,

@lohedges if you use -d X as command line argument you can specify the gpu device id when launching somd-freenrg

See 

https://github.com/michellab/Sire/blob/devel/wrapper/python/scripts/somd-freenrg.py

wouldn’t that be sufficient to resolve the issue?

Julien

**Comment by lohedges** [comment]
Here's a minimal `Sire.Base.Process` example that you could try too:

```python
from Sire.Base import Process

process = Process.run("echo", "Hello, World!")
process.wait()
```

Save it to a Python script and run it with `sire_python`.

**Comment by lohedges** [comment]
Hi @jmichel80,

Thanks for pointing out the command-line option. There will still be the same problem: See [here](https://github.com/michellab/BioSimSpace/issues/35) for details. Basically, this isn't actually a device index, rather an index into the CUDA_VISIBLE_DEVICES array. Consequently, the index must always be less than the number of entries in the array, so must always be zero for a single GPU job if only one device is visible, regardless of the actual real GPU index in the array. It's also hard to know whether the CUDA_VISIBLE_DEVICES will have even been set, or if it's set correctly if it has.

It's trivial to get things to work properly if you have exclusive node access, since you know all of the GPU ids and can either increment the index, or re-order the CUDA_VISIBLE_DEVICES array. However, it's tricky when you're submitting a job on a shared node. When I get time, I plan on adding better functionality to BioSimSpace so that it can autodetect the resources that are available at run time and set things up appropriately.

**Comment by dlukauskis** [comment]
Both C fork and the Sire.Process tests ran fine, no crashes and no errors, produced expected outputs. I think the problem might be, like @lohedges suggested, that somd-freenrg code initially tries to use all available cores on a node to start the process, so when multiple jobs try to do that at the same time, they all crash. When the node only has 2 GPUs and 24 cores, running two simultanous processes is possible, but if the nodes are GPU-heavy (8 GPUs, 24 cores/node) submitting 8 jobs per node probably consumes too much CPU. 

Since your cluster is different to ours, I'm not sure how you could test this hypothesis. Try to run somd-freenrg on a node with other CPU-consuming processes already running?

**Comment by lohedges** [comment]
Great, thanks for checking the fork examples.

It's possible to launch the `somd-freenrgy` script using `sire_python` as follows (this assumes a `sire.app` install, paths will be different with Conda):

```sh
 ~/sire.app/bin/sire_python ~/sire.app/share/Sire/scripts/somd-freenrg.py
```

(The actual `somd-freenrg` executable is basically a wrapper to do this for you.)

We could then restrict the number of CPUs as follows:

```sh
 ~/sire.app/bin/sire_python --ppn=1 ~/sire.app/share/Sire/scripts/somd-freenrg.py
```

You could try this directly, or I could send you a modified version of [_somd.py](https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/Process/_somd.py) which you could copy into the right place in the BioSimSpace Python library.

**Comment by lohedges** [comment]
Annoyingly, it looks like there's a bug in `somd-freenrgy` which means that modifying the BioSimSpace code won't work!

If I run the apps directly and pass the number of processors on the command-line: 

```sh
~/sire.app/bin/somd --ppn=1
```

This works as expected with the first line of output being:

```
Starting /home/lester/sire.app/bin/somd: number of threads equals 1
```

However, doing the same for `somd-freenrg`:

```
~/sire.app/bin/somd-freenrg --ppn=1
```

Gives:

```
Starting /home/lester/sire.app/bin/somd-freenrg: number of threads equals 1
  File "/home/lester/sire.app/share/Sire/scripts/somd-freenrg.py", line 1
    Python 3.7.2 (default, Dec 29 2018, 06:25:15)
```

This is why I didn't think that it was passing the arguments through to `sire_python` correctly, although `somd` works so it should do. I'll try to fix this.

**Comment by lohedges** [comment]
Ah, turns out my local `somd-freenrg` is corrupted. You can get an updated version of `_somd.py` that uses a single core [here](https://github.com/michellab/BioSimSpace/files/3346545/_somd.txt). Save this as `_somd.py`, then copy to, e.g:

For Conda:

```
cp _somd.py ~/.conda/envs/biosimspace/lib/python3.7/site-packages/BioSimSpace/Process
```

A Sire or BioSimSpace app (rename path as appropriate):

```
cp _somd.py ~/sire.app//lib/python3.7/site-packages/BioSimSpace/Process
``` 

Let me know if this fixes things and I'll update the BioSimSpace code. SOMD is super slow on CPU anyway so it's probably not an issue to restrict the number of threads.

**Comment by jmichel80** [comment]
Hi,

The problem could also be memory usage when several multi threaded jobs attempt to load a large system.

We have dealt with this in the past with somd by setting in the submission script the environment variable OMP_NUM_THREADS to 1. This should give equivalent behaviour to —ppn=1 but should work with vanilla somd-freenrg. 
This can be verified by login on a node where a job had just started and checking the CPU usage per somd-freenrg process does not go above 100%.

J

**Comment by lohedges** [comment]
Thanks @jmichel80, that's a good suggestion. That way we can keep using a multi-threaded SOMD, but deal with situations where it is problematic without directly modifying the code.

**Comment by dlukauskis** [comment]
New _somd.py script worked, no more issues with running multiple jobs on the same node. Thanks!

**Comment by lohedges** [comment]
Thanks for the update.

Could you confirm if it also works when setting the `OMP_NUM_THREADS=1` environment variable, since this would be the preferable solution. If so, then I'll leave the code as is and update the SOMD documentation within BioSimSpace to highlight the issue.

**Comment by lohedges** [comment]
Remember to use the old `_somd.py` script when testing `OMP_NUM_THREADS`.

**Comment by lohedges** [comment]
I've tested with `OMP_NUM_THREADS` and it doesn't work. Instead, I will expose an environment variable to sire, `SIRE_NUM_THREADS`, that will be used if `--ppn` isn't passed on the command-line. This way we can easily fix SOMD in batch scripts without modifying the BIoSimSpace code, which would required passing through an argument for `--ppn` in numerous places.

**Comment by lohedges** [comment]
This is now added to Sire and will be supported in BioSimSpace when the next Conda package is built against it. You can restrict the number of threads using either the `OMP_NUM_THREADS` or `SIRE_NUM_THREADS` environment variables, or by using the `--ppn` command-line argument. The command-line argument takes precedence over `SIRE_NUM_THREADS`, which takes precedence over `OMP_NUM_THREADS`.
