### ISSUE TITLE
Somd-freenrg error

### ISSUE THREAD

**Issue by dlukauskis** [michellab/BioSimSpace#94]
We're trying to use BSS (master branch) for free energy calculations by running D3R2018 setup. While most ligand pairs are running fine, some however raise an OpenMM/Somd error, as attached below. This happens with CatS pairs 195 30, 4 9 and 79 252. I have tested this on my work station and the local cluster, so it's unlikely to be hardware-related.
[somd.txt](https://github.com/michellab/BioSimSpace/files/3363226/somd.txt)

**Comment by lohedges** [comment]
Could you possibly try the devel branch, this has numerous improvements and fixes to the MCS matcher and SOMD perturbation file writer, which are the likely culprits here. The issue is probably because there are too many perturbations in the file, which has caused a buffer overflow on the GPU. I had similar issues when first running SOMD free energy calculations since I was writing _all_ information to the perturbation file, rather than just those terms that change (for ease of debugging). It's possible that there are just a lot of terms for these ligand pairs, so I'm not sure what we'd do as a fix in those situations. I'll take a look at the particular pairs to see what the SOMD files look like.

**Comment by lohedges** [comment]
Also, as mentioned in the other issue thread, there are issues with the CatS ligand set so I wouldn't advise running large scale production simulations until they are fixed.

**Comment by lohedges** [comment]
I've looked at the ligand pairs and these were known to be problematic during our D3R run. Typically, each ligand in the data set contains around 90-100 atoms and we would expect a reasonable mapping to match 80-90 atoms. For these pairs we get the following results (this is using the mappings used in the original D3R run).

195 <--> 30: 29 atoms match
4 <--> 9: 29 atoms match
79 <--> 252: 28 atoms match

Because of the low number of atoms in the MCS mappings the perturbation involves a large number of dummy atom records in the perturbation file, leading to the overflow that you are observing. This may not occur on all GPU clusters depending on the amount of memory available. Note that there are modifications to dihedral/improper terms involving dummy atoms (see [here](https://github.com/michellab/BioSimSpace/issues/74) for details) so there are a large number of these records in the perturbation file.

With the latest development code it is not even possible to merge the molecules based on the poor mappings since they involve perturbations that break rings (which isn't allowed by default). At such, the code would have raised an exception and exited before running the SOMD simulation.
