### ISSUE TITLE
Issues with reading files

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#96]
I am struggling to read in the following two files, that upon first glance look ok. 
VMD can't seem to read them either. 
[001.setup.zip](https://github.com/michellab/BioSimSpace/files/3416925/001.setup.zip)

The error I get is:
```
 mol = BSS.IO.readMolecules(["004_merged.rst7", "004_merged.prm7"])                                                    
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-909f447aa5c0> in <module>
----> 1 mol = BSS.IO.readMolecules(["004_merged.rst7", "004_merged.prm7"])

~/miniconda3/lib/python3.7/site-packages/BioSimSpace/IO/_io.py in readMolecules(files, property_map)
    287             raise IOError(msg) from None
    288         else:
--> 289             raise IOError("Failed to read molecules from: %s" % files) from None
    290 
    291     return _System(system)

OSError: Failed to read molecules from: ['004_merged.rst7', '004_merged.prm7']
```

**Comment by lohedges** [comment]
Hi @ppxasjsm, are these files what BioSimSpace generates as input for SOMD, or are you writing them some other way?

As mentioned before, we currently don't have support for reading topology/coordinate files for merged molecules. They are purely created for use as input for SOMD/GROMACS, so won't work with any other package/viewer. You also can't just write a merged molecule to file, you need to pass it to an appropriate free energy driver which will write the correct format files to run your calculation. If you just want to visualise the molecule at one of the lambda end points (with appropriate dummy atoms), then you'll need to use the property map, as was done in your free energy workshop. (Perhaps I should forbid writing of systems containing a merged molecule unless it is done during a free energy simulation set up.)

It would be possible to create a reader for the GROMACS perturbed topology since all the information is in the one file. However, the AMBER files are meaningless without the SOMD pert file too. (They only represent the lambda = 0 state with some naming and ordering tweaks.)
